export const en = {
  locale: 'en',
  altHome: '/es/',
  altLocale: { code: 'es', label: 'Español', href: '/es' },
  home: '/',
  meta: {
    title: 'Property Lawyers in Sotogrande and the Costa del Sol',
    description:
      'Property lawyers in Sotogrande and the Costa del Sol. Independent legal advice for foreign buyers on purchase, residency and tax. Rated 5.0 from 53 Google reviews.',
  },
  topbar: { blurb: 'Independent legal advice for property buyers in Sotogrande', hours: 'Mon to Fri, 9:00 to 17:00' },
  nav: [
    { label: 'Buying property', href: '/buying-property/' },
    { label: 'Residency', href: '/residency-and-visas/' },
    { label: 'Tax', href: '/tax-and-accountancy/' },
    { label: 'About', href: '/about/' },
    { label: 'Insights', href: '/blog/' },
    { label: 'Contact', href: '/contact/' },
  ],
  navServices: [
    { label: 'Buying property', href: '/buying-property/' },
    { label: 'Selling property', href: '/selling-property/' },
    { label: 'Residency & visas', href: '/residency-and-visas/' },
    { label: 'Tax & accountancy', href: '/tax-and-accountancy/' },
    { label: 'Property management', href: '/property-management-services/' },
    { label: 'Gibraltar & Spain', href: '/gibraltar-and-spain/' },
    { label: 'Property law', href: '/property-law/' },
    { label: 'The Golden Visa', href: '/spanish-golden-visa/' },
  ],
  navFirm: [
    { label: 'About Esther', href: '/about/' },
    { label: 'Full client service', href: '/full-client-service/' },
    { label: 'Immigration procedures', href: '/immigration-and-foreigners-legal-procedures/' },
    { label: 'Insights', href: '/blog/' },
    { label: 'Contact', href: '/contact/' },
  ],
  navLabels: { services: 'Services', firm: 'Firm' },
  cta: { primary: 'Get in touch', call: 'Call the office', consult: 'Write to Esther' },
  hero: {
    eyebrow: 'Abogada \u00b7 Sotogrande, C\u00e1diz',
    h1: 'Property lawyers in Sotogrande and the Costa del Sol',
    sub: 'Independent legal advice for buying, selling and owning property in Spain.',
    lede: 'An English-speaking Spanish lawyer specialising in property law for foreigners investing in, and relocating to, Spain. Qualified in Barcelona in 1983, based in Sotogrande since 1990.',
    strap: '\u201cMaking the client feel safe at home.\u201d',
    secondary: 'How we work with you',
    reviews: '53 Google reviews',
  },
  trust: [
    { v: 'Since 1983', k: 'Qualified in Barcelona' },
    { v: 'Sotogrande', k: 'Based here since 1990' },
    { v: '3 jurisdictions', k: 'UK, Gibraltar & Spain' },
    { v: 'EN / ES', k: 'Fluent in both languages' },
  ],
  intro: {
    eyebrow: 'How we work',
    h2: 'We take you by the hand through the whole process',
    p1: 'Buying or owning property in another country involves people, offices and paperwork you have not met before. My team and I handle all of it, from the first enquiry through to completion and for as long afterwards as you need us.',
    p2: 'We can begin before you even step onto Spanish soil, and we stay with you afterwards for the tax returns, the residency paperwork and everything else that comes with owning something here.',
    cta: 'Tell us what you are planning',
  },
  services: {
    eyebrow: 'Services',
    h2: 'What I handle',
    sub: 'Most clients arrive for a purchase and stay for everything that follows: the tax returns, the residency paperwork, the sale years later.',
    more: 'Read more',
    items: [
      { slug: 'buying-property', img: 'villa-pool-costa-del-sol', tag: 'Most requested', title: 'Buying property',
        text: 'Full conveyancing from NIE to keys. Registry checks, contract review, tax calculation and completion before the notary.' },
      { slug: 'residency-and-visas', img: 'spanish-visa-application', tag: 'Updated 2026', title: 'Residency & visas',
        text: 'The Golden Visa closed in April 2025. The non lucrative, digital nomad and family routes remain open, and I file them.' },
      { slug: 'tax-and-accountancy', img: 'coastal-property-costa-del-sol', title: 'Tax & fiscal',
        text: 'Tax returns for non residents, ITP and plusval\u00eda on purchase, plus the annual obligations of owning Spanish property.' },
      { slug: 'selling-property', img: 'property-keys-handover-spain', title: 'Selling property',
        text: 'Capital gains, the 3% retention applied to non residents, and getting your proceeds out of Spain cleanly.' },
      { slug: 'property-management-services', img: 'yachts-puerto-sotogrande', title: 'Property management',
        text: 'Utilities, community fees, insurance and keyholding for owners who are not here all year.' },
      { slug: 'gibraltar-and-spain', img: 'rock-of-gibraltar-from-spain', tag: 'Two jurisdictions', title: 'Gibraltar & Spain',
        text: 'Frontier workers, Gibraltar companies holding Spanish property, and residents moving between the two jurisdictions.' },
    ],
  },
  checks: {
    eyebrow: 'Due diligence',
    h2: 'How we guide you through a purchase',
    sub: 'These are the steps we take care of on your behalf, so that by the time you commit you know exactly what you are buying.',
    items: [
      { icon: 'doc', title: 'Nota simple', text: 'Who actually owns the property, and exactly what is registered against it at the Land Registry.' },
      { icon: 'coin', title: 'Debts & charges', text: 'Any mortgage, community fee, IBI or other charge registered against the property, so that everything is clear at completion.' },
      { icon: 'plan', title: 'Licences & planning', text: 'That the build is licensed and declared, and that the registry, the catastro and what you have seen all agree.' },
      { icon: 'sign', title: 'Contrato de arras', text: 'We read the reservation contract before you sign it, and discuss any amendment worth making.' },
      { icon: 'calc', title: 'Your real costs', text: 'The taxes and official fees for your particular purchase, set out in advance so the figures are known.' },
      { icon: 'home', title: 'Utilities & community', text: 'Supply contracts, meter readings and community status confirmed and transferred at completion.' },
    ],
  },
  reviews: {
    eyebrow: 'Client reviews',
    h2: 'What clients say',
    sub: 'Every review below was left publicly on Google. Not one is under five stars.',
    average: 'Average from 53 Google reviews',
    verified: 'Verified on Google',
    swipe: 'Swipe for more reviews',
    bandTitle: 'Was I your lawyer?',
    bandText: 'A review takes a minute and it genuinely helps other buyers find independent advice.',
    leave: 'Leave a review',
    readAll: 'Read all 53 reviews',
    items: [
      { initial: 'J', name: 'J., United Kingdom', matter: 'Property purchase',
        text: 'I am so incredibly grateful we found Esther. She was wonderful to work with from beginning to end, and helped us understand the purchasing process at every stage.' },
      { initial: 'S', name: 'S., United Kingdom', matter: 'Property purchase',
        text: 'She helped us understand the purchasing process and stepped in to avoid us making costly mistakes on a property that was fraught with issues.' },
      { initial: 'M', name: 'Mark, United Kingdom', matter: 'Property purchase',
        text: 'Speaking no Spanish, it was essential that I fully understood the process of purchasing a property in Spain. Esther explained exactly what was going on every step of the way.' },
      { initial: 'R', name: 'R. and family', matter: 'Purchase, utilities, residency',
        text: 'Over eight months she guided us through the purchase, the set up of all utilities, local authority documentation and our visas. What could have been daunting and confusing was made simple.' },
    ],
  },
  about: {
    eyebrow: 'About',
    h2: 'Esther Pujol Wilkie',
    role: 'Founding partner \u00b7 Abogada',
    p1: 'I was born in Barcelona and studied law there, and I have practised in the United Kingdom, Gibraltar and Spain. For the last thirty years or so I have worked from Sotogrande, almost entirely with foreign clients meeting Spanish law for the first time.',
    p2: 'That means property, but it also means the tax office, the town hall, the immigration office and everything else that comes with owning something here. My clients tend to arrive nervous and stay for decades.',
    creds: [
      ['Qualified', 'Law degree, Barcelona'],
      ['Jurisdictions', 'Spain, Gibraltar and the United Kingdom'],
      ['Languages', 'Spanish and English'],
      ['Colegio', 'ICA Cádiz, nº 1432'],
      ['Practising since', '2 July 1990'],
      ['Recent training', 'Competencias Digitales Profesionales, CGAE, 150h, 2026'],
    ],
    credPending: null,
    chips: [
      { icon: 'shield', text: 'Colegiada nº 1432, ICA Cádiz, desde 1990' },
      { icon: 'list', text: 'Agencia Tributaria filings' },
      { icon: 'globe', text: 'Cross border Gibraltar work' },
    ],
  },
  faq: {
    eyebrow: 'Common questions',
    h2: 'What buyers usually ask first',
    items: [
      { q: 'Can I still get residency by buying a property?',
        a: 'No. Spain\u2019s Golden Visa was repealed by Organic Law 1/2025 and stopped accepting new applications on 3 April 2025. You can still buy freely as a foreigner, but the purchase no longer grants a residence permit. If residency is your goal, the non lucrative visa, digital nomad visa and family routes all remain open, and I can advise on which one fits your circumstances.' },
      { q: 'What is an NIE and when do I need one?',
        a: 'The NIE (N\u00famero de Identificaci\u00f3n de Extranjero) is your Spanish tax identification number. You need one to buy property, open a bank account or pay tax here. I can obtain it on your behalf, and it is usually the first thing we start.' },
      { q: 'Can you act for me if I am not in Spain?',
        a: 'Yes. With a power of attorney I can complete the entire purchase on your behalf, including signing at the notary. Many clients complete without travelling.' },
      { q: 'What will the purchase actually cost me beyond the price?',
        a: 'There are taxes and official fees on any Spanish purchase, and they vary with the property and how it is bought. We set out the figures for your particular purchase at the outset, so nothing arrives unexpectedly.' },
      { q: 'Do you speak English?',
        a: 'Yes, English and Spanish both fluently. Most of my clients speak no Spanish at all. Everything is explained in plain English, including every document you will be asked to sign.' },
    ],
  },
  blogBase: '/blog',
  insights: {
    eyebrow: 'Insights',
    h2: 'Notes on Spanish property law',
    items: [
      { slug: "spain-golden-visa-guide", metaDesc: "Spain’s Golden Visa closed to new applications on 3 April 2025. What happens to existing holders, and the residency routes still available in 2026.", sections: [{"h2": "What changed", "p": ["The Residency Visa for Investors, known everywhere as the Golden Visa, was introduced in 2013 to encourage investment into Spain. It was repealed by Organic Law 1/2025 and stopped accepting new applications on 3 April 2025.", "Buying property here remains entirely open to foreign nationals. It simply no longer carries an entitlement to residency."]}, {"h2": "If you hold one already", "p": ["The transitional provisions protect existing holders. Where the authorisation was granted, or the application filed, before the cut off date, the position continues and renewal remains available while the original conditions are met.", "If you are considering selling the property the visa was based upon, or you are approaching ten years of legal residency, it is worth a conversation first. There are usually more options than people expect."]}, {"h2": "What people ask instead", "p": ["The common question is which route replaces it, and the honest answer is that none does exactly. The Golden Visa was unusual in asking very little in the way of presence in Spain. Every route now available expects you to spend a meaningful part of the year here.", "The non lucrative route suits those with sufficient means who will not work in Spain. The digital nomad visa suits those working remotely for companies elsewhere. There are also entrepreneur, highly qualified employment and family routes. Which one fits depends on how you earn."]}, {"h2": "A word on tax", "p": ["Residency and tax residency are different things. Spending more than 183 days a year in Spain will generally make you tax resident here on your worldwide income. Because the remaining routes expect real presence, this now affects far more applicants than it used to, and it is much better considered before an application than after."]}], cat: "Residency", title: "The Golden Visa has closed. What now?",
        text: "The investor residency route ended in April 2025. What it means for existing holders and which routes remain open." },
      { slug: "contrato-de-arras", metaDesc: "The Spanish reservation contract explained: the three types of arras, what happens if a mortgage is refused, and why it is worth reading before signing.", sections: [{"h2": "What the contract does", "p": ["The contrato de arras is the reservation contract, and it is usually the first document a buyer signs and the point at which a deposit is paid. It fixes the price, the parties and the date for completion, and takes the property off the market while the purchase is prepared.", "It is a useful document and there is nothing unusual about it. It simply repays reading carefully, because the different forms of arras have quite different consequences."]}, {"h2": "The three forms", "p": ["Arras penitenciales are the most common. They allow either party to withdraw: the buyer forfeits the deposit, the seller repays double. Arras confirmatorias confirm the sale and do not provide for withdrawal in the same way. Arras penales set a penalty while leaving the sale enforceable.", "The heading on the document does not always match the terms beneath it, which is why we read the clauses rather than the title."]}, {"h2": "Two clauses worth attention", "p": ["The first is what happens if a mortgage is not granted. Where the contract makes no express provision, the buyer carries that risk. It is a straightforward point to agree at the outset.", "The second is the completion date and what follows if the seller is not ready, for instance because a charge has still to be cancelled. A little flexibility written in at this stage saves a good deal of difficulty later."]}, {"h2": "Our advice", "p": ["Let us see the contract before you sign it. The searches, the registry position and the planning status all belong at this stage rather than afterwards, and any amendment worth making is far easier to agree before the deposit has been paid than after."]}], cat: "Buying", title: "Understanding the contrato de arras",
        text: "The reservation contract is the first document most buyers sign. A short guide to what it does and what to look for." },
      { slug: "non-resident-tax", metaDesc: "The annual filings for non resident property owners in Spain: the return that applies even when the property is empty, IBI, community fees and rental income.", sections: [{"h2": "The annual return", "p": ["A non resident owner files an annual return whether or not the property is let. Where it sits empty, the tax is calculated from the cadastral value rather than from any income received.", "It surprises many owners that an unused property produces a filing at all. It does, every year, and unfiled returns accumulate quietly until they surface at the point of sale."]}, {"h2": "The rest of the picture", "p": ["IBI is charged by the town hall and is usually the largest recurring item. Community fees apply where the property forms part of a community of owners. There may also be refuse charges and, above certain thresholds, wealth tax, which varies between regions.", "Where the property is let, income is declared quarterly, and the treatment differs depending on where you are tax resident. Since Brexit this affects British owners in particular."]}, {"h2": "Why it is worth keeping current", "p": ["Individually these are modest sums. The difficulty is that municipal charges and community fees attach to the property rather than to the owner, so they follow it to a sale, often years later.", "Keeping everything current is considerably easier than resolving it under time pressure with a buyer waiting. It is a service we provide for most of the clients whose property we look after."]}], cat: "Tax", title: "What a non resident owner files each year",
        text: "A short summary of the annual obligations that come with owning a property in Spain from abroad." },
    ],
  },
  contact: {
    eyebrow: 'Get in touch',
    h2: 'Write to Esther',
    sub: 'Tell me a little about what you are planning and I will reply personally, usually within one working day.',
    labels: { office: 'Office', phone: 'Telephone', email: 'Email', hours: 'Hours', languages: 'Languages',
      first: 'First name', surname: 'Surname', email: 'Email', tel: 'Telephone',
      matter: 'How can I help?', area: 'Area', message: 'Your message' },
    placeholder: 'A sentence or two about what you are planning is plenty.',
    consent: 'I have read the privacy policy and consent to being contacted about my enquiry.',
    send: 'Send enquiry',
    sending: 'Sending\u2026',
    ok: 'Thank you. Your enquiry has been sent and I will reply personally, usually within one working day.',
    err: 'That did not send. Please email or call the office directly and I will pick it up.',
    matters: ['Buying a property', 'Selling a property', 'Residency or visa', 'Tax return or fiscal',
      'Property management', 'Gibraltar and Spain matter', 'Something else'],
    areas: ['Sotogrande', 'San Roque', 'Estepona', 'Marbella', 'Casares or Manilva', 'Gibraltar',
      'Elsewhere in Spain', 'Not decided yet'],
  },
  footer: {
    blurb: 'Independent legal advice in English and Spanish for property buyers and owners in Sotogrande and the Campo de Gibraltar.',
    services: 'Services', firm: 'Firm',
    more: 'Practice areas',
    legacyLinks: [
      { label: 'Property law', href: '/property-law/' },
      { label: 'The Golden Visa', href: '/spanish-golden-visa/' },
      { label: 'Immigration procedures', href: '/immigration-and-foreigners-legal-procedures/' },
      { label: 'Full client service', href: '/full-client-service/' },
    ],

    firmLinks: [
      { label: 'About Esther', href: '/about/' },
      { label: 'Client reviews', href: '/#reviews' },
      { label: 'Insights', href: '/blog/' },
      { label: 'Contact', href: '/contact/' },
    ],
    legal: [
      { label: 'Aviso legal', href: '/aviso-legal' },
      { label: 'Pol\u00edtica de privacidad', href: '/politica-de-privacidad' },
      { label: 'Pol\u00edtica de cookies', href: '/politica-de-cookies' },
    ],
    place: 'La Marina de Sotogrande \u00b7 C\u00e1diz \u00b7 Espa\u00f1a',
    poweredBy: 'Powered by',
  },
};
export default en;
