export const en = {
  locale: 'en',
  altHome: '/es/',
  altLocale: { code: 'es', label: 'Español', href: '/es' },
  home: '/',
  meta: {
    title: 'Property Lawyers in Sotogrande and the Costa del Sol',
    description:
      'Property lawyers in Sotogrande and the Costa del Sol. Independent legal advice for foreign buyers on purchase, residency and tax. Rated 5.0 from 53 Google reviews.',
  },
  topbar: { blurb: 'Independent legal advice for property buyers in Sotogrande', hours: 'Mon to Fri, 9:00 to 17:00' },
  nav: [
    { label: 'Buying property', href: '/buying-property/' },
    { label: 'Residency', href: '/residency-and-visas/' },
    { label: 'Tax', href: '/tax-and-accountancy/' },
    { label: 'About', href: '/about/' },
    { label: 'Insights', href: '/blog/' },
    { label: 'Contact', href: '/contact/' },
  ],
  navServices: [
    { label: 'Buying property', href: '/buying-property/' },
    { label: 'Selling property', href: '/selling-property/' },
    { label: 'Residency & visas', href: '/residency-and-visas/' },
    { label: 'Tax & accountancy', href: '/tax-and-accountancy/' },
    { label: 'Property management', href: '/property-management-services/' },
    { label: 'Gibraltar & Spain', href: '/gibraltar-and-spain/' },
    { label: 'Property law', href: '/property-law/' },
    { label: 'The Golden Visa', href: '/spanish-golden-visa/' },
  ],
  navFirm: [
    { label: 'About Esther', href: '/about/' },
    { label: 'Full client service', href: '/full-client-service/' },
    { label: 'Immigration procedures', href: '/immigration-and-foreigners-legal-procedures/' },
    { label: 'Insights', href: '/blog/' },
    { label: 'Contact', href: '/contact/' },
  ],
  navLabels: { services: 'Services', firm: 'Firm' },
  cta: { primary: 'Get in touch', call: 'Call the office', consult: 'Write to Esther' },
  hero: {
    eyebrow: 'Abogada \u00b7 Sotogrande, C\u00e1diz',
    h1: 'Property lawyers in Sotogrande and the Costa del Sol',
    sub: 'Independent legal advice for buying, selling and owning property in Spain.',
    lede: 'An English-speaking Spanish lawyer specialising in property law for foreigners investing in, and relocating to, Spain. Qualified in Barcelona in 1983, based in Sotogrande since 1990.',
    strap: '\u201cMaking the client feel safe at home.\u201d',
    secondary: 'How we work with you',
    reviews: '53 Google reviews',
  },
  trust: [
    { v: 'Since 1983', k: 'Qualified in Barcelona' },
    { v: 'Sotogrande', k: 'Based here since 1990' },
    { v: '3 jurisdictions', k: 'UK, Gibraltar & Spain' },
    { v: 'EN / ES', k: 'Fluent in both languages' },
  ],
  intro: {
    eyebrow: 'How we work',
    h2: 'We take you by the hand through the whole process',
    p1: 'Buying or owning property in another country involves people, offices and paperwork you have not met before. My team and I handle all of it, from the first enquiry through to completion and for as long afterwards as you need us.',
    p2: 'We can begin before you even step onto Spanish soil, and we stay with you afterwards for the tax returns, the residency paperwork and everything else that comes with owning something here.',
    cta: 'Tell us what you are planning',
  },
  services: {
    eyebrow: 'Services',
    h2: 'What I handle',
    sub: 'Most clients arrive for a purchase and stay for everything that follows: the tax returns, the residency paperwork, the sale years later.',
    more: 'Read more',
    items: [
      { slug: 'buying-property', img: 'villa-pool-costa-del-sol', tag: 'Most requested', title: 'Buying property',
        text: 'Full conveyancing from NIE to keys. Registry checks, contract review, tax calculation and completion before the notary.' },
      { slug: 'residency-and-visas', img: 'spanish-visa-application', tag: 'Updated 2026', title: 'Residency & visas',
        text: 'The Golden Visa closed in April 2025. The non lucrative, digital nomad and family routes remain open, and I file them.' },
      { slug: 'tax-and-accountancy', img: 'coastal-property-costa-del-sol', title: 'Tax & fiscal',
        text: 'Tax returns for non residents, ITP and plusval\u00eda on purchase, plus the annual obligations of owning Spanish property.' },
      { slug: 'selling-property', img: 'property-keys-handover-spain', title: 'Selling property',
        text: 'Capital gains, the 3% retention applied to non residents, and getting your proceeds out of Spain cleanly.' },
      { slug: 'property-management-services', img: 'yachts-puerto-sotogrande', title: 'Property management',
        text: 'Utilities, community fees, insurance and keyholding for owners who are not here all year.' },
      { slug: 'gibraltar-and-spain', img: 'rock-of-gibraltar-from-spain', tag: 'Two jurisdictions', title: 'Gibraltar & Spain',
        text: 'Frontier workers, Gibraltar companies holding Spanish property, and residents moving between the two jurisdictions.' },
    ],
  },
  checks: {
    eyebrow: 'Due diligence',
    h2: 'How we guide you through a purchase',
    sub: 'These are the steps we take care of on your behalf, so that by the time you commit you know exactly what you are buying.',
    items: [
      { icon: 'doc', title: 'Nota simple', text: 'Who actually owns the property, and exactly what is registered against it at the Land Registry.' },
      { icon: 'coin', title: 'Debts & charges', text: 'Any mortgage, community fee, IBI or other charge registered against the property, so that everything is clear at completion.' },
      { icon: 'plan', title: 'Licences & planning', text: 'That the build is licensed and declared, and that the registry, the catastro and what you have seen all agree.' },
      { icon: 'sign', title: 'Contrato de arras', text: 'We read the reservation contract before you sign it, and discuss any amendment worth making.' },
      { icon: 'calc', title: 'Your real costs', text: 'The taxes and official fees for your particular purchase, set out in advance so the figures are known.' },
      { icon: 'home', title: 'Utilities & community', text: 'Supply contracts, meter readings and community status confirmed and transferred at completion.' },
    ],
  },
  reviews: {
    eyebrow: 'Client reviews',
    h2: 'What clients say',
    sub: 'Every review below was left publicly on Google. Not one is under five stars.',
    average: 'Average from 53 Google reviews',
    verified: 'Verified on Google',
    swipe: 'Swipe for more reviews',
    bandTitle: 'Was I your lawyer?',
    bandText: 'A review takes a minute and it genuinely helps other buyers find independent advice.',
    leave: 'Leave a review',
    readAll: 'Read all 53 reviews',
    items: [
      { initial: 'J', name: 'J., United Kingdom', matter: 'Property purchase',
        text: 'I am so incredibly grateful we found Esther. She was wonderful to work with from beginning to end, and helped us understand the purchasing process at every stage.' },
      { initial: 'S', name: 'S., United Kingdom', matter: 'Property purchase',
        text: 'She helped us understand the purchasing process and stepped in to avoid us making costly mistakes on a property that was fraught with issues.' },
      { initial: 'M', name: 'Mark, United Kingdom', matter: 'Property purchase',
        text: 'Speaking no Spanish, it was essential that I fully understood the process of purchasing a property in Spain. Esther explained exactly what was going on every step of the way.' },
      { initial: 'R', name: 'R. and family', matter: 'Purchase, utilities, residency',
        text: 'Over eight months she guided us through the purchase, the set up of all utilities, local authority documentation and our visas. What could have been daunting and confusing was made simple.' },
    ],
  },
  about: {
    eyebrow: 'About',
    h2: 'Esther Pujol Wilkie',
    role: 'Founding partner \u00b7 Abogada',
    p1: 'I was born in Barcelona and studied law there, and I have practised in the United Kingdom, Gibraltar and Spain. For the last thirty years or so I have worked from Sotogrande, almost entirely with foreign clients meeting Spanish law for the first time.',
    p2: 'That means property, but it also means the tax office, the town hall, the immigration office and everything else that comes with owning something here. My clients tend to arrive nervous and stay for decades.',
    creds: [
      ['Qualified', 'Law degree, Barcelona'],
      ['Jurisdictions', 'Spain, Gibraltar and the United Kingdom'],
      ['Languages', 'Spanish and English'],
      ['Colegio', 'ICA Cádiz, nº 1432'],
      ['Practising since', '2 July 1990'],
      ['Recent training', 'Competencias Digitales Profesionales, CGAE, 150h, 2026'],
    ],
    credPending: null,
    chips: [
      { icon: 'shield', text: 'Colegiada nº 1432, ICA Cádiz, desde 1990' },
      { icon: 'list', text: 'Agencia Tributaria filings' },
      { icon: 'globe', text: 'Cross border Gibraltar work' },
    ],
  },
  faq: {
    eyebrow: 'Common questions',
    h2: 'What buyers usually ask first',
    items: [
      { q: 'Can I still get residency by buying a property?',
        a: 'No. Spain\u2019s Golden Visa was repealed by Organic Law 1/2025 and stopped accepting new applications on 3 April 2025. You can still buy freely as a foreigner, but the purchase no longer grants a residence permit. If residency is your goal, the non lucrative visa, digital nomad visa and family routes all remain open, and I can advise on which one fits your circumstances.' },
      { q: 'What is an NIE and when do I need one?',
        a: 'The NIE (N\u00famero de Identificaci\u00f3n de Extranjero) is your Spanish tax identification number. You need one to buy property, open a bank account or pay tax here. I can obtain it on your behalf, and it is usually the first thing we start.' },
      { q: 'Can you act for me if I am not in Spain?',
        a: 'Yes. With a power of attorney I can complete the entire purchase on your behalf, including signing at the notary. Many clients complete without travelling.' },
      { q: 'What will the purchase actually cost me beyond the price?',
        a: 'There are taxes and official fees on any Spanish purchase, and they vary with the property and how it is bought. We set out the figures for your particular purchase at the outset, so nothing arrives unexpectedly.' },
      { q: 'Do you speak English?',
        a: 'Yes, English and Spanish both fluently. Most of my clients speak no Spanish at all. Everything is explained in plain English, including every document you will be asked to sign.' },
    ],
  },
  blogBase: '/blog',
  insights: {
    eyebrow: 'Insights',
    h2: 'Notes on Spanish property law',
    items: [
      { slug: 'spain-golden-visa-guide', metaDesc: "Spain's Golden Visa was repealed on 3 April 2025. What changed, what happens to existing holders, which routes remain open, and the tax consequence they trigger.", sections: [{"h2": "What actually changed", "p": ["Organic Law 1/2025 was published in the Boletín Oficial del Estado on 3 January 2025 and took effect on 3 April 2025. It suppressed Articles 63 to 67 of Law 14/2013, which had provided the legal basis for the residence visa for investors since 2013.", "There is no replacement scheme and no grace period. Property purchase, at any value, no longer produces any residence right in Spain."]}, {"h2": "Why it went", "p": ["The stated reason was housing affordability. The government argued that residency tied to property investment was contributing to price pressure in Madrid, Barcelona, Valencia and the Balearics. Whether the scheme was genuinely a significant driver of those prices is arguable, but politically the property route had become untenable."]}, {"h2": "If you already hold one", "p": ["Transitional provisions protect existing holders. If your authorisation was granted, or your application filed, before the cut off, your status continues and renewal remains available provided the original conditions still hold, including retention of the qualifying investment.", "Renewals due in 2026 and 2027 deserve individual review. The transitional rules interact with the general immigration regime in ways the statutory text does not make obvious."]}, {"h2": "What people ask instead", "p": ["The common question now is which route replaces it, and the honest answer is that none of them does. The Golden Visa was unusual in requiring almost no physical presence. Every remaining route expects you to actually live here for a meaningful part of the year.", "The non-lucrative visa suits those with sufficient passive income who will not work in Spain. The digital nomad visa suits remote workers paid from outside Spain. There are also entrepreneur, highly qualified employment and family routes. The right one depends on how you earn rather than what you own."]}, {"h2": "The tax consequence", "p": ["Any route involving more than 183 days a year in Spain will generally make you tax resident here on worldwide income. That should be modelled before an application is submitted. It is the single most expensive thing to discover after the fact."]}],  cat: 'Residency', title: 'The Golden Visa has ended. What replaced it?',
        text: 'What changed in April 2025, what happens to existing holders, and which routes still work in 2026.' },
      { slug: 'contrato-de-arras', metaDesc: "The Spanish reservation contract is where buyers most often lose their deposit. The three types of arras, the two clauses worth arguing over, and what to check first.", sections: [{"h2": "Where deposits are lost", "p": ["The contrato de arras is the reservation contract, and it is where most buyers first commit money. It is also, very often, signed before anyone independent has read it.", "Under the standard arras penitenciales the buyer who withdraws forfeits the deposit and the seller who withdraws repays double. That symmetry is what most buyers assume they are getting. It is not always what the document in front of them actually says."]}, {"h2": "Three things worth checking", "p": ["Which type of arras it is. Penitenciales, confirmatorias and penales have materially different consequences, and the label is not always used correctly.", "What happens if the buyer's mortgage is refused. Without an express condition, a financing failure is the buyer's problem and the deposit is gone.", "The completion deadline and what follows if the seller cannot meet it, for instance because a charge has not been cleared or paperwork is missing."]}, {"h2": "Before signing anything", "p": ["The nota simple, the debt position and the planning status all belong before the reservation contract, not after it. Once the deposit is paid, the negotiating position has largely gone."]}],  cat: 'Buying', title: 'How buyers lose deposits on the contrato de arras',
        text: 'The reservation contract most buyers sign before taking any advice, and the clauses worth arguing over.' },
      { slug: 'non-resident-tax', metaDesc: "Modelo 210 applies whether or not the property is let. What a non resident owner owes each year, why arrears follow the property, and the deadlines that catch people.", sections: [{"h2": "Modelo 210", "p": ["A non-resident owner files Modelo 210 whether or not the property is let. Where it sits empty, tax is charged on an imputed income derived from the cadastral value. It surprises people that an unused property generates a tax liability at all, but it does, every year."]}, {"h2": "The rest of the annual picture", "p": ["IBI, the municipal property tax, is charged by the town hall and is usually the largest recurring item. Community of owners fees apply where the property forms part of a community. Wealth tax applies where the relevant thresholds are exceeded, and the thresholds vary by autonomous community.", "Where the property is let, the treatment differs between EU and non-EU residents, and since Brexit that distinction has mattered a great deal to British owners."]}, {"h2": "Why arrears matter more than the amounts", "p": ["Individually these are not large sums. The difficulty is that unpaid municipal charges and community fees attach to the property rather than the person, and surface at the point of sale, often years later and always at the worst moment."]}],  cat: 'Tax', title: 'What a non resident owner owes each year',
        text: 'Modelo 210, IBI, community fees and the deadlines that catch owners out.' },
    ],
  },
  contact: {
    eyebrow: 'Get in touch',
    h2: 'Write to Esther',
    sub: 'Tell me a little about what you are planning and I will reply personally, usually within one working day.',
    labels: { office: 'Office', phone: 'Telephone', email: 'Email', hours: 'Hours', languages: 'Languages',
      first: 'First name', surname: 'Surname', email: 'Email', tel: 'Telephone',
      matter: 'How can I help?', area: 'Area', message: 'Your message' },
    placeholder: 'A sentence or two about what you are planning is plenty.',
    consent: 'I have read the privacy policy and consent to being contacted about my enquiry.',
    send: 'Send enquiry',
    sending: 'Sending\u2026',
    ok: 'Thank you. Your enquiry has been sent and I will reply personally, usually within one working day.',
    err: 'That did not send. Please email or call the office directly and I will pick it up.',
    matters: ['Buying a property', 'Selling a property', 'Residency or visa', 'Tax return or fiscal',
      'Property management', 'Gibraltar and Spain matter', 'Something else'],
    areas: ['Sotogrande', 'San Roque', 'Estepona', 'Marbella', 'Casares or Manilva', 'Gibraltar',
      'Elsewhere in Spain', 'Not decided yet'],
  },
  footer: {
    blurb: 'Independent legal advice in English and Spanish for property buyers and owners in Sotogrande and the Campo de Gibraltar.',
    services: 'Services', firm: 'Firm',
    more: 'Practice areas',
    legacyLinks: [
      { label: 'Property law', href: '/property-law/' },
      { label: 'The Golden Visa', href: '/spanish-golden-visa/' },
      { label: 'Immigration procedures', href: '/immigration-and-foreigners-legal-procedures/' },
      { label: 'Full client service', href: '/full-client-service/' },
    ],

    firmLinks: [
      { label: 'About Esther', href: '/about/' },
      { label: 'Client reviews', href: '/#reviews' },
      { label: 'Insights', href: '/blog/' },
      { label: 'Contact', href: '/contact/' },
    ],
    legal: [
      { label: 'Aviso legal', href: '/aviso-legal' },
      { label: 'Pol\u00edtica de privacidad', href: '/politica-de-privacidad' },
      { label: 'Pol\u00edtica de cookies', href: '/politica-de-cookies' },
    ],
    place: 'La Marina de Sotogrande \u00b7 C\u00e1diz \u00b7 Espa\u00f1a',
    poweredBy: 'Powered by',
  },
};
export default en;
