export const es = {
  locale: 'es',
  altHome: '/',
  altLocale: { code: 'en', label: 'English', href: '/' },
  home: '/es',
  meta: {
    title: 'Abogados inmobiliarios en Sotogrande y Costa del Sol',
    description:
      'Abogados inmobiliarios en Sotogrande y la Costa del Sol. Asesoramiento independiente para compradores extranjeros en compraventa, residencia y fiscalidad.',
  },
  topbar: { blurb: 'Asesoramiento legal independiente para compradores en Sotogrande', hours: 'Lunes a viernes, 9:00 a 17:00' },
  nav: [
    { label: 'Comprar', href: '/es/compraventa/' },
    { label: 'Residencia', href: '/es/residencia-y-visados/' },
    { label: 'Fiscalidad', href: '/es/fiscalidad/' },
    { label: 'Sobre Esther', href: '/es/sobre-esther/' },
    { label: 'Artículos', href: '/es/articulos/' },
    { label: 'Contacto', href: '/es/contacto/' },
  ],
  navServices: [
    { label: 'Comprar una propiedad', href: '/es/compraventa/' },
    { label: 'Vender una propiedad', href: '/es/venta-de-propiedades/' },
    { label: 'Residencia y visados', href: '/es/residencia-y-visados/' },
    { label: 'Fiscalidad y contabilidad', href: '/es/fiscalidad/' },
    { label: 'Gestión de propiedades', href: '/es/gestion-de-propiedades/' },
    { label: 'Gibraltar y España', href: '/es/gibraltar-y-espana/' },
    { label: 'Derecho inmobiliario', href: '/es/derecho-inmobiliario/' },
    { label: 'La Golden Visa', href: '/es/golden-visa-espana/' },
  ],
  navFirm: [
    { label: 'Sobre Esther', href: '/es/sobre-esther/' },
    { label: 'Servicio integral', href: '/es/servicio-integral/' },
    { label: 'Extranjería', href: '/es/tramites-de-extranjeria/' },
    { label: 'Artículos', href: '/es/articulos/' },
    { label: 'Contacto', href: '/es/contacto/' },
  ],
  navLabels: { services: 'Servicios', firm: 'Despacho' },
  cta: { primary: 'Contactar', call: 'Llamar al despacho', consult: 'Escribir a Esther' },
  hero: {
    eyebrow: 'Abogada \u00b7 Sotogrande, C\u00e1diz',
    h1: 'Abogados inmobiliarios en Sotogrande y la Costa del Sol',
    sub: 'Asesoramiento legal independiente para comprar, vender y mantener una propiedad en España.',
    lede: 'Abogada española especializada en derecho inmobiliario para extranjeros que invierten en España o se trasladan a vivir aquí. Licenciada en Barcelona en 1983, en Sotogrande desde 1990.',
    strap: '\u00abQue el cliente se sienta como en casa.\u00bb',
    secondary: 'Cómo trabajamos con usted',
    reviews: '53 reseñas en Google',
  },
  trust: [
    { v: 'Desde 1983', k: 'Licenciada en Barcelona' },
    { v: 'Sotogrande', k: 'Desde 1990' },
    { v: '3 jurisdicciones', k: 'Reino Unido, Gibraltar y España' },
    { v: 'ES / EN', k: 'Ambos idiomas con fluidez' },
  ],
  intro: {
    eyebrow: 'Cómo trabajamos',
    h2: 'Le acompañamos de la mano durante todo el proceso',
    p1: 'Comprar o mantener una propiedad en otro país implica trato con personas, oficinas y trámites que no conoce. Mi equipo y yo nos ocupamos de todo, desde la primera consulta hasta la firma y durante todo el tiempo que después nos necesite.',
    p2: 'Podemos empezar antes incluso de que pise suelo español, y seguimos a su lado después para las declaraciones, la residencia y todo lo que conlleva tener algo aquí.',
    cta: 'Cuéntenos qué tiene en mente',
  },
  services: {
    eyebrow: 'Servicios',
    h2: 'En qué le puedo ayudar',
    sub: 'La mayoría de mis clientes llegan por una compra y se quedan para todo lo que viene después: los impuestos, la residencia y la venta años más tarde.',
    more: 'Saber más',
    items: [
      { slug: 'compraventa', img: 'villa-pool-costa-del-sol', tag: 'Más solicitado', title: 'Comprar una propiedad',
        text: 'Todo el proceso, del NIE a las llaves. Nota simple, revisión del contrato, cálculo de impuestos y firma ante notario.' },
      { slug: 'residencia-y-visados', img: 'spanish-visa-application', tag: 'Actualizado 2026', title: 'Residencia y visados',
        text: 'La Golden Visa se cerró en abril de 2025. Siguen abiertas la no lucrativa, la de nómada digital y las vías familiares, y yo las tramito.' },
      { slug: 'fiscalidad', img: 'coastal-property-costa-del-sol', title: 'Fiscal y contable',
        text: 'Declaraciones de no residentes, ITP y plusvalía en la compra, y las obligaciones anuales de tener una propiedad en España.' },
      { slug: 'venta-de-propiedades', img: 'property-keys-handover-spain', title: 'Vender una propiedad',
        text: 'Ganancia patrimonial, la retención del 3% a no residentes y la repatriación del importe sin complicaciones.' },
      { slug: 'gestion-de-propiedades', img: 'yachts-puerto-sotogrande', title: 'Gestión de propiedades',
        text: 'Suministros, cuotas de comunidad, seguros y custodia de llaves para propietarios que no residen aquí todo el año.' },
      { slug: 'gibraltar-y-espana', img: 'rock-of-gibraltar-from-spain', tag: 'Dos jurisdicciones', title: 'Gibraltar y España',
        text: 'Trabajadores transfronterizos, sociedades gibraltareñas con inmuebles en España y residentes entre ambas jurisdicciones.' },
    ],
  },
  checks: {
    eyebrow: 'Due diligence',
    h2: 'Cómo le acompañamos en una compra',
    sub: 'Estos son los pasos de los que nos ocupamos en su nombre, para que cuando se comprometa sepa exactamente qué está comprando.',
    items: [
      { icon: 'doc', title: 'Nota simple', text: 'Quién es el titular real y qué consta inscrito sobre la finca en el Registro de la Propiedad.' },
      { icon: 'coin', title: 'Cargas y deudas', text: 'Cualquier hipoteca, cuota de comunidad, IBI o carga inscrita sobre la finca, para que todo quede limpio en la firma.' },
      { icon: 'plan', title: 'Licencias y urbanismo', text: 'Que la obra cuente con licencia y esté declarada, y que Registro, catastro y lo que usted ha visto coincidan.' },
      { icon: 'sign', title: 'Contrato de arras', text: 'Leemos el contrato de arras antes de que lo firme y comentamos cualquier ajuste que convenga.' },
      { icon: 'calc', title: 'Su coste real', text: 'Los impuestos y aranceles de su operación concreta, detallados de antemano para que las cifras se conozcan.' },
      { icon: 'home', title: 'Suministros y comunidad', text: 'Contratos de suministro, lecturas de contador y estado de la comunidad verificados y traspasados en la firma.' },
    ],
  },
  reviews: {
    eyebrow: 'Reseñas de clientes',
    h2: 'Lo que dicen los clientes',
    sub: 'Todas las reseñas están publicadas en Google. Ninguna baja de cinco estrellas.',
    average: 'Media de 53 reseñas en Google',
    verified: 'Verificado en Google',
    swipe: 'Deslice para ver más reseñas',
    bandTitle: '¿Fui su abogada?',
    bandText: 'Dejar una reseña lleva un minuto y ayuda de verdad a otros compradores a encontrar asesoramiento independiente.',
    leave: 'Dejar una reseña',
    readAll: 'Ver las 53 reseñas',
    items: [
      { initial: 'J', name: 'J., Reino Unido', matter: 'Compra de vivienda',
        text: 'Estoy enormemente agradecida de haber encontrado a Esther. Ha sido un placer trabajar con ella de principio a fin, y nos ayudó a entender el proceso de compra en cada fase.' },
      { initial: 'S', name: 'S., Reino Unido', matter: 'Compra de vivienda',
        text: 'Nos ayudó a entender el proceso de compra e intervino para evitar errores muy costosos en una propiedad llena de problemas.' },
      { initial: 'M', name: 'Mark, Reino Unido', matter: 'Compra de vivienda',
        text: 'Sin hablar español, era esencial entender bien el proceso de compra en España. Esther nos explicó exactamente qué ocurría en cada paso.' },
      { initial: 'R', name: 'R. y familia', matter: 'Compra, suministros, residencia',
        text: 'Durante ocho meses nos guió en la compra, el alta de todos los suministros, la documentación municipal y nuestros visados. Lo que podía ser abrumador resultó sencillo.' },
    ],
  },
  about: {
    eyebrow: 'Sobre Esther',
    h2: 'Esther Pujol Wilkie',
    role: 'Socia fundadora \u00b7 Abogada',
    p1: 'Nací en Barcelona y allí estudié Derecho. He ejercido en el Reino Unido, Gibraltar y España. Desde hace unos treinta años trabajo desde Sotogrande, casi siempre con clientes extranjeros que se enfrentan por primera vez al derecho español.',
    p2: 'Eso significa inmobiliario, pero también Hacienda, el ayuntamiento, extranjería y todo lo demás que conlleva tener algo aquí. Mis clientes suelen llegar nerviosos y quedarse durante décadas.',
    creds: [
      ['Titulación', 'Licenciada en Derecho, Barcelona'],
      ['Jurisdicciones', 'España, Gibraltar y Reino Unido'],
      ['Idiomas', 'Español e inglés'],
      ['Colegio', 'ICA Cádiz, nº 1432'],
      ['Ejerciente desde', '2 de julio de 1990'],
      ['Formación reciente', 'Competencias Digitales Profesionales, CGAE, 150h, 2026'],
    ],
    credPending: null,
    chips: [
      { icon: 'shield', text: 'Colegiada nº 1432, ICA Cádiz' },
      { icon: 'list', text: 'Presentaciones ante la Agencia Tributaria' },
      { icon: 'globe', text: 'Asuntos transfronterizos con Gibraltar' },
    ],
  },
  faq: {
    eyebrow: 'Preguntas frecuentes',
    h2: 'Lo que preguntan primero los compradores',
    items: [
      { q: '¿Puedo obtener la residencia comprando una propiedad?',
        a: 'No. La Golden Visa española quedó derogada por la Ley Orgánica 1/2025 y dejó de admitir solicitudes el 3 de abril de 2025. Un extranjero puede seguir comprando con total libertad, pero la compra ya no otorga permiso de residencia. Si su objetivo es la residencia, siguen abiertas la visa no lucrativa, la de nómada digital y las vías familiares, y puedo asesorarle sobre cuál encaja en su caso.' },
      { q: '¿Qué es el NIE y cuándo lo necesito?',
        a: 'El NIE (Número de Identificación de Extranjero) es su número de identificación fiscal en España. Lo necesita para comprar una propiedad, abrir una cuenta bancaria o pagar impuestos aquí. Puedo obtenerlo en su nombre y suele ser lo primero que tramitamos.' },
      { q: '¿Puede actuar en mi nombre si no estoy en España?',
        a: 'Sí. Con un poder notarial puedo completar toda la compra en su nombre, incluida la firma ante notario. Muchos clientes cierran la operación sin desplazarse.' },
      { q: '¿Cuánto me costará la compra además del precio?',
        a: 'Toda compra en España conlleva impuestos y aranceles oficiales, que varían según el inmueble y la forma de adquirirlo. Le detallamos las cifras de su operación concreta desde el principio, para que nada aparezca por sorpresa.' },
      { q: '¿Habla inglés?',
        a: 'Sí, español e inglés con fluidez. La mayoría de mis clientes no habla español y todo se explica con claridad, incluido cada documento que se le pida firmar.' },
    ],
  },
  blogBase: '/es/articulos',
  insights: {
    eyebrow: 'Artículos',
    h2: 'Apuntes de derecho inmobiliario español',
    items: [
      { slug: "guia-golden-visa-espana", metaDesc: "La Golden Visa española dejó de admitir solicitudes el 3 de abril de 2025. Qué ocurre con los titulares actuales y qué vías de residencia quedan en 2026.", sections: [{"h2": "Qué ha cambiado", "p": ["El Visado de Residencia para Inversores, conocido por todos como Golden Visa, se creó en 2013 para fomentar la inversión en España. Quedó derogado por la Ley Orgánica 1/2025 y dejó de admitir nuevas solicitudes el 3 de abril de 2025.", "Comprar aquí sigue plenamente abierto a los extranjeros. Simplemente ya no lleva aparejado un derecho de residencia."]}, {"h2": "Si ya es titular", "p": ["Las disposiciones transitorias protegen a los titulares actuales. Cuando la autorización se concedió, o la solicitud se presentó, antes de la fecha de corte, la situación continúa y la renovación sigue siendo posible mientras se mantengan las condiciones originales.", "Si está pensando en vender el inmueble en el que se basó el visado, o se acerca a los diez años de residencia legal, conviene hablarlo antes. Suele haber más opciones de las que se piensa."]}, {"h2": "Qué se pregunta ahora", "p": ["La pregunta habitual es qué vía la sustituye, y la respuesta honesta es que ninguna exactamente. La Golden Visa era inusual porque exigía muy poca presencia en España. Todas las vías disponibles hoy esperan que pase aquí una parte significativa del año.", "La no lucrativa encaja con quien dispone de medios suficientes y no va a trabajar en España. La de nómada digital, con quien trabaja en remoto para empresas de fuera. Existen además las de emprendimiento, empleo altamente cualificado y familiares. Cuál conviene depende de cómo genere sus ingresos."]}, {"h2": "Una nota sobre fiscalidad", "p": ["Residencia y residencia fiscal son cosas distintas. Permanecer más de 183 días al año en España le hará, por regla general, residente fiscal aquí por su renta mundial. Como las vías que quedan sí esperan presencia real, esto afecta hoy a muchos más solicitantes que antes, y conviene valorarlo antes de solicitar."]}], cat: "Residencia", title: "La Golden Visa se ha cerrado. ¿Y ahora?",
        text: "La vía de residencia por inversión terminó en abril de 2025. Qué supone para los titulares actuales y qué vías siguen abiertas." },
      { slug: "contrato-de-arras", metaDesc: "El contrato de reserva español explicado: los tres tipos de arras, qué ocurre si se deniega la hipoteca y por qué conviene leerlo antes de firmar.", sections: [{"h2": "Qué hace el contrato", "p": ["El contrato de arras es el contrato de reserva y suele ser el primer documento que firma el comprador y el momento en que se entrega una señal. Fija el precio, las partes y la fecha de la escritura, y retira el inmueble del mercado mientras se prepara la compra.", "Es un documento útil y no tiene nada de extraordinario. Simplemente merece leerse con calma, porque las distintas modalidades de arras tienen consecuencias bastante diferentes."]}, {"h2": "Las tres modalidades", "p": ["Las arras penitenciales son las más habituales. Permiten desistir a cualquiera de las partes: el comprador pierde la señal y el vendedor la devuelve doblada. Las confirmatorias confirman la venta y no contemplan el desistimiento del mismo modo. Las penales fijan una penalización manteniendo la venta exigible.", "El encabezamiento del documento no siempre coincide con las cláusulas que contiene, y por eso leemos el clausulado y no el título."]}, {"h2": "Dos cláusulas que merecen atención", "p": ["La primera es qué ocurre si no se concede la hipoteca. Cuando el contrato no lo prevé expresamente, ese riesgo lo asume el comprador. Es un punto sencillo de acordar desde el principio.", "La segunda es la fecha de firma y qué sucede si el vendedor no llega a tiempo, por ejemplo porque queda una carga por cancelar. Un poco de flexibilidad prevista en este momento evita bastantes dificultades después."]}, {"h2": "Nuestro consejo", "p": ["Déjenos ver el contrato antes de firmarlo. Las comprobaciones, la situación registral y el estado urbanístico corresponden a esta fase y no a la siguiente, y cualquier ajuste que convenga es mucho más fácil de acordar antes de entregar la señal."]}], cat: "Compraventa", title: "Entender el contrato de arras",
        text: "El contrato de reserva es el primer documento que firma casi todo comprador. Una guía breve sobre qué hace y qué conviene mirar." },
      { slug: "impuestos-no-residentes", metaDesc: "Las presentaciones anuales del propietario no residente en España: la declaración que procede aunque el inmueble esté vacío, el IBI, la comunidad y el alquiler.", sections: [{"h2": "La declaración anual", "p": ["El propietario no residente presenta una declaración anual se alquile o no el inmueble. Cuando permanece vacío, el impuesto se calcula sobre el valor catastral y no sobre ingreso alguno.", "A muchos propietarios les sorprende que una vivienda sin uso genere una presentación. La genera, todos los años, y las declaraciones no presentadas se acumulan en silencio hasta que afloran en el momento de la venta."]}, {"h2": "El resto del cuadro", "p": ["El IBI lo gira el ayuntamiento y suele ser la partida recurrente más elevada. Las cuotas de comunidad se devengan cuando el inmueble forma parte de una comunidad de propietarios. Puede haber además tasa de basuras y, por encima de ciertos umbrales, impuesto sobre el patrimonio, que varía según la comunidad autónoma.", "Cuando el inmueble se alquila, la renta se declara trimestralmente y el tratamiento varía según dónde sea usted residente fiscal. Desde el Brexit esto afecta en particular a los propietarios británicos."]}, {"h2": "Por qué conviene tenerlo al día", "p": ["Individualmente son cantidades modestas. La dificultad es que los tributos municipales y las cuotas de comunidad quedan afectos a la finca y no al propietario, de modo que la siguen hasta la venta, a menudo años después.", "Mantenerlo todo al corriente es bastante más sencillo que resolverlo con prisas y un comprador esperando. Es un servicio que prestamos a la mayoría de los clientes cuya propiedad gestionamos."]}], cat: "Fiscal", title: "Qué presenta cada año un propietario no residente",
        text: "Un resumen breve de las obligaciones anuales que conlleva tener una propiedad en España desde el extranjero." },
    ],
  },
  contact: {
    eyebrow: 'Contacto',
    h2: 'Escribir a Esther',
    sub: 'Cuénteme un poco sobre lo que tiene en mente y le responderé personalmente, normalmente en un día laborable.',
    labels: { office: 'Despacho', phone: 'Teléfono', email: 'Correo electrónico', hours: 'Horario', languages: 'Idiomas',
      first: 'Nombre', surname: 'Apellidos', email: 'Correo electrónico', tel: 'Teléfono',
      matter: '¿En qué puedo ayudarle?', area: 'Zona', message: 'Su mensaje' },
    placeholder: 'Con una o dos frases sobre lo que tiene en mente es suficiente.',
    consent: 'He leído la política de privacidad y acepto ser contactado en relación con mi consulta.',
    send: 'Enviar consulta',
    sending: 'Enviando\u2026',
    ok: 'Gracias. Su consulta se ha enviado y le responderé personalmente, normalmente en un día laborable.',
    err: 'No se ha podido enviar. Escriba o llame directamente al despacho y lo atenderé.',
    matters: ['Comprar una propiedad', 'Vender una propiedad', 'Residencia o visado', 'Impuestos o fiscalidad',
      'Gestión de propiedades', 'Asunto Gibraltar y España', 'Otra cuestión'],
    areas: ['Sotogrande', 'San Roque', 'Estepona', 'Marbella', 'Casares o Manilva', 'Gibraltar',
      'Otra zona de España', 'Aún sin decidir'],
  },
  footer: {
    blurb: 'Asesoramiento legal independiente, en español e inglés, para compradores y propietarios en Sotogrande y el Campo de Gibraltar.',
    services: 'Servicios', firm: 'Despacho',
    more: 'Áreas de práctica',
    legacyLinks: [
      { label: 'Derecho inmobiliario', href: '/es/derecho-inmobiliario/' },
      { label: 'Golden Visa', href: '/es/golden-visa-espana/' },
      { label: 'Extranjería', href: '/es/tramites-de-extranjeria/' },
      { label: 'Servicio integral', href: '/es/servicio-integral/' },
    ],

    firmLinks: [
      { label: 'Sobre Esther', href: '/es/sobre-esther/' },
      { label: 'Reseñas', href: '/es/#reviews' },
      { label: 'Artículos', href: '/es/articulos/' },
      { label: 'Contacto', href: '/es/contacto/' },
    ],
    legal: [
      { label: 'Aviso legal', href: '/es/aviso-legal' },
      { label: 'Política de privacidad', href: '/es/politica-de-privacidad' },
      { label: 'Política de cookies', href: '/es/politica-de-cookies' },
    ],
    place: 'La Marina de Sotogrande \u00b7 C\u00e1diz \u00b7 España',
    poweredBy: 'Desarrollado por',
  },
};
export default es;
