export const es = {
  locale: 'es',
  altLocale: { code: 'en', label: 'English', href: '/' },
  home: '/es',
  meta: {
    title: 'Abogada Inmobiliaria en Sotogrande | Esther Pujol Wilkie & Associates',
    description:
      'Abogados inmobiliarios en Sotogrande y la Costa del Sol. Asesoramiento legal independiente para compradores extranjeros: compraventa, residencia y fiscalidad. 5,0 sobre 53 reseñas de Google.',
  },
  topbar: { blurb: 'Asesoramiento legal independiente para compradores en Sotogrande', hours: 'Lunes a viernes, 9:00 a 17:00' },
  nav: [
    { label: 'Servicios', href: '#services' },
    { label: 'Due diligence', href: '#checks', hint: 'Qué reviso' },
    { label: 'Reseñas', href: '#reviews', hint: '5,0 \u2605 \u00b7 53' },
    { label: 'Sobre Esther', href: '#about' },
    { label: 'Preguntas', href: '#faq' },
    { label: 'Contacto', href: '#contact' },
  ],
  cta: { primary: 'Consulta gratuita', call: 'Llamar ahora', consult: 'Solicitar consulta gratuita' },
  hero: {
    eyebrow: 'Abogada \u00b7 Sotogrande, C\u00e1diz',
    h1: 'Abogados inmobiliarios en Sotogrande y la Costa del Sol',
    sub: 'Asesoramiento legal independiente para comprar, vender y mantener una propiedad en España.',
    lede: 'Treinta y cinco años acompañando a compradores extranjeros a través del derecho español, explicado con claridad en cada paso.',
    strap: 'Su abogada. No la de la agencia.',
    secondary: 'Qué reviso antes de que firme',
    reviews: '53 reseñas en Google',
  },
  trust: [
    { v: '35+', k: 'Años en Sotogrande' },
    { v: 'Gratis', k: 'Primera consulta' },
    { v: '3 países', k: 'Reino Unido, Gibraltar y España' },
    { v: 'ES / EN', k: 'Ambos idiomas con fluidez' },
  ],
  intro: {
    eyebrow: 'Por qué importa el asesoramiento independiente',
    h2: 'El notario no le representa. La agencia tampoco.',
    p1: 'En España la función del notario es dar fe de la escritura, no proteger sus intereses. A la agencia inmobiliaria le paga el vendedor al firmar. Si nadie independiente revisa la propiedad, entonces no la revisa nadie.',
    p2: 'Yo trabajo únicamente para usted. La nota simple, las cargas, la situación urbanística y las condiciones del contrato se revisan antes de que se entregue un solo euro de señal, y se renegocian cuando hace falta.',
    cta: 'Hablemos de su compra',
  },
  services: {
    eyebrow: 'Servicios',
    h2: 'En qué le puedo ayudar',
    sub: 'La mayoría de mis clientes llegan por una compra y se quedan para todo lo que viene después: los impuestos, la residencia y la venta años más tarde.',
    more: 'Saber más',
    items: [
      { slug: 'compraventa', img: 'buying', tag: 'Más solicitado', title: 'Comprar una propiedad',
        text: 'Todo el proceso, del NIE a las llaves. Nota simple, revisión del contrato, cálculo de impuestos y firma ante notario.' },
      { slug: 'residencia-y-visados', img: 'residency', tag: 'Actualizado 2026', title: 'Residencia y visados',
        text: 'La Golden Visa se cerró en abril de 2025. Siguen abiertas la no lucrativa, la de nómada digital y las vías familiares, y yo las tramito.' },
      { slug: 'fiscalidad', img: 'tax', title: 'Fiscal y contable',
        text: 'Declaraciones de no residentes, ITP y plusvalía en la compra, y las obligaciones anuales de tener una propiedad en España.' },
      { slug: 'venta-de-propiedades', img: 'selling', title: 'Vender una propiedad',
        text: 'Ganancia patrimonial, la retención del 3% a no residentes y la repatriación del importe sin complicaciones.' },
      { slug: 'gestion-de-propiedades', img: 'management', title: 'Gestión de propiedades',
        text: 'Suministros, cuotas de comunidad, seguros y custodia de llaves para propietarios que no residen aquí todo el año.' },
      { slug: 'gibraltar-y-espana', img: 'gibraltar', tag: 'Dos jurisdicciones', title: 'Gibraltar y España',
        text: 'Trabajadores transfronterizos, sociedades gibraltareñas con inmuebles en España y residentes entre ambas jurisdicciones.' },
    ],
  },
  checks: {
    eyebrow: 'Due diligence',
    h2: 'Qué reviso antes de que firme',
    sub: 'Todo esto ocurre antes de que se mueva ninguna señal. Aquí es donde aparecen los problemas y donde se salvan los depósitos.',
    items: [
      { icon: 'doc', title: 'Nota simple', text: 'Quién es el titular real y qué consta inscrito sobre la finca en el Registro de la Propiedad.' },
      { icon: 'coin', title: 'Cargas y deudas', text: 'Hipotecas, cuotas de comunidad impagadas, IBI atrasado y embargos siguen a la finca, no al vendedor.' },
      { icon: 'plan', title: 'Licencias y urbanismo', text: 'Que la obra sea legal, esté declarada y coincida con el Registro. Ampliaciones y piscinas a menudo no lo están.' },
      { icon: 'sign', title: 'Contrato de arras', text: 'El contrato de reserva es donde más señales se pierden. Se lee y se renegocia antes de firmar.' },
      { icon: 'calc', title: 'Su coste real', text: 'ITP, notaría, registro y honorarios calculados de antemano, para que el día de la firma no haya sorpresas.' },
      { icon: 'home', title: 'Suministros y comunidad', text: 'Contratos de suministro, lecturas de contador y estado de la comunidad verificados y traspasados en la firma.' },
    ],
  },
  reviews: {
    eyebrow: 'Reseñas de clientes',
    h2: 'Lo que dicen los clientes',
    sub: 'Todas las reseñas están publicadas en Google. Ninguna baja de cinco estrellas.',
    average: 'Media de 53 reseñas en Google',
    verified: 'Verificado en Google',
    swipe: 'Deslice para ver más reseñas',
    bandTitle: '¿Fui su abogada?',
    bandText: 'Dejar una reseña lleva un minuto y ayuda de verdad a otros compradores a encontrar asesoramiento independiente.',
    leave: 'Dejar una reseña',
    readAll: 'Ver las 53 reseñas',
    items: [
      { initial: 'J', name: 'J., Reino Unido', matter: 'Compra de vivienda',
        text: 'Nos sentíamos vulnerables y presionados por la agencia para usar el abogado que ellos recomendaban. Nos ahorró tiempo y dinero, y defiende lo nuestro con una firmeza exquisita.' },
      { initial: 'S', name: 'S., Reino Unido', matter: 'Compra de vivienda',
        text: 'Nos ayudó a entender el proceso de compra e intervino para evitar errores muy costosos en una propiedad llena de problemas.' },
      { initial: 'M', name: 'Mark, Reino Unido', matter: 'Compra de vivienda',
        text: 'Sin hablar español, era esencial entender bien el proceso de compra en España. Esther nos explicó exactamente qué ocurría en cada paso.' },
      { initial: 'R', name: 'R. y familia', matter: 'Compra, suministros, residencia',
        text: 'Durante ocho meses nos guió en la compra, el alta de todos los suministros, la documentación municipal y nuestros visados. Lo que podía ser abrumador resultó sencillo.' },
    ],
  },
  about: {
    eyebrow: 'Sobre Esther',
    h2: 'Esther Pujol Wilkie',
    role: 'Socia fundadora \u00b7 Abogada',
    p1: 'Nací en Barcelona y allí estudié Derecho. He ejercido en el Reino Unido, Gibraltar y España. Desde hace unos treinta años trabajo desde Sotogrande, casi siempre con clientes extranjeros que se enfrentan por primera vez al derecho español.',
    p2: 'Eso significa inmobiliario, pero también Hacienda, el ayuntamiento, extranjería y todo lo demás que conlleva tener algo aquí. Mis clientes suelen llegar nerviosos y quedarse durante décadas.',
    creds: [
      ['Titulación', 'Licenciada en Derecho, Barcelona'],
      ['Jurisdicciones', 'España, Gibraltar y Reino Unido'],
      ['Idiomas', 'Español e inglés'],
    ],
    credPending: ['Colegio', 'Colegio y n\u00ba de colegiada por confirmar'],
    chips: [
      { icon: 'shield', text: 'Abogada colegiada, Colegio de Abogados' },
      { icon: 'list', text: 'Presentaciones ante la Agencia Tributaria' },
      { icon: 'globe', text: 'Asuntos transfronterizos con Gibraltar' },
    ],
  },
  faq: {
    eyebrow: 'Preguntas frecuentes',
    h2: 'Lo que preguntan primero los compradores',
    items: [
      { q: '¿Puedo obtener la residencia comprando una propiedad?',
        a: 'No. La Golden Visa española quedó derogada por la Ley Orgánica 1/2025 y dejó de admitir solicitudes el 3 de abril de 2025. Un extranjero puede seguir comprando con total libertad, pero la compra ya no otorga permiso de residencia. Si su objetivo es la residencia, siguen abiertas la visa no lucrativa, la de nómada digital y las vías familiares, y puedo asesorarle sobre cuál encaja en su caso.' },
      { q: '¿Necesito abogada si la agencia ya tiene una?',
        a: 'El abogado de la agencia no es su abogado. A las agencias les paga el vendedor al firmar, de modo que su interés está en cerrar la venta, no en si la finca tiene una ampliación no declarada o cuotas de comunidad impagadas. La representación independiente es la protección más importante que tiene un comprador extranjero.' },
      { q: '¿Qué es el NIE y cuándo lo necesito?',
        a: 'El NIE (Número de Identificación de Extranjero) es su número de identificación fiscal en España. Lo necesita para comprar una propiedad, abrir una cuenta bancaria o pagar impuestos aquí. Puedo obtenerlo en su nombre y suele ser lo primero que tramitamos.' },
      { q: '¿Puede actuar en mi nombre si no estoy en España?',
        a: 'Sí. Con un poder notarial puedo completar toda la compra en su nombre, incluida la firma ante notario. Muchos clientes cierran la operación sin desplazarse.' },
      { q: '¿Cuánto me costará la compra además del precio?',
        a: 'Calcule entre un 10 y un 12% adicional sobre el precio en una segunda transmisión en Andalucía. Incluye el ITP, la notaría, el Registro de la Propiedad y los honorarios legales. Recibirá una cifra desglosada antes de comprometerse, para que nada aparezca tarde.' },
      { q: '¿Habla inglés?',
        a: 'Sí, español e inglés con fluidez. La mayoría de mis clientes no habla español y todo se explica con claridad, incluido cada documento que se le pida firmar.' },
    ],
  },
  insights: {
    eyebrow: 'Artículos',
    h2: 'Apuntes de derecho inmobiliario español',
    items: [
      { slug: 'guia-golden-visa-espana', sections: [{"h2": "Qué cambió exactamente", "p": ["La Ley Orgánica 1/2025 se publicó en el BOE el 3 de enero de 2025 y desplegó efectos el 3 de abril de 2025. Suprimió los artículos 63 a 67 de la Ley 14/2013, que constituían la base legal del visado de residencia para inversores desde 2013.", "No hay régimen sustitutivo ni periodo transitorio para nuevas solicitudes. La compra de un inmueble, sea cual sea su importe, ya no genera derecho de residencia en España."]}, {"h2": "Por qué se suprimió", "p": ["El motivo declarado fue la asequibilidad de la vivienda. El Gobierno sostuvo que vincular la residencia a la inversión inmobiliaria presionaba los precios en Madrid, Barcelona, Valencia y Baleares. Puede discutirse si el programa era realmente un factor relevante en esos precios, pero políticamente la vía inmobiliaria había dejado de ser sostenible."]}, {"h2": "Si ya es titular", "p": ["Las disposiciones transitorias protegen a quienes obtuvieron la autorización, o presentaron la solicitud, antes de la fecha de corte. La renovación sigue siendo posible mientras se mantengan las condiciones originales, incluida la conservación de la inversión que dio derecho al permiso.", "Las renovaciones que venzan en 2026 y 2027 merecen revisión individual. Las reglas transitorias interactúan con el régimen general de extranjería de un modo que el texto legal no hace evidente."]}, {"h2": "Qué preguntan ahora", "p": ["La pregunta habitual es qué vía sustituye a la Golden Visa, y la respuesta honesta es que ninguna lo hace del todo. Aquel visado era inusual porque apenas exigía presencia física en España. Todas las vías que quedan esperan que resida aquí una parte significativa del año.", "La no lucrativa encaja con quien dispone de rentas pasivas suficientes y no va a trabajar en España. La de nómada digital encaja con quien trabaja en remoto para empresas de fuera. Existen además las vías de emprendimiento, de empleo altamente cualificado y las familiares. La adecuada depende de cómo genera sus ingresos, no de lo que posee."]}, {"h2": "La consecuencia fiscal", "p": ["Cualquier vía que implique más de 183 días al año en España le convertirá, con carácter general, en residente fiscal aquí por su renta mundial. Conviene calcularlo antes de presentar la solicitud. Es, con diferencia, lo más caro de descubrir a posteriori."]}],  cat: 'Residencia', title: 'La Golden Visa ha terminado. ¿Qué la sustituye?',
        text: 'Qué cambió en abril de 2025, qué ocurre con los titulares actuales y qué vías siguen funcionando en 2026.' },
      { slug: 'contrato-de-arras', sections: [{"h2": "Dónde se pierden las señales", "p": ["El contrato de arras es el contrato de reserva y es donde la mayoría de los compradores entrega dinero por primera vez. También es, muy a menudo, lo primero que se firma sin que nadie independiente lo haya leído.", "En las arras penitenciales, el comprador que desiste pierde la señal y el vendedor que desiste devuelve el doble. Esa simetría es lo que casi todos dan por supuesto. No siempre es lo que dice el documento que tienen delante."]}, {"h2": "Tres cosas que conviene comprobar", "p": ["De qué tipo de arras se trata. Las penitenciales, las confirmatorias y las penales tienen consecuencias muy distintas, y la denominación no siempre se emplea con rigor.", "Qué ocurre si se deniega la hipoteca del comprador. Sin una condición expresa, la falta de financiación es problema del comprador y la señal se pierde.", "El plazo para elevar a público y qué sucede si el vendedor no puede cumplirlo, por ejemplo porque no ha cancelado una carga o le falta documentación."]}, {"h2": "Antes de firmar nada", "p": ["La nota simple, la situación de cargas y el estado urbanístico corresponden a un momento anterior al contrato de reserva, no posterior. Una vez entregada la señal, la capacidad de negociación prácticamente ha desaparecido."]}],  cat: 'Compraventa', title: 'Cómo se pierden las señales en el contrato de arras',
        text: 'El contrato de reserva que casi todos firman antes de asesorarse, y las cláusulas que conviene discutir.' },
      { slug: 'impuestos-no-residentes', sections: [{"h2": "Modelo 210", "p": ["El propietario no residente presenta el modelo 210 se alquile o no el inmueble. Cuando permanece vacío, se tributa por una renta imputada calculada sobre el valor catastral. Sorprende que un inmueble sin uso genere obligación tributaria, pero la genera, todos los años."]}, {"h2": "El resto del cuadro anual", "p": ["El IBI lo gira el ayuntamiento y suele ser la partida recurrente más elevada. Las cuotas de comunidad se devengan cuando el inmueble forma parte de una comunidad de propietarios. El impuesto sobre el patrimonio se aplica al superarse los umbrales, que varían según la comunidad autónoma.", "Cuando el inmueble se alquila, el tratamiento difiere entre residentes de la UE y de terceros países, distinción que desde el Brexit afecta de lleno a los propietarios británicos."]}, {"h2": "Por qué importan más los atrasos que los importes", "p": ["Individualmente no son cantidades elevadas. La dificultad es que los tributos municipales y las cuotas de comunidad impagadas siguen a la finca y no a la persona, y afloran en el momento de la venta, con frecuencia años después y siempre en el peor momento."]}],  cat: 'Fiscal', title: 'Qué debe cada año un propietario no residente',
        text: 'Modelo 210, IBI, cuotas de comunidad y los plazos que se le escapan a los propietarios.' },
    ],
  },
  contact: {
    eyebrow: 'Contacto',
    h2: 'Primera consulta gratuita',
    sub: 'Cuénteme brevemente qué tiene en mente. Le respondo personalmente, normalmente en un día laborable, con una idea de lo que implica y de lo que costará.',
    labels: { office: 'Despacho', phone: 'Teléfono', hours: 'Horario', languages: 'Idiomas',
      first: 'Nombre', surname: 'Apellidos', email: 'Correo electrónico', tel: 'Teléfono',
      matter: '¿En qué puedo ayudarle?', area: 'Zona', message: 'Su mensaje' },
    placeholder: 'Con una o dos frases sobre lo que tiene en mente es suficiente.',
    consent: 'He leído la política de privacidad y acepto ser contactado en relación con mi consulta.',
    send: 'Enviar consulta',
    sending: 'Enviando\u2026',
    ok: 'Gracias. Su consulta se ha enviado y le responderé personalmente, normalmente en un día laborable.',
    err: 'No se ha podido enviar. Escriba o llame directamente al despacho y lo atenderé.',
    matters: ['Comprar una propiedad', 'Vender una propiedad', 'Residencia o visado', 'Impuestos o fiscalidad',
      'Gestión de propiedades', 'Asunto Gibraltar y España', 'Otra cuestión'],
    areas: ['Sotogrande', 'San Roque', 'Estepona', 'Marbella', 'Casares o Manilva', 'Gibraltar',
      'Otra zona de España', 'Aún sin decidir'],
  },
  footer: {
    blurb: 'Asesoramiento legal independiente, en español e inglés, para compradores y propietarios en Sotogrande y el Campo de Gibraltar.',
    services: 'Servicios', firm: 'Despacho',
    more: 'Áreas de práctica',
    legacyLinks: [
      { label: 'Derecho inmobiliario', href: '/es/derecho-inmobiliario/' },
      { label: 'Golden Visa', href: '/es/golden-visa-espana/' },
      { label: 'Extranjería', href: '/es/tramites-de-extranjeria/' },
      { label: 'Servicio integral', href: '/es/servicio-integral/' },
    ],

    firmLinks: [
      { label: 'Sobre Esther', href: '#about' },
      { label: 'Reseñas', href: '#reviews' },
      { label: 'Artículos', href: '#insights' },
      { label: 'Contacto', href: '#contact' },
    ],
    legal: [
      { label: 'Aviso legal', href: '/es/aviso-legal' },
      { label: 'Política de privacidad', href: '/es/politica-de-privacidad' },
      { label: 'Política de cookies', href: '/es/politica-de-cookies' },
    ],
    place: 'La Marina de Sotogrande \u00b7 C\u00e1diz \u00b7 España',
    poweredBy: 'Desarrollado por',
  },
};
export default es;
