// Page content. `legacy: true` marks URLs inherited from the WordPress site that
// must keep their path. New services sit on new paths alongside them.
const pages = {
  'property-law': {
    legacy: true, image: 'buying', eyebrow: 'Practice area',
    title: 'Property Law in Spain',
    intro: 'The legal framework behind every Spanish property transaction, and what it means for a foreign owner.',
    nav: 'Property law',
    sections: [
      { h2: 'A different system to the one you know',
        p: ['Spanish property law is not a variation on the English or Irish system. Ownership transfers at the notary by public deed, the escritura pública, and only becomes fully effective against third parties once it is inscribed at the Registro de la Propiedad. Until that inscription happens, the position is weaker than most buyers assume.',
            'The practical consequence is that a great deal depends on checks made before signature. Debts, charges and planning irregularities attach to the property itself rather than to the person who created them, so a buyer can inherit problems that had nothing to do with them.'] },
      { h2: 'What attaches to the property, not the seller',
        list: ['Mortgages and any other charge inscribed at the Land Registry',
               'Unpaid community of owners fees, generally for the current year and three preceding years',
               'Outstanding IBI, the annual municipal property tax',
               'Embargoes and pending judicial proceedings',
               'Planning infringements on unlicensed or undeclared building work'] },
      { h2: 'The documents that matter',
        p: ['The nota simple is the Land Registry extract showing the registered owner, the description of the property and any charge against it. It is the starting point of every purchase and it is inexpensive to obtain.',
            'The catastro record is separate and serves a fiscal purpose. The two frequently disagree on surface area or boundaries, and reconciling them before completion avoids difficulty at resale.',
            'For anything built or extended in recent decades, the licencia de primera ocupación and the planning position at the town hall matter as much as the registry entry.'] },
      { h2: 'Where I come in',
        p: ['I act for the buyer or the owner, never for the agent or the developer. That means the searches are run, the contract is read before you are asked to sign it, and the tax position is calculated in advance rather than discovered at the notary.'] },
    ],
    related: [
      { href: '/buying-property/', label: 'Buying a property: the full process' },
      { href: '/selling-property/', label: 'Selling a property in Spain' },
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
    ],
  },

  'spanish-golden-visa': {
    legacy: true, image: 'residency', eyebrow: 'Residency',
    title: 'The Spanish Golden Visa',
    intro: 'The investor residence route closed on 3 April 2025. What that means if you hold one, and what is available if you do not.',
    nav: 'Golden Visa',
    sections: [
      { h2: 'The programme has ended',
        p: ['Spain\u2019s residence visa for investors, universally known as the Golden Visa, was repealed by Organic Law 1/2025. The law was published in the Boletín Oficial del Estado on 3 January 2025 and took effect three months later, on 3 April 2025. It removed Articles 63 to 67 of Law 14/2013, which had been the legal basis for the scheme since 2013.',
            'There is no replacement and no grace period. Buying property in Spain no longer grants any residence right, at any value. Foreign buyers may still purchase freely; the purchase simply carries no immigration consequence.'] },
      { h2: 'If you already hold one',
        p: ['Existing holders are protected by transitional provisions. If your visa or residence authorisation was granted, or your application was filed, before the cut off date, your status continues and renewals remain possible provided you still meet the original conditions, including maintaining the qualifying investment.',
            'Renewals falling due in 2026 and 2027 are worth reviewing individually rather than assumed. The transitional rules interact with the general immigration regime in ways that are not always obvious from the text.'] },
      { h2: 'What is available instead',
        list: ['Non-lucrative visa, for those with sufficient passive income who will not work in Spain',
               'Digital nomad visa, for remote workers employed by or contracting with companies outside Spain',
               'Entrepreneur and self-employment routes, where there is a genuine business project',
               'EU Blue Card, for highly qualified employees with a recognised degree',
               'Family reunification, where a family member already holds Spanish residence'],
        p: ['Each carries different income thresholds, physical presence requirements and tax consequences. The right route depends on how you earn, where you earn it and how much time you intend to spend in Spain.'] },
      { h2: 'The tax point most people miss',
        p: ['Residency and tax residency are separate questions. Spending more than 183 days in Spain in a calendar year generally makes you tax resident here on worldwide income, regardless of which permit you hold. That should be modelled before an application is filed, not after.'] },
    ],
    related: [
      { href: '/residency-and-visas/', label: 'Residency and visa applications' },
      { href: '/immigration-and-foreigners-legal-procedures/', label: 'Immigration and legal procedures' },
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
    ],
  },

  'tax-and-accountancy': {
    legacy: true, image: 'tax', eyebrow: 'Practice area',
    title: 'Tax and Accountancy',
    intro: 'The taxes that arise on purchase, the ones that recur every year, and the returns that have to be filed whether or not you live here.',
    nav: 'Tax and accountancy',
    sections: [
      { h2: 'On purchase',
        p: ['A resale property in Andalucía attracts transfer tax, ITP, currently at 7%. A new build from a developer attracts IVA at 10% plus stamp duty instead. Notary, land registry and legal fees sit on top, and a reasonable overall budget is 10 to 12% above the purchase price.',
            'The valor de referencia introduced in 2022 sets a minimum taxable value for the transaction. Where the agreed price falls below it, tax is assessed on the reference figure, which occasionally produces an unwelcome surprise.'] },
      { h2: 'Every year, as a non-resident owner',
        list: ['Modelo 210, the non-resident income tax return, whether or not the property is let',
               'IBI, the annual municipal property tax',
               'Community of owners fees, where the property forms part of a community',
               'Wealth tax, where the applicable thresholds are exceeded'] },
      { h2: 'On sale',
        p: ['Capital gains tax applies to the difference between acquisition and disposal values, adjusted for allowable costs. Where the seller is not resident in Spain, the buyer is obliged to retain 3% of the price and pay it directly to the tax authority against the seller\u2019s liability. Recovering an excess retention requires a separate filing.'] },
    ],
    related: [
      { href: '/selling-property/', label: 'Selling a property in Spain' },
      { href: '/property-law/', label: 'Property law in Spain' },
    ],
  },

  'immigration-and-foreigners-legal-procedures': {
    legacy: true, image: 'management', eyebrow: 'Practice area',
    title: 'Immigration and Foreigners\u2019 Legal Procedures',
    intro: 'The administrative machinery that comes with living in, or owning something in, Spain as a foreign national.',
    nav: 'Immigration procedures',
    sections: [
      { h2: 'The paperwork behind everyday life',
        p: ['Most of what makes living here difficult is not the law but the administration: appointments that must be booked weeks ahead, documents that must be legalised or apostilled, and offices that will not accept a submission with a single field wrong.',
            'I handle these procedures on behalf of clients, generally under a power of attorney so that attendance in person is not required.'] },
      { h2: 'Procedures handled',
        list: ['NIE, the foreigner identification number required for almost every transaction',
               'Empadronamiento, registration with the town hall where you live',
               'TIE, the physical residence card, and its renewals',
               'Residence certificates for EU nationals',
               'Driving licence exchange and vehicle registration',
               'Legalisation, apostille and sworn translation of foreign documents'] },
      { h2: 'For UK nationals since Brexit',
        p: ['British citizens resident in Spain before 31 December 2020 retain rights under the Withdrawal Agreement, evidenced by the TIE. Those arriving afterwards are treated as third country nationals and need a visa route in the same way as any other non-EU national. The distinction matters a great deal in practice and is worth confirming rather than assuming.'] },
    ],
    related: [
      { href: '/residency-and-visas/', label: 'Residency and visa applications' },
      { href: '/spanish-golden-visa/', label: 'The Spanish Golden Visa' },
    ],
  },

  'property-management-services': {
    legacy: true, image: 'selling', eyebrow: 'Practice area',
    title: 'Property Management Services',
    intro: 'Keeping a Spanish property running properly when you are not here for most of the year.',
    nav: 'Property management',
    sections: [
      { h2: 'What an absent owner needs covered',
        list: ['Utility contracts, transfers, meter readings and direct debits',
               'Community of owners fees, correspondence and representation at meetings',
               'Buildings and contents insurance, placed and renewed',
               'IBI and refuse charges paid on time',
               'Keyholding, access for trades and periodic inspection'] },
      { h2: 'Why it tends to matter',
        p: ['Unpaid community fees and municipal charges do not simply lapse. They accumulate against the property and surface at the point of sale, sometimes years later and usually at the least convenient moment. Keeping them current is considerably cheaper than resolving them under time pressure.'] },
    ],
    related: [
      { href: '/full-client-service/', label: 'Full client service' },
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
    ],
  },

  'full-client-service': {
    legacy: true, image: 'polo', eyebrow: 'How I work',
    title: 'Full Client Service',
    intro: 'Legal, fiscal and administrative matters handled together, by the same office, for as long as you own something here.',
    nav: 'Full client service',
    sections: [
      { h2: 'One office, the whole relationship',
        p: ['Most clients arrive with a single transaction in mind and stay for everything that follows it. The purchase leads to the tax filings, the tax filings lead to the residence application, and years later the same office handles the sale or the inheritance.',
            'Keeping all of it in one place means nothing is assumed to have been done by somebody else, which is where most problems in cross-border matters begin.'] },
      { h2: 'What that covers in practice',
        list: ['Conveyancing on purchase and sale',
               'Annual tax compliance for residents and non-residents',
               'Residence, visa and immigration procedures',
               'Wills, inheritance and succession planning in Spain',
               'Property management and administration',
               'Representation under power of attorney where you are abroad'] },
    ],
    related: [
      { href: '/buying-property/', label: 'Buying a property' },
      { href: '/property-management-services/', label: 'Property management' },
    ],
  },

  // ---- new services, new URLs ----
  'buying-property': {
    image: 'buying', eyebrow: 'Service',
    title: 'Buying a Property in Spain',
    intro: 'Independent conveyancing from the first search to the keys, acting only for the buyer.',
    nav: 'Buying property',
    sections: [
      { h2: 'Before any money moves',
        p: ['The reservation contract, the contrato de arras, is where most buyers are first asked to commit funds, and it is frequently signed before anyone independent has read it. Under the standard arras penitenciales the buyer who withdraws forfeits the deposit and the seller who withdraws repays double, but the drafting varies and not every contract presented is standard.',
            'The registry search, the debt position, the planning status and the tax calculation all belong before signature, not after.'] },
      { h2: 'The sequence',
        list: ['NIE application for each buyer',
               'Nota simple and full due diligence on the property',
               'Review and negotiation of the reservation contract',
               'Spanish bank account and funds transfer planning',
               'Completion before the notary, in person or under power of attorney',
               'Tax payment, registry inscription and transfer of utilities'] },
      { h2: 'If you are not in Spain',
        p: ['A power of attorney, granted before a notary here or before a Spanish consulate or a local notary with apostille, allows the entire purchase to be completed on your behalf. A significant proportion of purchases complete without the buyer travelling.'] },
    ],
    related: [
      { href: '/property-law/', label: 'Property law in Spain' },
      { href: '/tax-and-accountancy/', label: 'Purchase taxes and annual obligations' },
    ],
  },

  'selling-property': {
    image: 'selling', eyebrow: 'Service',
    title: 'Selling a Property in Spain',
    intro: 'Capital gains, the non-resident retention, and getting the proceeds out cleanly.',
    nav: 'Selling property',
    sections: [
      { h2: 'The 3% retention',
        p: ['Where the seller is not tax resident in Spain, the buyer must retain 3% of the price and pay it to the tax authority on account of the seller\u2019s capital gains liability. Where the actual liability is lower, the excess is recoverable, but only by filing within the prescribed period and with the supporting documentation in order.'] },
      { h2: 'Preparing the file early',
        list: ['Nota simple confirming the registered position is clean',
               'Community fee certificate confirming nothing is outstanding',
               'IBI receipts and the energy performance certificate',
               'Licencia de primera ocupación where applicable',
               'Documentary evidence of acquisition cost and allowable expenses'] },
      { h2: 'Plusvalía municipal',
        p: ['The municipal capital gains tax is charged on the increase in the cadastral land value and is normally payable by the seller. Since the 2021 reform two calculation methods exist and the more favourable may be chosen, which is worth doing rather than accepting the first figure produced.'] },
    ],
    related: [
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
      { href: '/property-law/', label: 'Property law in Spain' },
    ],
  },

  'residency-and-visas': {
    image: 'residency', eyebrow: 'Service',
    title: 'Residency and Visa Applications',
    intro: 'The routes that remain open in 2026, and which one fits your circumstances.',
    nav: 'Residency and visas',
    sections: [
      { h2: 'Choosing the route',
        p: ['Since the investor visa closed in April 2025, residence in Spain depends on how you earn rather than what you own. The practical question is whether your income is passive, remote, self-employed or from Spanish employment, and how much of the year you intend to be here.'] },
      { h2: 'The main routes',
        list: ['Non-lucrative visa: sufficient passive income, no work in Spain, substantial physical presence expected',
               'Digital nomad visa: remote work for companies outside Spain, with a minimum income threshold linked to the national minimum wage',
               'Self-employment and entrepreneur routes: a genuine business plan and, in some cases, favourable assessment of the project',
               'EU Blue Card: highly qualified employment with a recognised qualification',
               'Family routes: reunification with a resident family member'] },
      { h2: 'Tax follows residence',
        p: ['Any route that involves spending more than 183 days a year in Spain will generally make you tax resident on worldwide income. Modelling that before applying, rather than after arrival, avoids the most expensive category of mistake.'] },
    ],
    related: [
      { href: '/spanish-golden-visa/', label: 'What happened to the Golden Visa' },
      { href: '/immigration-and-foreigners-legal-procedures/', label: 'Immigration procedures' },
    ],
  },

  'gibraltar-and-spain': {
    image: 'gibraltar', eyebrow: 'Service',
    title: 'Gibraltar and Spain',
    intro: 'Cross-border matters for frontier workers, Gibraltar companies and residents moving between the two jurisdictions.',
    nav: 'Gibraltar and Spain',
    sections: [
      { h2: 'Two systems, one commute',
        p: ['Sotogrande sits twenty minutes from the frontier, and a substantial number of people here live under one system and work or hold assets under the other. Having practised in the United Kingdom, Gibraltar and Spain, I advise on where the two regimes meet rather than on only one side of the line.'] },
      { h2: 'Matters commonly arising',
        list: ['Frontier workers resident in Spain and employed in Gibraltar',
               'Spanish tax residence and reporting for Gibraltar income',
               'Gibraltar companies holding Spanish real estate, and the reporting that follows',
               'Modelo 720 declarations of assets held outside Spain',
               'Relocation in either direction, and the residence position that results'] },
      { h2: 'A note on the current position',
        p: ['The treaty framework governing the relationship between Gibraltar and the EU has been under negotiation for several years and remains subject to change. Anything time sensitive is worth confirming at the point of decision rather than relying on a general description.'] },
    ],
    related: [
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
      { href: '/residency-and-visas/', label: 'Residency and visas' },
    ],
  },
};
export default pages;
