// Las páginas heredadas conservan su ruta original en inglés bajo /es/ con slug propio.
const pages = {
  'sobre-esther': {
    en: 'about', legacy: true, image: 'esther-pujol-wilkie-abogada-sotogrande',
    imageAlt: 'Esther Pujol Wilkie, abogada, en su despacho de Sotogrande',
    portrait: true, imageCaption: 'Esther Pujol Wilkie, abogada \u00b7 Colegiada n\u00ba 1432, ICA C\u00e1diz',
    metaTitle: 'Esther Pujol Wilkie, abogada en Sotogrande',
    metaDesc: 'Abogada española especializada en derecho inmobiliario para extranjeros. Licenciada en Barcelona en 1983, ejerció en Escocia y Gibraltar, en Sotogrande desde 1990.',
    eyebrow: 'Sobre Esther',
    title: 'Esther Pujol Wilkie',
    intro: 'Abogada española especializada en derecho inmobiliario, en particular para extranjeros que invierten en España o se trasladan a vivir aquí.',
    nav: 'Sobre Esther',
    sections: [
      { h2: 'Barcelona, Edimburgo, Gibraltar, Sotogrande',
        p: ['Me licencié en Barcelona en 1983 y me trasladé a Edimburgo, donde ejercí durante cinco años como la única abogada española en Escocia en aquel momento. En esos años trabajé también en la División Internacional del Bank of Scotland y obtuve un Diploma del Scottish Institute of Bankers, además de colaborar con la Law Society of Scotland, el Consulado de España en Edimburgo y diversos grupos jurídicos y de medios británicos.',
            'En 1988 me trasladé a Gibraltar para incorporarme al equipo jurídico español de Hassans, entonces en empresa conjunta con Plazas Abogados. Poco después pasé a su recién abierta oficina de Sotogrande, donde permanecí como socia directora hasta 2010, seguido de una etapa como socia del despacho internacional KONSILIA, especializado en derecho inmobiliario y asesoría fiscal.',
            'En 2012 emprendí en solitario, con la misma ética de trabajo y una visión más definida: seguir ayudando y colaborando con clientes y emprendedores internacionales que desarrollan negocio e inversión en España y fuera de ella.'] },
      { h2: 'Dónde trabajamos',
        p: ['El despacho está en Guadalmarina, en la Avenida de la Marina, en La Marina de Sotogrande. Cubrimos toda la costa andaluza, en especial Marbella y Estepona, y con frecuencia asumimos proyectos en otros puntos de España, incluida Barcelona.',
            'Buena parte del trabajo se realiza a distancia mediante poder notarial, para clientes que no residen en España la mayor parte del año.'] },
      { h2: 'Cómo trabajamos',
        list: ['Honestidad e integridad', 'Confianza', 'Excelencia', 'Creatividad', 'Visión', 'Adaptabilidad'],
        p: ['Nuestra filosofía es sencilla: que el cliente se sienta como en casa.'] },
      { h2: 'Idiomas y titulación',
        list: ['Español e inglés, ambos con fluidez, con todo explicado con claridad',
               'Licenciada en Derecho, Barcelona, 1983',
               'Colegiada n\u00ba 1432, Ilustre Colegio Provincial de Abogados de Cádiz',
               'Diploma del Scottish Institute of Bankers',
               'Ha ejercido en el Reino Unido, Gibraltar y España',
               'Diploma en Competencias Digitales Profesionales, Unión Profesional y CGAE, 2026'] },
    ],
    related: [
      { href: '/es/servicio-integral/', label: 'Todos los servicios' },
      { href: '/es/contacto/', label: 'Contactar' },
    ],
  },
  'contacto': {
    en: 'contact', legacy: true, image: 'polo-sotogrande', imageAlt: 'Partido de polo en Sotogrande',
    metaTitle: 'Contacto | Abogada en Sotogrande, Cádiz',
    metaDesc: 'Escriba a Esther Pujol Wilkie sobre comprar, vender o mantener una propiedad en España. Respuesta personal, normalmente en un día laborable, en español o inglés.',
    eyebrow: 'Contacto',
    title: 'Contacto',
    intro: 'No dude en escribirnos con los datos que encontrará más abajo, o envíe un mensaje mediante el formulario.',
    nav: 'Contacto',
    sections: [
      { h2: 'Escribirnos',
        p: ['Leo y respondo personalmente las consultas, sin derivarlas a nadie, normalmente en un día laborable. Basta con unas líneas sobre lo que tiene en mente.',
            'A partir de ahí podemos hablar con calma, entender qué necesita y explicarle cómo lo abordaríamos.'] },
      { h2: 'Conviene indicar',
        list: ['Si compra, vende o ya es propietario',
               'Dónde está la propiedad o en qué zona busca',
               'Si ya se ha firmado algo',
               'Su nacionalidad y dónde es residente fiscal',
               'Si la residencia en España forma parte del plan'] },
    ],
    related: [
      { href: '/es/sobre-esther/', label: 'Sobre Esther Pujol Wilkie' },
      { href: '/es/servicio-integral/', label: 'Todos los servicios' },
    ],
  },
  'derecho-inmobiliario': {
    en: 'property-law', image: 'scales-of-justice-spanish-law',
    imageAlt: 'La balanza de la justicia, en representación del ejercicio del derecho español',
    metaTitle: 'Derecho inmobiliario en España | Pujol Wilkie',
    metaDesc: 'Derecho inmobiliario español explicado con claridad para propietarios extranjeros. Más de treinta años acompañando a clientes en la costa andaluza.',
    eyebrow: 'Área de práctica',
    title: 'Derecho inmobiliario en España',
    intro: 'Si tiene previsto adquirir una propiedad en España, permítanos ayudarle a hacerlo bien a la primera.',
    nav: 'Derecho inmobiliario',
    sections: [
      { h2: 'Hacerlo bien a la primera',
        p: ['Ya venga por la playa, el golf, el polo, la náutica o por un proyecto empresarial, comprar en España es una experiencia agradable cuando está bien atendida. Con más de treinta años de ejercicio en esta costa hemos acompañado a cientos de clientes en ese camino.',
            'Podemos empezar a ocuparnos de sus necesidades antes incluso de que pise suelo español: desde la obtención del NIE hasta la compra, el alquiler o la venta, y le asesoramos sobre la fiscalidad que conlleva ser propietario aquí.'] },
      { h2: 'Un sistema que conviene entender',
        p: ['El derecho inmobiliario español funciona de forma distinta al sistema británico o irlandés. La propiedad se transmite ante notario mediante escritura pública y después se inscribe en el Registro de la Propiedad, que es lo que la hace plenamente eficaz frente a terceros.',
            'Hay un punto práctico más importante que ningún otro: las cargas y obligaciones quedan afectas a la finca y no a quien las generó. Precisamente por eso merecen atención las comprobaciones que hacemos de antemano.'] },
      { h2: 'De qué nos ocupamos',
        list: ['Compraventas y transmisiones de fincas e inmuebles',
               'Nota simple, cargas y situación registral completa',
               'Situación urbanística y de licencias en el ayuntamiento',
               'Contratos, desde las arras hasta la escritura',
               'Arrendamientos, de larga temporada y turísticos',
               'Herencias, testamentos y sucesiones sobre bienes en España',
               'Urbanismo y, cuando llega a ser necesario, litigio'] },
      { h2: 'Cómo trabajamos con usted',
        p: ['Mi equipo y yo le acompañamos de la mano en cada fase, en español o en inglés, explicándole qué ocurre y por qué. Cuando algo debe resolverse se lo decimos con claridad y le planteamos las opciones, de modo que las decisiones sean suyas y con toda la información delante.'] },
    ],
    faq: [
      { q: '¿Qué es la nota simple?',
        a: 'Es el extracto del Registro que acredita quién es el titular, cómo se describe la finca y qué consta inscrito sobre ella. Cuesta muy poco y es donde empieza correctamente toda compra.' },
      { q: '¿El notario comprueba la finca por mí?',
        a: 'El notario es un funcionario público cuya función es dar fe de la escritura y verificar identidad y capacidad. Comprobar la situación física, urbanística y registral es un trabajo distinto, y es el que nosotros hacemos por usted antes de que se comprometa.' },
      { q: '¿Y si la vivienda tiene una ampliación no declarada?',
        a: 'Es bastante habitual y por lo general tiene solución. Según la antigüedad de la obra y la situación urbanística puede legalizarse, o reflejarse en el precio y en la escritura. Lo importante es detectarlo pronto, que es parte de lo que hacemos.' },
      { q: '¿Debo otorgar testamento en España?',
        a: 'Si tiene un inmueble aquí, siempre lo recomendamos. Facilita mucho las cosas a su familia y es el lugar natural para elegir la ley de su nacionalidad como aplicable a su sucesión, algo que muchos de nuestros clientes prefieren.' },
    ],
    related: [{ href: '/es/compraventa/', label: 'Comprar una propiedad en España' },
              { href: '/es/servicio-integral/', label: 'Todos los servicios' }],
  },
  'golden-visa-espana': {
    en: 'spanish-golden-visa', image: 'spanish-visa-application',
    imageAlt: 'Formulario de solicitud de visado español',
    metaTitle: 'Golden Visa España: derogada en abril de 2025',
    metaDesc: 'La Golden Visa española dejó de admitir solicitudes el 3 de abril de 2025. Qué supone para los titulares actuales y qué vías de residencia siguen abiertas.',
    eyebrow: 'Residencia',
    title: 'La Golden Visa española',
    intro: 'El visado de residencia para inversores dejó de admitir solicitudes el 3 de abril de 2025. Esta es la situación.',
    nav: 'Golden Visa',
    sections: [
      { h2: 'Qué ha cambiado',
        p: ['La Golden Visa, formalmente el Visado de Residencia para Inversores, se creó en 2013 para fomentar la inversión en España. Quedó derogada por la Ley Orgánica 1/2025 y dejó de admitir nuevas solicitudes el 3 de abril de 2025.',
            'Comprar una propiedad en España sigue estando plenamente abierto a los extranjeros. Simplemente ya no lleva aparejado un derecho de residencia, de modo que son dos cuestiones distintas y estaremos encantados de asesorarle sobre ambas.'] },
      { h2: 'Si ya es titular',
        p: ['Los titulares actuales quedan protegidos por las disposiciones transitorias. Si su autorización se concedió, o su solicitud se presentó, antes de la fecha de corte, su situación continúa y la renovación sigue siendo posible mientras se mantengan las condiciones originales.',
            'Si está pensando en vender el inmueble en el que se basó su visado, o se acerca a los diez años de residencia legal, háblenos antes. Suele haber más opciones de las que se piensa y son más fáciles de organizar con antelación.'] },
      { h2: 'Las vías que quedan',
        list: ['Residencia no lucrativa, para quien dispone de medios suficientes y no va a trabajar en España',
               'Visado de nómada digital, para quien trabaja en remoto con empresas de fuera de España',
               'Cuenta propia y emprendimiento, con un proyecto empresarial real',
               'Tarjeta azul UE, para empleo altamente cualificado',
               'Reagrupación familiar con un residente en España',
               'Libre circulación, para nacionales de la UE y del EEE y sus familiares'],
        p: ['Cada vía tiene sus requisitos y sus consecuencias fiscales. Cuál le conviene depende de cómo genera sus ingresos y de cuánto tiempo piensa pasar aquí, y es una conversación que merece la pena tener pronto.'] },
      { h2: 'Una nota sobre fiscalidad',
        p: ['Residencia y residencia fiscal son cuestiones distintas. Permanecer más de 183 días al año en España le hará, por regla general, residente fiscal aquí por su renta mundial, sea cual sea el permiso que tenga. Es mucho más sencillo preverlo que corregirlo después.'] },
    ],
    faq: [
      { q: '¿Puedo solicitar todavía la Golden Visa?',
        a: 'No. Las nuevas solicitudes se cerraron el 3 de abril de 2025 y no hay régimen sustitutivo. Comprar una propiedad sigue plenamente abierto a extranjeros, pero ya no otorga residencia.' },
      { q: 'Ya soy titular. ¿Qué ocurre ahora?',
        a: 'Su situación queda protegida por las disposiciones transitorias y la renovación sigue siendo posible mientras mantenga las condiciones originales. Estaremos encantados de revisar cualquier renovación próxima.' },
      { q: '¿Puedo vender el inmueble en el que se basó mi visado?',
        a: 'Puede, pero afectará por lo general a la base de la renovación, de modo que conviene planificar la venta y la residencia a la vez. Háblenos antes de comprometerse a nada.' },
      { q: '¿Qué la ha sustituido?',
        a: 'Nada exactamente equivalente. Siguen abiertas la no lucrativa, la de nómada digital, las de emprendimiento y las familiares, aunque todas esperan que pase en España una parte significativa del año.' },
    ],
    related: [{ href: '/es/residencia-y-visados/', label: 'Residencia y visados' },
              { href: '/es/tramites-de-extranjeria/', label: 'Trámites de extranjería' }],
  },
  'fiscalidad': {
    en: 'tax-and-accountancy', image: 'coastal-property-costa-del-sol',
    imageAlt: 'Inmuebles y puerto deportivo en la Costa del Sol',
    metaTitle: 'Fiscalidad inmobiliaria para no residentes | Pujol Wilkie',
    metaDesc: 'Fiscalidad y contabilidad para propietarios en España, residentes y no residentes. Preparamos y presentamos sus declaraciones y le mantenemos al día.',
    eyebrow: 'Área de práctica', title: 'Fiscalidad y contabilidad',
    intro: 'Como propietario o residente en España siempre hay ciertas obligaciones fiscales. Nos ocupamos de ellas por usted.',
    nav: 'Fiscalidad',
    sections: [
      { h2: 'Tener a alguien que se ocupe',
        p: ['Es fundamental contar con profesionales que le asesoren y se aseguren de que las declaraciones anuales o trimestrales se presentan en su nombre, en plazo y correctamente.',
            'Prestamos estos servicios a particulares, residentes y no residentes, tanto si el inmueble se posee a título privado como si forma parte de una estructura societaria o de una empresa con actividad regular.'] },
      { h2: 'De qué nos ocupamos',
        list: ['Declaraciones anuales y trimestrales, preparadas y presentadas en plazo',
               'La declaración de no residentes, que procede se alquile o no el inmueble',
               'Tributos locales como el IBI y las tasas municipales asociadas',
               'La fiscalidad de la compra y la situación ante una futura venta',
               'Cuentas y presentaciones societarias cuando existe estructura',
               'Declaración de bienes situados en el extranjero, cuando le corresponda'] },
      { h2: 'Mantenerle al día',
        p: ['La fiscalidad española cambia más a menudo de lo que se espera, y los tipos y umbrales varían entre comunidades. Informamos a nuestros clientes de todo lo relevante para que puedan cumplir en todo momento, y calculamos las cifras de su caso concreto en lugar de aplicar una regla general.'] },
    ],
    faq: [
      { q: '¿Debo presentar algo si mi vivienda está vacía?',
        a: 'Sí. El propietario no residente presenta declaración anual se alquile o no el inmueble, calculada sobre el valor catastral. Lo gestionamos de forma habitual para los clientes de los que nos ocupamos.' },
      { q: '¿Y las rentas del alquiler?',
        a: 'Se declaran trimestralmente y el tratamiento varía según dónde sea usted residente fiscal. Desde el Brexit esa distinción afecta en particular a los propietarios británicos, por lo que conviene revisarlo.' },
      { q: '¿Qué impuestos surgen al vender?',
        a: 'Existe un impuesto sobre la ganancia y, cuando el vendedor no reside en España, el comprador retiene un porcentaje del precio a cuenta. Si la retención supera lo realmente debido, el exceso se recupera, y de esa presentación nos ocupamos nosotros.' },
      { q: '¿Debo declarar bienes que tengo fuera de España?',
        a: 'Si es residente fiscal en España y sus bienes en el extranjero superan los umbrales, sí. Es sencillo una vez bien planteado y le diremos si le corresponde.' },
    ],
    related: [{ href: '/es/venta-de-propiedades/', label: 'Vender una propiedad' },
              { href: '/es/gestion-de-propiedades/', label: 'Gestión de propiedades' }],
  },
  'tramites-de-extranjeria': {
    en: 'immigration-and-foreigners-legal-procedures', image: 'yachts-puerto-sotogrande',
    imageAlt: 'Embarcaciones amarradas en el Puerto de Sotogrande',
    metaTitle: 'Trámites de extranjería en España | Pujol Wilkie',
    metaDesc: 'NIE, residencia, TIE, nacionalidad y canje de permiso de conducir tramitados en su nombre, con más de treinta años de experiencia en extranjería.',
    eyebrow: 'Área de práctica', title: 'Extranjería y trámites administrativos',
    intro: 'Gestionar sus asuntos en España requiere un asesor con conocimiento profundo, cuidado y diligencia.',
    nav: 'Extranjería',
    sections: [
      { h2: 'Un terreno que conocemos bien',
        p: ['Es un ámbito en el que contamos con más de treinta años de experiencia y en el que nos hemos ganado una reputación de asesoramiento fiable. Nos ocupamos de los trámites administrativos y legales en su nombre, normalmente mediante poder notarial, de modo que no tenga que acudir en persona.'] },
      { h2: 'Trámites que gestionamos',
        list: ['NIE, número de identificación de extranjero',
               'Autorizaciones de residencia, con o sin actividad, incluidas las de trabajo, reagrupación familiar y estudios',
               'TIE, tarjeta de residencia, y sus renovaciones',
               'Certificados de residencia para ciudadanos de la UE',
               'Solicitudes de nacionalidad',
               'Canje de permiso de conducir',
               'Empadronamiento y alta en el ayuntamiento',
               'Legalización, apostilla y traducción jurada de documentos extranjeros'] },
      { h2: 'Ciudadanos británicos tras el Brexit',
        p: ['Quienes residían legalmente en España antes del 31 de diciembre de 2020 conservan sus derechos bajo el Acuerdo de Retirada, acreditados con el TIE. Quienes llegaron después siguen las mismas vías que cualquier otro extranjero no comunitario.',
            'La distinción importa bastante en la práctica, sobre todo para quienes pasaron temporadas aquí antes de 2021 sin registrarse, y estaremos encantados de decirle cuál es su situación.'] },
      { h2: 'Un servicio a medida',
        p: ['Cada caso es algo distinto. Escríbanos describiendo el suyo y le asesoraremos sobre qué hace falta y cómo lo abordaríamos.'] },
    ],
    faq: [
      { q: '¿Qué es el NIE y cuándo lo necesito?',
        a: 'Es su número de identificación a efectos fiscales en España, necesario para comprar, abrir cuenta bancaria o tributar aquí. Lo obtenemos en su nombre y suele ser lo primero que tramitamos.' },
      { q: '¿Tengo que acudir yo a las citas?',
        a: 'Normalmente no. Con un poder notarial podemos acudir en su nombre en la mayoría de los trámites, que es como lo prefieren buena parte de nuestros clientes.' },
      { q: '¿Cuánto tardan estos trámites?',
        a: 'Depende del trámite y de la oficina. Reunir la documentación suele ser lo más largo, porque los documentos extranjeros requieren apostilla y traducción jurada y tienen su propia validez, así que empezar pronto marca la diferencia.' },
    ],
    related: [{ href: '/es/residencia-y-visados/', label: 'Residencia y visados' },
              { href: '/es/servicio-integral/', label: 'Todos los servicios' }],
  },
  'gestion-de-propiedades': {
    en: 'property-management-services', image: 'yachts-puerto-sotogrande',
    imageAlt: 'Embarcaciones amarradas en el Puerto de Sotogrande',
    metaTitle: 'Gestión de propiedades en Sotogrande | Pujol Wilkie',
    metaDesc: 'Gestión y conserjería para propietarios que no residen todo el año en España: supervisión, suministros, tributos locales, mantenimiento y jardines.',
    eyebrow: 'Área de práctica', title: 'Gestión de propiedades',
    intro: 'Tranquilidad mientras usted está fuera, a través de nuestro departamento de gestión y conserjería.',
    nav: 'Gestión de propiedades',
    sections: [
      { h2: 'Cuidar su propiedad mientras usted no está',
        p: ['Muchos propietarios no pueden viajar a España siempre que querrían y, comprensiblemente, les preocupan la seguridad, el mantenimiento y las reparaciones. Nuestro departamento de gestión y conserjería existe precisamente para eso.'] },
      { h2: 'Este servicio puede incluir',
        list: ['Supervisión del inmueble: revisión e informe de electricidad, agua, correo y seguridad',
               'Gestión de facturas de suministros',
               'Pago de tributos locales como el IBI',
               'Limpieza y lavandería',
               'Jardinería y paisajismo',
               'Mantenimiento de piscina',
               'Pintura, reparaciones y reformas en general',
               'Mantenimiento, reparación e inspección de vehículos'] },
      { h2: 'Cómo organizarlo',
        p: ['Cada propiedad es distinta, igual que la atención que necesita. Escríbanos describiendo el inmueble y con qué frecuencia viene, y le prepararemos una propuesta.'] },
    ],
    related: [{ href: '/es/servicio-integral/', label: 'Servicio integral al cliente' },
              { href: '/es/contacto/', label: 'Contactar' }],
  },
  'servicio-integral': {
    en: 'full-client-service', image: 'polo-sotogrande', imageAlt: 'Partido de polo en Sotogrande',
    metaTitle: 'Servicio integral al cliente | Abogada en Sotogrande',
    metaDesc: 'Un servicio completo en derecho inmobiliario, fiscal, sucesorio, familiar, societario y urbanístico desde un mismo despacho, en español e inglés.',
    eyebrow: 'Cómo trabajamos', title: 'Servicio integral al cliente',
    intro: 'Un servicio verdaderamente completo, atendiendo cualquier área del derecho que nuestros clientes puedan necesitar.',
    nav: 'Servicio integral',
    sections: [
      { h2: 'Un despacho, toda la relación',
        p: ['La mayoría de los clientes llega por un asunto concreto y se queda para todo lo que viene después. Una compra lleva a las declaraciones, las declaraciones a la residencia y, años más tarde, el mismo despacho gestiona la venta o la herencia.',
            'Mantenerlo todo en un mismo sitio evita que nada se dé por supuesto, y quien le asesora más adelante ya conoce el historial.'] },
      { h2: 'Áreas que atendemos habitualmente',
        list: ['Derecho inmobiliario', 'Gestión de propiedades', 'Herencias y testamentos',
               'Fiscalidad y contabilidad', 'Procedimientos de inversión', 'Derecho de familia',
               'Derecho societario', 'Litigios y resolución de conflictos', 'Derecho urbanístico',
               'Extranjería: residencias, canje de permiso de conducir, TIE, NIE'] },
      { h2: 'Trabajar con clientes que no están aquí',
        p: ['Un poder notarial nos permite atender la mayoría de los asuntos sin su presencia: firmar, presentar declaraciones, acudir a citas y tratar con suministradoras y bancos. Conviene otorgarlo aprovechando un viaje y no cuando ya resulta urgente.'] },
    ],
    related: [{ href: '/es/sobre-esther/', label: 'Sobre Esther Pujol Wilkie' },
              { href: '/es/contacto/', label: 'Contactar' }],
  },
  'compraventa': {
    en: 'buying-property', image: 'villa-pool-costa-del-sol',
    imageAlt: 'Villa con piscina en la Costa del Sol, típica de las compraventas en Sotogrande',
    metaTitle: 'Comprar una propiedad en España | Abogada Sotogrande',
    metaDesc: 'Acompañamos al comprador extranjero en todo el proceso, del NIE a las llaves: comprobaciones, contratos, impuestos y firma ante notario.',
    eyebrow: 'Servicio', title: 'Comprar una propiedad en España',
    intro: 'Le llevamos de la mano durante todo el proceso, desde la primera consulta hasta las llaves.',
    nav: 'Comprar una propiedad',
    sections: [
      { h2: 'Podemos empezar antes de que llegue',
        p: ['Buena parte de una compra en España puede prepararse antes de que ponga un pie aquí. Obtenemos su NIE, allanamos el camino para la cuenta bancaria y comenzamos las comprobaciones de cualquier inmueble que esté considerando en serio, de modo que cuando decida ya sepa exactamente qué compra.',
            'Si no puede viajar para la firma, un poder notarial nos permite completarla en su nombre, incluida la escritura ante notario. Muchas de nuestras compras se cierran sin que el comprador tenga que estar en España.'] },
      { h2: 'Qué comprobamos',
        list: ['La nota simple: titularidad, descripción y cargas inscritas',
               'Hipotecas, cuotas de comunidad, IBI y cualquier otra deuda, que siguen a la finca y no al vendedor',
               'La situación urbanística en el ayuntamiento, incluidas ampliaciones, piscinas o terrazas',
               'Licencia de primera ocupación cuando el inmueble es relativamente reciente',
               'La correspondencia entre Registro y catastro en superficie y linderos',
               'El contrato de arras, antes de que se le pida firmarlo',
               'La situación fiscal, para que las cifras se conozcan de antemano'] },
      { h2: 'El contrato de arras',
        p: ['El contrato de arras suele ser el primer documento que se pide firmar y el momento en que se entrega una señal. Hay más de un tipo y las diferencias importan, sobre todo en cuanto a qué ocurre si no se concede la hipoteca o si la firma se retrasa.',
            'Lo leemos y, cuando procede, planteamos modificaciones antes de la firma. Es una conversación sencilla de tener pronto y bastante más difícil después.'] },
      { h2: 'La firma y lo que viene después',
        p: ['La firma se realiza ante notario, donde el pago, el otorgamiento y la entrega de llaves ocurren juntos. Inmediatamente después liquidamos los impuestos y presentamos la escritura a inscripción en el Registro.',
            'A partir de ahí traspasamos los suministros, comunicamos a la comunidad y dejamos en marcha las declaraciones anuales. La mayoría de los clientes se quedan con nosotros para esa parte.'] },
    ],
    faq: [
      { q: '¿Cuánto suele tardar?',
        a: 'Una segunda transmisión sencilla suele completarse en seis a diez semanas desde las arras hasta la firma. Lo que más alarga el proceso es la espera de cita para el NIE o la tasación de la hipoteca, o resolver algo que aparezca en las comprobaciones.' },
      { q: '¿Tengo que estar en España para comprar?',
        a: 'No. Con un poder notarial podemos completar toda la compra en su nombre, incluida la firma ante notario. Puede otorgarse ante notario español, en un consulado o ante notario local con apostilla y traducción jurada.' },
      { q: '¿Qué es el NIE y cuándo lo necesito?',
        a: 'Es su número de identificación a efectos fiscales en España. Lo necesita para comprar, abrir cuenta o tributar aquí, y suele ser lo primero que tramitamos.' },
      { q: '¿Puedo comprar si no soy ciudadano de la UE?',
        a: 'Sí. No hay restricción para que un extranjero compre en España. Desde abril de 2025 la compra ya no lleva aparejada residencia, de modo que son cuestiones distintas y le asesoramos sobre ambas.' },
      { q: '¿Con qué más debo contar además del precio?',
        a: 'Toda compra conlleva impuestos y aranceles oficiales, que varían según el inmueble y la forma de adquirirlo. Le detallamos las cifras de su operación desde el principio, para que nada aparezca por sorpresa.' },
    ],
    related: [{ href: '/es/derecho-inmobiliario/', label: 'Derecho inmobiliario en España' },
              { href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' },
              { href: '/es/contacto/', label: 'Contactar' }],
  },
  'venta-de-propiedades': {
    en: 'selling-property', image: 'property-keys-handover-spain',
    imageAlt: 'Entrega de llaves en la firma de una compraventa en España',
    metaTitle: 'Vender una propiedad en España | Abogada Sotogrande',
    metaDesc: 'Nos ocupamos de la venta de su inmueble de principio a fin, incluida la retención a no residentes y la devolución del exceso.',
    eyebrow: 'Servicio', title: 'Vender una propiedad en España',
    intro: 'Nos ocupamos de la venta de principio a fin, incluido todo lo que viene después.',
    nav: 'Vender una propiedad',
    sections: [
      { h2: 'Preparar el expediente',
        p: ['Una venta va mucho mejor cuando la documentación está lista antes de que aparezca un comprador. Reunimos lo necesario y resolvemos lo que esté pendiente, de modo que cuando llegue una oferta pueda usted avanzar.'] },
      { h2: 'Qué dejamos en orden',
        list: ['La nota simple, confirmando que la situación registral coincide con lo que se vende',
               'Certificado de la comunidad acreditando que no hay deudas',
               'Recibos de IBI y certificado de eficiencia energética',
               'Licencia de primera ocupación cuando proceda',
               'Justificación de lo que le costó el inmueble y de las mejoras realizadas',
               'Suministros, confirmados al corriente'] },
      { h2: 'La fiscalidad de la venta',
        p: ['Cuando el vendedor no reside en España, el comprador está obligado a retener un porcentaje del precio e ingresarlo a cuenta del impuesto sobre la ganancia. Si supera lo realmente debido, el exceso se recupera, y esa presentación la hacemos nosotros.',
            'Existe además el impuesto municipal sobre el incremento del valor del suelo, que corresponde normalmente al vendedor. Calculamos ambos, junto con lo que puede deducirse, y le presentamos las cifras antes de la firma.'] },
      { h2: 'Si no está en España',
        p: ['Igual que en la compra, un poder notarial nos permite completar la venta en su nombre y ocuparnos de las presentaciones posteriores. Para un vendedor que vive fuera suele ser lo más práctico, porque ese trabajo continúa varios meses después.'] },
    ],
    faq: [
      { q: '¿Por qué me retiene el comprador parte del precio?',
        a: 'Porque no es usted residente fiscal en España. El comprador está legalmente obligado a retener un porcentaje e ingresarlo a cuenta del impuesto sobre su ganancia. Es habitual en toda venta de no residente.' },
      { q: '¿Puedo recuperar ese dinero?',
        a: 'Si la retención supera el impuesto realmente debido, sí, presentando en plazo y con la documentación de adquisición. Nos ocupamos de ello, aunque las devoluciones tardan algunos meses.' },
      { q: '¿Qué reduce la ganancia sujeta a impuesto?',
        a: 'Los costes de adquisición y las mejoras documentadas, junto con los gastos de la venta. Conservar facturas de las obras merece mucho la pena y le diremos qué computa.' },
      { q: '¿Puedo vender sin viajar a España?',
        a: 'Sí, mediante poder notarial. Firmamos en su nombre y nos encargamos después de las presentaciones y de cualquier devolución.' },
    ],
    related: [{ href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' },
              { href: '/es/derecho-inmobiliario/', label: 'Derecho inmobiliario en España' }],
  },
  'residencia-y-visados': {
    en: 'residency-and-visas', image: 'spanish-visa-application',
    imageAlt: 'Formulario de solicitud de visado español',
    metaTitle: 'Residencia y visados en España 2026 | Pujol Wilkie',
    metaDesc: 'Vías no lucrativa, nómada digital, emprendimiento y familiar hacia la residencia española, preparadas y presentadas desde nuestro despacho en Sotogrande.',
    eyebrow: 'Servicio', title: 'Residencia y visados',
    intro: 'Tenga o no residencia española, podemos ofrecerle la orientación y los pasos necesarios.',
    nav: 'Residencia y visados',
    sections: [
      { h2: 'Encontrar la vía adecuada',
        p: ['Desde el cierre del visado de inversores en abril de 2025, la residencia depende de cómo genera sus ingresos y no de lo que posee. La pregunta práctica es si su renta es pasiva, remota, por cuenta propia o de empleo aquí, y cuánto tiempo piensa pasar en España.',
            'Lo hablamos con usted primero, de modo que la solicitud que preparemos sea la que más probabilidades tiene de prosperar y no simplemente la más conocida.'] },
      { h2: 'Las vías principales',
        list: ['Residencia no lucrativa, con medios suficientes y sin trabajar en España',
               'Visado de nómada digital, para trabajo en remoto con empresas de fuera',
               'Cuenta propia y emprendimiento, con un proyecto empresarial real',
               'Tarjeta azul UE, para empleo altamente cualificado',
               'Reagrupación familiar con un residente en España',
               'Arraigo, para quien ya ha pasado aquí un periodo cualificado',
               'Autorizaciones de estudios, modificables en algunos casos'] },
      { h2: 'En qué consiste el proceso',
        p: ['La mayoría de las vías se solicitan en el consulado español del país de residencia o, en algunos casos, desde España. Concedida la autorización, se entra, se obtiene el TIE y se realiza el empadronamiento.',
            'Lo más largo suele ser reunir la documentación, porque los documentos extranjeros requieren apostilla y traducción jurada y tienen su propia validez. Le decimos qué hace falta y en qué orden, que es donde se evita la mayor parte del retraso.'] },
      { h2: 'Residencia y fiscalidad',
        p: ['Son cuestiones distintas. Una vía que implique más de 183 días al año aquí le hará, por regla general, residente fiscal en España por su renta mundial. Es mucho más fácil preverlo antes de solicitar que deshacerlo después, y se lo plantearemos desde el principio.'] },
    ],
    faq: [
      { q: '¿Qué visado me corresponde?',
        a: 'Depende de cómo genera sus ingresos y no de lo que posee. Las rentas pasivas apuntan a la no lucrativa, el trabajo en remoto a la de nómada digital y un negocio aquí a la cuenta propia. Cuéntenos su situación y le asesoramos.' },
      { q: '¿Puedo trabajar en remoto con una no lucrativa?',
        a: 'No, y esa es la diferencia esencial entre ambas. Si trabaja en remoto, la vía de nómada digital es la pensada para usted.' },
      { q: '¿Cuánto tarda la tramitación?',
        a: 'Varía bastante según consulado y vía. Reunir y legalizar la documentación suele ser lo más largo, así que recomendamos empezar pronto.' },
      { q: '¿Seré residente fiscal en España?',
        a: 'Si permanece más de 183 días al año, por regla general sí, por su renta mundial. Se lo planteamos desde el principio para que pueda preverse y no descubrirse después.' },
    ],
    related: [{ href: '/es/golden-visa-espana/', label: 'Qué pasó con la Golden Visa' },
              { href: '/es/tramites-de-extranjeria/', label: 'Trámites de extranjería' }],
  },
  'gibraltar-y-espana': {
    en: 'gibraltar-and-spain', image: 'rock-of-gibraltar-from-spain',
    imageAlt: 'El Peñón de Gibraltar visto desde la costa española cerca de Sotogrande',
    metaTitle: 'Gibraltar y España: asesoramiento transfronterizo',
    metaDesc: 'Asesoramiento para trabajadores transfronterizos, sociedades gibraltareñas con inmuebles en España y traslados entre ambas, por una abogada que ha ejercido en las dos.',
    eyebrow: 'Servicio', title: 'Gibraltar y España',
    intro: 'Asesoramiento que tiene en cuenta ambos lados de la verja, por una abogada que ha ejercido en los dos.',
    nav: 'Gibraltar y España',
    sections: [
      { h2: 'Dos sistemas, una misma comunidad',
        p: ['Sotogrande está a veinte minutos de la verja, y buena parte de nuestros clientes vive bajo un sistema mientras trabaja o tiene bienes bajo el otro.',
            'Habiendo iniciado mi ejercicio en España con el equipo jurídico español de Hassans en Gibraltar, y habiendo ejercido antes en el Reino Unido, asesoro sobre el punto en que ambos se encuentran y no solo sobre uno de ellos.'] },
      { h2: 'Asuntos que nos plantean',
        list: ['Trabajadores transfronterizos residentes en España y empleados en Gibraltar',
               'Residencia fiscal española y declaración de rentas de Gibraltar',
               'Sociedades gibraltareñas titulares de inmuebles en España',
               'Declaración de bienes situados fuera de España',
               'Traslados en cualquiera de las dos direcciones y la residencia resultante',
               'Sucesiones con bienes a ambos lados de la verja'] },
      { h2: 'Estructuras con inmuebles en España',
        p: ['Este tipo de estructuras fue habitual y la situación ha cambiado considerablemente. Cuando ya existe una, la pregunta útil suele ser si sigue sirviéndole y qué consecuencias tendría deshacerla. Ese cálculo exige mirar ambas jurisdicciones a la vez, y estaremos encantados de estudiarlo con usted.'] },
      { h2: 'Un panorama en movimiento',
        p: ['El marco que regula la relación entre Gibraltar y la Unión Europea lleva años perfilándose y sigue evolucionando. Todo lo que dependa de plazos conviene confirmarlo con nosotros en el momento de decidir.'] },
    ],
    faq: [
      { q: 'Vivo en España y trabajo en Gibraltar. ¿Dónde tributo?',
        a: 'Por lo general es residente fiscal en España por su renta mundial, cotizando en Gibraltar por el empleo. El acuerdo entre ambos establece cómo se determina la residencia, y estaremos encantados de revisar su caso.' },
      { q: 'Tengo un inmueble en España a través de una sociedad de Gibraltar. ¿Sigue teniendo sentido?',
        a: 'La situación ha cambiado bastante en los últimos años y conviene revisarlo. Mantener o deshacer la estructura depende de ambas jurisdicciones y lo estudiaríamos en conjunto con usted.' },
      { q: '¿Debo declarar mis cuentas de Gibraltar en España?',
        a: 'Si es residente fiscal en España y sus bienes en el extranjero superan los umbrales, sí. Es sencillo una vez bien planteado y podemos ocuparnos de ello.' },
    ],
    related: [{ href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' },
              { href: '/es/residencia-y-visados/', label: 'Residencia y visados' }],
  },
};
export default pages;
