// Las páginas heredadas conservan su ruta original en inglés bajo /es/ con slug propio.
const pages = {
'sobre-esther': {
    metaTitle: "Esther Pujol Wilkie, abogada en Sotogrande",
    metaDesc: "Colegiada nº 1432 del Colegio de Abogados de Cádiz y ejerciente desde 1990, trabajando casi siempre con clientes extranjeros que afrontan el derecho español.",
    en: 'about', legacy: true, image: 'esther-pujol-wilkie-abogada-sotogrande', imageAlt: 'Esther Pujol Wilkie, abogada, en su despacho de Sotogrande', eyebrow: 'Sobre Esther',
    title: 'Esther Pujol Wilkie',
    intro: 'Ejerciendo el derecho español desde 1990, casi siempre para quienes se enfrentan a él por primera vez.',
    nav: 'Sobre Esther',
    sections: [
      { h2: 'Barcelona, Londres, Gibraltar, Sotogrande',
        p: ['Nací en Barcelona y allí estudié Derecho. Antes de establecerme en esta costa ejercí en el Reino Unido y en Gibraltar, y cuento además con formación bancaria, algo que en materia inmobiliaria resulta útil más a menudo de lo que cabría esperar.',
            'Desde mi colegiación en el Colegio de Abogados de Cádiz en 1990 trabajo desde Sotogrande. Mis clientes son en su mayoría extranjeros que se enfrentan por primera vez al derecho español, normalmente con motivo de una compra y con frecuencia desde fuera de España.'] },
      { h2: 'Cómo funciona el despacho',
        p: ['Trabajo para el cliente y para nadie más. Sin acuerdos de comisión con agencias ni con promotoras, sin lealtades divididas. Parece obvio hasta que se comprende qué proporción del trabajo inmobiliario en esta costa llega por la parte vendedora.',
            'La mayoría de los asuntos empiezan con una operación y continúan durante años: la compra lleva a las declaraciones, las declaraciones a la residencia y, con el tiempo, el mismo despacho gestiona la venta o la herencia.'] },
      { h2: 'Idiomas y jurisdicciones',
        list: ['Español e inglés con fluidez, con cada documento explicado con claridad',
               'Colegiada y en ejercicio en España',
               'Ejercicio previo en el Reino Unido y en Gibraltar',
               'Asuntos transfronterizos entre España y Gibraltar'] },
      { h2: 'Trabajar con clientes que no están aquí',
        p: ['Buena parte de mis clientes no reside en España la mayor parte del año, de modo que gran parte del trabajo se realiza a distancia mediante poder notarial: firmar ante notario, presentar declaraciones y tratar con el ayuntamiento y con Hacienda.',
            'En junio de 2026 complet\u00e9 el Diploma en Competencias Digitales Profesionales del Consejo General de la Abogac\u00eda Espa\u00f1ola, un programa de 150 horas impartido junto con Uni\u00f3n Profesional, directamente relacionado con la forma en que hoy se desarrolla ese trabajo: presentaciones telem\u00e1ticas, firma digital y tratamiento seguro de documentaci\u00f3n de clientes entre jurisdicciones.'] },
      { h2: 'El despacho',
        p: ['El despacho está en Guadalmarina, en la Avenida de la Marina, a pocos minutos del puerto. Buena parte del trabajo se realiza a distancia mediante poder notarial para quienes no están en España.'] },
    ],
    related: [{ href: '/es/servicio-integral/', label: 'Cómo trabajo con mis clientes' },
              { href: '/es/contacto/', label: 'Solicitar una consulta gratuita' }],
  },
  'contacto': {
    metaTitle: "Contacto | Abogada en Sotogrande, Cádiz",
    metaDesc: "Primera consulta gratuita sobre comprar, vender o mantener una propiedad en España. Respuesta en un día laborable, en español o en inglés, desde Sotogrande.",
    en: 'contact', legacy: true, image: 'polo-sotogrande', imageAlt: 'Partido de polo en Sotogrande', eyebrow: 'Contacto',
    title: 'Contacto',
    intro: 'Una primera conversación gratuita sobre lo que tiene en mente, sin compromiso.',
    nav: 'Contacto',
    sections: [
      { h2: 'Qué ocurre cuando contacta',
        p: ['Puede usar el formulario, llamar al despacho o escribir por correo. Respondo personalmente, normalmente en un día laborable.',
            'La primera conversación no tiene coste. Suele bastar para saber si lo que plantea es sencillo, en qué consiste el proceso, cuánto costará aproximadamente y si necesita abogada. A veces la respuesta es que no.'] },
      { h2: 'Conviene indicar',
        list: ['Si compra, vende o ya es propietario', 'Dónde está la propiedad o dónde busca',
               'Si ya ha firmado algo y, en ese caso, qué', 'Su nacionalidad y dónde es residente fiscal',
               'Si la residencia en España forma parte del plan'] },
      { h2: 'Si ya ha firmado algo',
        p: ['Si ha firmado un contrato de reserva o de arras y tiene dudas, indíquelo en el primer mensaje. En esas situaciones el tiempo cuenta y suele haber más opciones de las que se piensa.'] },
    ],
    related: [{ href: '/es/compraventa/', label: 'Comprar una propiedad en España' }],
  },
  'derecho-inmobiliario': {
    metaTitle: "Derecho inmobiliario en España | Pujol Wilkie",
    metaDesc: "Cómo funciona realmente el derecho inmobiliario español para el propietario extranjero: inscripción registral, cargas que siguen a la finca y comprobaciones previas.",
    faq: [
      {
            "q": "¿Qué es la nota simple y por qué importa?",
            "a": "Es el extracto del Registro que acredita quién es el titular, cómo se describe la finca y qué cargas pesan sobre ella. Cuesta muy poco y es el punto de partida de toda compra, porque las deudas y las cargas siguen a la finca y no a quien las generó."
      },
      {
            "q": "¿Puedo heredar las deudas del anterior propietario?",
            "a": "En la práctica, sí. Hipotecas, cuotas de comunidad impagadas del año en curso y los tres anteriores, IBI atrasado y embargos quedan afectos a la finca. Quien no comprueba puede acabar pagando atrasos ajenos."
      },
      {
            "q": "¿Y si la vivienda tiene una ampliación no declarada?",
            "a": "Es uno de los tres problemas más frecuentes y rara vez se aprecia en una visita. Según la antigüedad de la obra y la situación urbanística, puede ser legalizable, puede estar sujeta a expediente o puede simplemente restar valor en una futura venta. Debe detectarse antes de firmar."
      },
      {
            "q": "¿El notario comprueba la finca por mí?",
            "a": "No. El notario es un funcionario público que da fe de la escritura y verifica identidad y capacidad. Comprobar la situación física, urbanística y de cargas no forma parte de esa función, y ni la agencia ni el abogado de la promotora trabajan para usted."
      },
      {
            "q": "¿Debo otorgar testamento en España?",
            "a": "Si posee un inmueble aquí, sí. Sin él, el procedimiento para sus herederos resulta más lento, más caro e íntegramente en español. El testamento español es además el lugar natural para hacer la elección del Reglamento UE 650/2012."
      }
    ],
    en: 'property-law', image: 'villa-pool-costa-del-sol', imageAlt: 'Villa con piscina en la Costa del Sol, típica de las compraventas en Sotogrande', eyebrow: '\u00c1rea de pr\u00e1ctica',
    title: 'Derecho inmobiliario en Espa\u00f1a',
    intro: 'El marco legal que hay detr\u00e1s de cada compraventa en Espa\u00f1a y lo que significa para un propietario extranjero.',
    nav: 'Derecho inmobiliario',
    sections: [
      { h2: 'Un sistema distinto al que usted conoce',
        p: ['La propiedad se transmite ante notario mediante escritura p\u00fablica y solo despliega plenos efectos frente a terceros una vez inscrita en el Registro de la Propiedad. Hasta esa inscripci\u00f3n, la posici\u00f3n del comprador es m\u00e1s d\u00e9bil de lo que suele suponerse.',
            'Espa\u00f1a funciona con un sistema de inscripci\u00f3n voluntaria pero determinante. Una finca puede pertenecer v\u00e1lidamente a alguien sin estar inscrita, pero el titular no inscrito queda expuesto frente a un adquirente posterior que s\u00ed inscriba de buena fe. Por eso el plazo entre la firma y la inscripci\u00f3n debe medirse en d\u00edas y no en meses.',
            'La consecuencia pr\u00e1ctica es que casi todo depende de las comprobaciones previas a la firma. Las deudas, las cargas y las irregularidades urban\u00edsticas siguen a la finca, no a quien las gener\u00f3, de modo que un comprador puede heredar problemas ajenos.'] },
      { h2: 'Lo que sigue a la finca, no al vendedor',
        list: ['Hipotecas y cualquier otra carga inscrita en el Registro',
               'Cuotas de comunidad impagadas, por lo general del a\u00f1o en curso y los tres anteriores',
               'IBI pendiente, el impuesto municipal anual',
               'Embargos y procedimientos judiciales en curso',
               'Infracciones urban\u00edsticas por obras sin licencia o no declaradas',
               'Servidumbres y derechos de paso, sean o no evidentes sobre el terreno'] },
      { h2: 'Los documentos que importan',
        p: ['La nota simple es el extracto registral que acredita la titularidad, la descripci\u00f3n de la finca y las cargas que pesan sobre ella. Es el punto de partida de toda compra y su coste es m\u00ednimo. Se trata de un extracto informativo; cuando un asunto es litigioso, la certificaci\u00f3n registral tiene mayor valor.',
            'El catastro es independiente y tiene finalidad fiscal. Ambos discrepan con frecuencia en superficie o linderos, y conviene conciliarlos antes de la firma para evitar problemas en una futura venta. Una discrepancia no es necesariamente un problema, pero s\u00ed lo es una discrepancia sin explicaci\u00f3n.',
            'En obra relativamente reciente, la licencia de primera ocupaci\u00f3n y la situaci\u00f3n urban\u00edstica en el ayuntamiento importan tanto como el asiento registral. Una construcci\u00f3n puede estar inscrita y ser ilegal.'] },
      { h2: 'D\u00f3nde suelen aparecer los problemas',
        p: ['Tres situaciones concentran la mayor parte de las dificultades. La primera son las obras no declaradas: una terraza cerrada, una piscina a\u00f1adida, un s\u00f3tano acondicionado, nada de ello con licencia ni reflejado en el Registro. Rara vez se aprecia en una visita y su legalizaci\u00f3n posterior resulta cara.',
            'La segunda es el t\u00edtulo hereditario. Cuando el vendedor adquiri\u00f3 por una herencia que nunca se complet\u00f3 debidamente, el tracto sucesivo presenta una laguna y no puede firmarse con seguridad hasta cerrarla.',
            'La tercera es el suelo r\u00fastico. Las limitaciones de edificaci\u00f3n son bastante m\u00e1s estrictas de lo que los compradores esperan, y que exista una casa sobre el terreno no acredita que sea legal.'] },
      { h2: 'C\u00f3mo se ostenta la propiedad',
        p: ['La forma de titularidad tiene consecuencias que sobreviven a la compra. La titularidad conjunta entre c\u00f3nyuges, a trav\u00e9s de sociedad o compartida entre familiares tiene efectos fiscales distintos en la transmisi\u00f3n y consecuencias distintas en caso de fallecimiento.',
            'El r\u00e9gimen sucesorio espa\u00f1ol y las legítimas pueden aplicarse a los bienes situados en Espa\u00f1a de un modo que sorprende a los propietarios procedentes del common law. El Reglamento UE 650/2012 permite a un extranjero elegir la ley de su nacionalidad para regir su sucesi\u00f3n, pero la elecci\u00f3n debe hacerse de forma expresa, normalmente en testamento otorgado en Espa\u00f1a.'] },
      { h2: 'D\u00f3nde intervengo',
        p: ['Actúo para el comprador o el propietario, nunca para la agencia ni para la promotora. Eso significa que las comprobaciones se realizan, el contrato se lee antes de que se le pida firmarlo y la posici\u00f3n fiscal se calcula por anticipado en lugar de descubrirse en la notaría.',
            'Cuando algo no está en orden, la cuestión rara vez es si conviene retirarse. Suele ser qué exigir al vendedor que subsane, qué retener del precio hasta que lo haga y qué reflejar en la escritura para que el problema no reaparezca cuando usted quiera vender.'] },
    ],
    related: [{ href: '/es/compraventa/', label: 'Comprar una propiedad: el proceso completo' },
              { href: '/es/venta-de-propiedades/', label: 'Vender una propiedad en Espa\u00f1a' },
              { href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' }],
  },
  'golden-visa-espana': {
    metaTitle: "Golden Visa España: derogada en abril de 2025",
    metaDesc: "El visado de inversores quedó derogado el 3 de abril de 2025. Qué ocurre con los titulares actuales, qué vías siguen abiertas y la consecuencia fiscal que se pasa por alto.",
    faq: [
      {
            "q": "¿Puedo solicitar todavía la Golden Visa española?",
            "a": "No. La Ley Orgánica 1/2025 derogó el régimen y dejó de admitir solicitudes el 3 de abril de 2025. No hay sustituto, ni periodo transitorio, ni umbral a partir del cual la compra otorgue residencia. Comprar sigue estando plenamente abierto a extranjeros, pero sin consecuencia migratoria."
      },
      {
            "q": "Ya soy titular. ¿Qué ocurre con mi permiso?",
            "a": "Las disposiciones transitorias protegen a los titulares. Si la autorización se concedió, o la solicitud se presentó, antes de la fecha de corte, su situación continúa y la renovación sigue siendo posible mientras se mantengan las condiciones originales, incluida la inversión."
      },
      {
            "q": "¿Puedo vender el inmueble que dio derecho a mi Golden Visa?",
            "a": "Puede venderlo, pero la venta extingue por lo general la base de la renovación. La transmisión debe planificarse junto con su situación de residencia. Si se acerca a los diez años de residencia legal, la residencia de larga duración o la nacionalidad pueden eliminar la dependencia de la inversión."
      },
      {
            "q": "¿Qué sustituyó a la Golden Visa?",
            "a": "Nada de forma directa. Siguen abiertas la no lucrativa, la de nómada digital, las vías de emprendimiento, la tarjeta azul UE y la reagrupación familiar, pero todas esperan que resida efectivamente en España buena parte del año. La Golden Visa era inusual precisamente porque no lo exigía."
      },
      {
            "q": "¿Comprar una vivienda más cara sigue dando derecho?",
            "a": "No. El umbral de 500.000 euros no se ha elevado: se ha suprimido. Ninguna compra, por elevado que sea su importe, genera derecho de residencia."
      }
    ],
    en: 'spanish-golden-visa', image: 'spanish-visa-application', imageAlt: 'Formulario de solicitud de visado español', eyebrow: 'Residencia',
    title: 'La Golden Visa espa\u00f1ola',
    intro: 'La v\u00eda de residencia por inversi\u00f3n se cerr\u00f3 el 3 de abril de 2025. Qu\u00e9 ocurre si ya la tiene y qu\u00e9 alternativas existen.',
    nav: 'Golden Visa',
    sections: [
      { h2: 'El programa ha terminado',
        p: ['El visado de residencia para inversores qued\u00f3 derogado por la Ley Org\u00e1nica 1/2025, publicada en el BOE el 3 de enero de 2025 y con efectos desde el 3 de abril de 2025. Se suprimieron los art\u00edculos 63 a 67 de la Ley 14/2013, base legal del r\u00e9gimen desde 2013.',
            'No hay sustituto ni periodo transitorio para nuevas solicitudes. Comprar un inmueble en Espa\u00f1a ya no otorga ning\u00fan derecho de residencia, sea cual sea su valor.'] },
      { h2: 'Qu\u00e9 ofrec\u00eda el r\u00e9gimen',
        p: ['La v\u00eda m\u00e1s conocida era la compra de inmuebles por al menos 500.000 euros libres de carga por ese importe. Otras inversiones admitidas eran un mill\u00f3n de euros en acciones de sociedades espa\u00f1olas o en fondos, dos millones en deuda p\u00fablica, un dep\u00f3sito bancario de un mill\u00f3n o un proyecto empresarial de inter\u00e9s general.',
            'Lo verdaderamente inusual no era el umbral sino la ausencia de exigencia de residencia efectiva. Bastaba una visita anual para mantener el permiso, y por eso atra\u00eda a quienes buscaban movilidad Schengen sin trasladarse. Ninguna v\u00eda actual reproduce eso.'] },
      { h2: 'Por qu\u00e9 se suprimi\u00f3',
        p: ['El motivo declarado fue la asequibilidad de la vivienda. El Gobierno sostuvo que vincular la residencia a la inversi\u00f3n inmobiliaria presionaba los precios en Madrid, Barcelona, Valencia y Baleares, y present\u00f3 la derogaci\u00f3n como protecci\u00f3n de la vivienda como derecho.',
            'Existi\u00f3 adem\u00e1s presi\u00f3n sostenida de la Comisi\u00f3n Europea, que desde hac\u00eda a\u00f1os consideraba que estos programas planteaban riesgos en materia de seguridad, blanqueo de capitales y transparencia fiscal.'] },
      { h2: 'Si ya es titular',
        p: ['Las disposiciones transitorias protegen a quienes obtuvieron la autorizaci\u00f3n, o presentaron la solicitud, antes de la fecha de corte. La renovaci\u00f3n sigue siendo posible mientras se mantengan las condiciones originales, incluida la conservaci\u00f3n de la inversi\u00f3n.',
            'Dos puntos conviene decirlos con claridad. Vender el inmueble que dio derecho al permiso extingue por lo general la base de la renovaci\u00f3n, de modo que una venta debe planificarse junto con la situaci\u00f3n de residencia. Y tras diez a\u00f1os de residencia legal, cumpliendo los requisitos de presencia, pueden abrirse la residencia de larga duraci\u00f3n o la nacionalidad, que eliminan la dependencia de la inversi\u00f3n.'] },
      { h2: 'Qu\u00e9 queda disponible',
        list: ['Residencia no lucrativa, con rentas pasivas suficientes y sin trabajar en Espa\u00f1a',
               'Visado de n\u00f3mada digital, para trabajo en remoto con empresas de fuera de Espa\u00f1a',
               'V\u00edas de emprendimiento y trabajo por cuenta propia, con proyecto empresarial real',
               'Tarjeta azul UE, para empleo altamente cualificado con t\u00edtulo reconocido',
               'Reagrupaci\u00f3n familiar con un residente en Espa\u00f1a',
               'Libre circulaci\u00f3n, para nacionales de la UE y del EEE y sus familiares'] },
      { h2: 'El punto fiscal que se suele pasar por alto',
        p: ['Residencia y residencia fiscal son cuestiones distintas. Permanecer m\u00e1s de 183 d\u00edas en Espa\u00f1a en un a\u00f1o natural le convierte, por regla general, en residente fiscal aqu\u00ed por su renta mundial, con independencia del permiso que tenga.',
            'La Golden Visa permit\u00eda mantener residencia espa\u00f1ola siendo residente fiscal en otro pa\u00eds, porque apenas exig\u00eda presencia. Las v\u00edas que la sustituyen no lo permiten, lo que cambia sustancialmente el c\u00e1lculo para quien tenga rentas o patrimonio fuera de Espa\u00f1a.'] },
      { h2: 'Errores frecuentes',
        list: ['Creer que comprar antes de cierta fecha a\u00fan da derecho. No lo da: la fecha de corte era la de solicitud, el 3 de abril de 2025',
               'Creer que un precio superior reabre la v\u00eda. No existe umbral alguno',
               'Creer que los titulares actuales deben vender o marcharse. No es as\u00ed',
               'Creer que otros pa\u00edses ofrecen equivalentes. Algunos mantienen programas, pero no mediante compra de vivienda en Espa\u00f1a'] },
    ],
    related: [{ href: '/es/residencia-y-visados/', label: 'Las v\u00edas de residencia abiertas' },
              { href: '/es/tramites-de-extranjeria/', label: 'Tr\u00e1mites de extranjer\u00eda' },
              { href: '/es/fiscalidad/', label: 'Residencia fiscal y obligaciones' }],
  },
  'fiscalidad': {
    metaTitle: "Fiscalidad inmobiliaria para no residentes | Pujol Wilkie",
    metaDesc: "Impuestos de la compra, modelo 210, IBI y ganancia patrimonial explicados por una abogada en Sotogrande, incluida la diferencia entre residentes UE y terceros países.",
    faq: [
      {
            "q": "¿Debo presentar declaración si mi vivienda está vacía?",
            "a": "Sí. El propietario no residente presenta el modelo 210 se alquile o no el inmueble. Si permanece vacío, se tributa por una renta imputada calculada sobre el valor catastral. Las declaraciones no presentadas se acumulan y afloran al vender."
      },
      {
            "q": "¿Cuánto tributa el alquiler siendo no residente?",
            "a": "Los residentes en la UE, Noruega e Islandia tributan al diecinueve por ciento y pueden deducir gastos en proporción al periodo arrendado. Los residentes en terceros países tributan al veinticuatro por ciento sobre el ingreso bruto sin deducción alguna. Desde el Brexit, los propietarios británicos quedan en el segundo grupo."
      },
      {
            "q": "¿Qué es el valor de referencia?",
            "a": "Una base mínima de tributación fijada por el Catastro desde 2022. Si el precio pactado queda por debajo, el ITP se liquida sobre el valor de referencia y no sobre lo pagado. Puede impugnarse, pero solo después de ingresar, de modo que conviene comprobarlo antes de cerrar el precio."
      },
      {
            "q": "¿Qué es la retención del 3% al vender?",
            "a": "Si el vendedor no es residente fiscal en España, el comprador retiene el tres por ciento del precio y lo ingresa en Hacienda a cuenta de la ganancia patrimonial. Si la deuda real es menor, el exceso se recupera presentando en plazo, aunque la devolución suele tardar entre seis y doce meses."
      },
      {
            "q": "¿Qué gastos reducen la ganancia patrimonial?",
            "a": "El ITP satisfecho en la compra, la notaría, el Registro, los honorarios y las mejoras documentadas incrementan el valor de adquisición. El mantenimiento ordinario y la redecoración no. Conservar las facturas de una cubierta nueva o una ampliación suele valer varios miles de euros."
      }
    ],
    en: 'tax-and-accountancy', image: 'coastal-property-costa-del-sol', imageAlt: 'Inmuebles y puerto deportivo en la Costa del Sol', eyebrow: '\u00c1rea de pr\u00e1ctica',
    title: 'Fiscalidad y contabilidad',
    intro: 'Los impuestos de la compra, los que se repiten cada a\u00f1o y las declaraciones que hay que presentar viva o no en Espa\u00f1a.',
    nav: 'Fiscalidad',
    sections: [
      { h2: 'En la compra',
        p: ['Una segunda transmisi\u00f3n en Andaluc\u00eda tributa por ITP, actualmente al siete por ciento. La obra nueva adquirida al promotor tributa por IVA al diez por ciento m\u00e1s AJD. Notar\u00eda, Registro y honorarios se suman, y una previsi\u00f3n razonable es del diez al doce por ciento sobre el precio.',
            'El valor de referencia, introducido en 2022 y fijado por el Catastro, establece una base m\u00ednima de tributaci\u00f3n. Cuando el precio pactado queda por debajo, se liquida sobre el valor de referencia. Puede impugnarse, pero la impugnaci\u00f3n es posterior al pago, de modo que conviene comprobarlo antes de cerrar el precio.'] },
      { h2: 'Cada a\u00f1o, como propietario no residente',
        list: ['Modelo 210, se alquile o no el inmueble',
               'IBI, impuesto municipal anual',
               'Cuotas de comunidad, si el inmueble forma parte de una comunidad',
               'Impuesto sobre el patrimonio, al superarse los umbrales, que var\u00edan por comunidad aut\u00f3noma',
               'Tasa de basuras y dem\u00e1s tributos municipales'],
        p: ['Cuando el inmueble permanece vac\u00edo, el modelo 210 sigue siendo obligatorio: se tributa por una renta imputada calculada sobre el valor catastral. Sorprende que un inmueble sin uso genere obligaci\u00f3n, pero la genera todos los a\u00f1os, y las declaraciones no presentadas se acumulan en silencio.'] },
      { h2: 'Si alquila el inmueble',
        p: ['El rendimiento del alquiler se declara trimestralmente. Los residentes en la Uni\u00f3n Europea, Noruega e Islandia pueden deducir gastos en proporci\u00f3n al periodo arrendado y tributan al diecinueve por ciento. Los residentes en terceros pa\u00edses no pueden deducir gasto alguno y tributan al veinticuatro por ciento sobre el ingreso bruto.',
            'Desde el Brexit esa distinci\u00f3n afecta a los propietarios brit\u00e1nicos y tiene un efecto relevante sobre el rendimiento neto. La compatibilidad de esa diferencia con la libre circulaci\u00f3n de capitales ha sido objeto de litigio en m\u00e1s de una ocasi\u00f3n, por lo que conviene revisar la situaci\u00f3n y no darla por cerrada.',
            'El alquiler tur\u00edstico exige adem\u00e1s inscripci\u00f3n en el registro correspondiente en Andaluc\u00eda, y el marco estatal en esta materia ha cambiado varias veces recientemente.'] },
      { h2: 'En la venta',
        p: ['La ganancia patrimonial se calcula por diferencia entre valor de adquisici\u00f3n y de transmisi\u00f3n, ajustada con los gastos deducibles: el ITP satisfecho en la compra, notar\u00eda, Registro, honorarios y las mejoras documentadas. El mantenimiento ordinario no computa, y conservar las facturas de lo que s\u00ed computa vale m\u00e1s de lo que la mayor\u00eda supone.',
            'Si el vendedor no es residente, el comprador retiene el tres por ciento del precio y lo ingresa mediante el modelo 211 a cuenta de la ganancia. Cuando la deuda real es menor, el exceso se recupera presentando el modelo 210 en plazo y con la documentaci\u00f3n en regla.',
            'La plusval\u00eda municipal corresponde por lo general al vendedor. Desde la sentencia del Tribunal Constitucional de 2021 y la reforma posterior existen dos m\u00e9todos de c\u00e1lculo y puede elegirse el m\u00e1s favorable. Si no ha habido incremento real de valor, no se devenga.'] },
      { h2: 'Bienes situados fuera de Espa\u00f1a',
        p: ['Los residentes fiscales en Espa\u00f1a deben declarar mediante el modelo 720 los bienes en el extranjero que superen los cincuenta mil euros por categor\u00eda. El r\u00e9gimen sancionador asociado fue declarado desproporcionado por el Tribunal de Justicia de la Uni\u00f3n Europea en 2022 y posteriormente revisado, pero la obligaci\u00f3n de declarar subsiste.'] },
      { h2: 'C\u00f3mo trabajo estos asuntos',
        p: ['Para la mayor\u00eda de los clientes se trata de un encargo continuado y no puntual. Las declaraciones se preparan y presentan en plazo, los tributos municipales se abonan y la situaci\u00f3n se revisa cuando cambian las circunstancias: un alquiler que comienza, un traslado a Espa\u00f1a o una venta en perspectiva.'] },
    ],
    related: [{ href: '/es/venta-de-propiedades/', label: 'Vender una propiedad en Espa\u00f1a' },
              { href: '/es/gestion-de-propiedades/', label: 'Gesti\u00f3n de propiedades' }],
  },
  'tramites-de-extranjeria': {
    metaTitle: "Trámites de extranjería en España | Pujol Wilkie",
    metaDesc: "NIE, empadronamiento, TIE y tarjetas de residencia tramitados en su nombre, además de la situación de los ciudadanos británicos tras el Brexit.",
    en: 'immigration-and-foreigners-legal-procedures', image: 'yachts-puerto-sotogrande', imageAlt: 'Embarcaciones amarradas en el Puerto de Sotogrande', eyebrow: '\u00c1rea de pr\u00e1ctica',
    title: 'Extranjer\u00eda y tr\u00e1mites administrativos',
    intro: 'La maquinaria administrativa que acompa\u00f1a a vivir o tener algo en Espa\u00f1a siendo extranjero.',
    nav: 'Extranjer\u00eda',
    sections: [
      { h2: 'El papeleo del d\u00eda a d\u00eda',
        p: ['Lo dif\u00edcil no suele ser la ley sino la administraci\u00f3n: citas que hay que reservar con semanas de antelaci\u00f3n y desaparecen a los pocos minutos de liberarse, documentos que deben legalizarse o apostillarse y traducirse por traductor jurado, y oficinas que rechazan un expediente por un solo campo mal cumplimentado.',
            'Nada de ello es intelectualmente complejo. Simplemente no perdona errores peque\u00f1os, y cada error cuesta otra cita. Tramito estos procedimientos en nombre del cliente, normalmente mediante poder notarial, de modo que no sea necesario acudir en persona.'] },
      { h2: 'Tr\u00e1mites que gestiono',
        list: ['NIE, n\u00famero de identificaci\u00f3n de extranjero, necesario para casi toda operaci\u00f3n',
               'Empadronamiento, del que dependen muchos otros tr\u00e1mites',
               'TIE, tarjeta f\u00edsica de residencia, y sus renovaciones',
               'Certificados de residencia para ciudadanos de la UE e inscripci\u00f3n en el Registro Central de Extranjeros',
               'Canje de permiso de conducir y matriculaci\u00f3n o importaci\u00f3n de veh\u00edculos',
               'Legalizaci\u00f3n, apostilla y traducci\u00f3n jurada de documentos extranjeros',
               'Alta en la Seguridad Social y en el r\u00e9gimen de aut\u00f3nomos cuando proceda',
               'Asistencia sanitaria y tarjeta sanitaria'] },
      { h2: 'Ciudadanos brit\u00e1nicos tras el Brexit',
        p: ['Quienes residían legalmente en Espa\u00f1a antes del 31 de diciembre de 2020 conservan sus derechos bajo el Acuerdo de Retirada, acreditados mediante el TIE con la menci\u00f3n del art\u00edculo correspondiente. Esos derechos son equivalentes en lo esencial a la situaci\u00f3n anterior al Brexit y no se ven afectados por cambios posteriores en el r\u00e9gimen general.',
            'Quienes llegaron despu\u00e9s son nacionales de tercer pa\u00eds y necesitan una v\u00eda de visado como cualquier otro extranjero no comunitario. La distinci\u00f3n tiene consecuencias importantes, sobre todo para quienes pasaron temporadas aqu\u00ed antes de 2021 sin registrarse formalmente.',
            'La estancia sin residencia queda adem\u00e1s limitada por la regla de noventa d\u00edas dentro de cualquier periodo de ciento ochenta, algo que sorprende a los propietarios de segunda residencia acostumbrados a entrar y salir sin restricci\u00f3n.'] },
      { h2: 'Documentos procedentes del extranjero',
        p: ['Casi todo documento extranjero presentado ante una autoridad espa\u00f1ola requiere apostilla conforme al Convenio de La Haya y traducci\u00f3n realizada por traductor jurado reconocido en Espa\u00f1a. Una traducci\u00f3n hecha fuera, por competente que sea, suele rechazarse.',
            'Certificados como los antecedentes penales o las partidas de nacimiento tienen adem\u00e1s periodos de validez, habitualmente de tres o seis meses, de modo que obtenerlos demasiado pronto es tan problem\u00e1tico como hacerlo tarde. El orden importa m\u00e1s que la rapidez.'] },
      { h2: 'D\u00f3nde suele torcerse',
        p: ['Los fallos m\u00e1s frecuentes son de procedimiento y no de fondo: cita en la oficina equivocada, certificado caducado entre la presentaci\u00f3n y la revisi\u00f3n, documento apostillado pero sin traducir, o resoluci\u00f3n que llega estando el interesado fuera de Espa\u00f1a y queda sin responder en plazo.',
            'Cuando ya existe denegaci\u00f3n, el plazo para interponer recurso es breve y se pierde con facilidad. Si ha recibido una resoluci\u00f3n desfavorable, conviene plantearlo de inmediato y no despu\u00e9s de valorar opciones.'] },
    ],
    related: [{ href: '/es/residencia-y-visados/', label: 'Residencia y visados' },
              { href: '/es/gibraltar-y-espana/', label: 'Gibraltar y Espa\u00f1a' }],
  },
  'gestion-de-propiedades': {
    metaTitle: "Gestión de propiedades en Sotogrande | Pujol Wilkie",
    metaDesc: "Suministros, cuotas de comunidad, seguros y custodia de llaves para propietarios que no residen en España todo el año, con representación en la junta.",
    en: 'property-management-services', image: 'property-keys-handover-spain', imageAlt: 'Entrega de llaves en la firma de una compraventa en España', eyebrow: '\u00c1rea de pr\u00e1ctica',
    title: 'Gesti\u00f3n de propiedades',
    intro: 'Mantener una propiedad en Espa\u00f1a en orden cuando no se reside aqu\u00ed la mayor parte del a\u00f1o.',
    nav: 'Gesti\u00f3n de propiedades',
    sections: [
      { h2: 'Qu\u00e9 necesita cubrir un propietario ausente',
        list: ['Contratos de suministro, cambios de titularidad, lecturas y domiciliaciones',
               'Cuotas de comunidad, correspondencia y representaci\u00f3n en juntas',
               'Seguros de continente y contenido, contrataci\u00f3n, renovaci\u00f3n y siniestros',
               'IBI y tasa de basuras abonados en plazo',
               'Custodia de llaves, acceso a gremios e inspecciones peri\u00f3dicas',
               'Coordinaci\u00f3n de reparaciones y supervisi\u00f3n de industriales',
               'Recepci\u00f3n de notificaciones oficiales, que se entregan en papel y en el domicilio'] },
      { h2: 'Por qu\u00e9 importa',
        p: ['Las cuotas de comunidad y los tributos municipales impagados no prescriben sin m\u00e1s: se acumulan contra la finca y afloran en el momento de la venta, a veces a\u00f1os despu\u00e9s y casi siempre en el peor momento. Mantenerlos al d\u00eda resulta mucho m\u00e1s barato que resolverlos con un comprador esperando.',
            'La comunidad de propietarios puede adem\u00e1s afectar la finca al pago de lo adeudado y, en casos graves, instar su ejecuci\u00f3n. Quien da por hecho que nada ocurre mientras est\u00e1 fuera suele acertar hasta que deja de acertar.'] },
      { h2: 'La comunidad de propietarios',
        p: ['Cuando el inmueble forma parte de una comunidad, la propiedad conlleva una cuota de participaci\u00f3n en los gastos comunes y un voto en la junta. Lo que all\u00ed se decide sobre sustituci\u00f3n de ascensor, cubierta, piscina o fachada genera derramas, a veces elevadas, que vinculan al propietario asistiera o no.',
            'Las convocatorias se env\u00edan en espa\u00f1ol al domicilio que consta en la comunidad, y el plazo para impugnar un acuerdo es breve. La representaci\u00f3n en junta evita que las decisiones se descubran despu\u00e9s por un recibo inesperado.'] },
      { h2: 'Si alquila',
        p: ['Alquilar, sea de larga temporada o tur\u00edstico, a\u00f1ade obligaciones: inscripci\u00f3n de la vivienda con fines tur\u00edsticos en Andaluc\u00eda, declaraciones trimestrales y cumplimiento de la normativa de registro de viajeros.',
            'El marco estatal del alquiler de corta duraci\u00f3n ha cambiado varias veces en los \u00faltimos a\u00f1os y sigue movi\u00e9ndose. Conviene confirmar la situaci\u00f3n vigente y no apoyarse en la que reg\u00eda al comprar.'] },
      { h2: 'C\u00f3mo funciona en la pr\u00e1ctica',
        p: ['Suele articularse como encargo anual junto con las obligaciones fiscales, de modo que un solo despacho concentre los suministros, la relaci\u00f3n con la comunidad, los seguros y la situaci\u00f3n tributaria. La ventaja pr\u00e1ctica es que nada se presume responsabilidad de otro, que es donde empiezan casi todos los problemas de la propiedad a distancia.'] },
    ],
    related: [{ href: '/es/servicio-integral/', label: 'Servicio integral al cliente' },
              { href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' }],
  },
  'servicio-integral': {
    metaTitle: "Servicio integral al cliente | Abogada en Sotogrande",
    metaDesc: "Inmobiliario, fiscal, residencia, herencias y administración atendidos desde un mismo despacho mientras tenga bienes en España, incluido mediante poder notarial.",
    en: 'full-client-service', image: 'polo-sotogrande', imageAlt: 'Partido de polo en Sotogrande', eyebrow: 'C\u00f3mo trabajo',
    title: 'Servicio integral al cliente',
    intro: 'Asuntos legales, fiscales y administrativos atendidos desde un mismo despacho, mientras tenga algo aqu\u00ed.',
    nav: 'Servicio integral',
    sections: [
      { h2: 'Un despacho, toda la relaci\u00f3n',
        p: ['La mayor\u00eda de los clientes llega con una sola operaci\u00f3n en mente y se queda para todo lo que viene despu\u00e9s: la compra lleva a las declaraciones, las declaraciones a la residencia y, a\u00f1os m\u00e1s tarde, el mismo despacho gestiona la venta o la herencia.',
            'Tenerlo todo en un mismo sitio evita el supuesto de que algo ya lo habr\u00e1 hecho otro, que es donde empiezan casi todos los problemas transfronterizos. Significa adem\u00e1s que quien asesora en la venta conserva el expediente de la compra, algo decisivo cuando se calcula la ganancia patrimonial quince a\u00f1os despu\u00e9s.'] },
      { h2: 'Qu\u00e9 incluye',
        list: ['Compraventa de inmuebles', 'Cumplimiento fiscal anual de residentes y no residentes',
               'Residencia, visados y extranjer\u00eda', 'Testamentos, herencias y planificaci\u00f3n sucesoria',
               'Gesti\u00f3n y administraci\u00f3n de inmuebles', 'Representaci\u00f3n mediante poder notarial',
               'Asuntos transfronterizos entre Espa\u00f1a y Gibraltar'] },
      { h2: 'Testamentos y sucesiones',
        p: ['Quien posee un inmueble en Espa\u00f1a deber\u00eda otorgar testamento espa\u00f1ol sobre sus bienes aqu\u00ed. Sin \u00e9l, la sucesi\u00f3n se resuelve por las reglas aplicables por defecto y el procedimiento para los herederos resulta m\u00e1s lento, m\u00e1s caro y \u00edntegramente en espa\u00f1ol.',
            'El Reglamento UE 650/2012 permite elegir la ley de la nacionalidad para regir la sucesi\u00f3n, lo que para los nacionales de pa\u00edses de common law evita las legítimas espa\u00f1olas. La elecci\u00f3n debe ser expresa y el testamento espa\u00f1ol es su lugar natural. Es un documento breve y econ\u00f3mico; su ausencia la pagan \u00edntegramente quienes quedan.'] },
      { h2: 'Trabajar a distancia',
        p: ['Un poder general otorgado ante notario espa\u00f1ol o en consulado permite atender la mayor\u00eda de los asuntos sin su presencia: firmar, presentar declaraciones, acudir a citas y tratar con suministradoras y bancos.',
            'Conviene otorgarlo aprovechando un viaje y no cuando ya resulta urgente, porque hacerlo desde el extranjero exige apostilla y traducci\u00f3n y a\u00f1ade semanas.'] },
      { h2: 'C\u00f3mo funcionan los honorarios',
        p: ['La compraventa se presupuesta como porcentaje sobre el precio o como cantidad fija, acordada por escrito antes de empezar. El cumplimiento anual se presupuesta por declaraci\u00f3n. Los asuntos puntuales se presupuestan antes del encargo.',
            'La primera conversaci\u00f3n no tiene coste y a menudo termina con una opini\u00f3n sobre si hace falta abogada. A veces la respuesta es que no.'] },
    ],
    related: [{ href: '/es/compraventa/', label: 'Comprar una propiedad' },
              { href: '/es/gestion-de-propiedades/', label: 'Gesti\u00f3n de propiedades' }],
  },
  'compraventa': {
    metaTitle: "Comprar una propiedad en España | Abogada Sotogrande",
    metaDesc: "Asesoramiento independiente para el comprador, del NIE a las llaves: comprobaciones, cláusulas del contrato de arras, plazos reales y coste total de la operación.",
    faq: [
      {
            "q": "¿Cuánto se tarda en comprar una vivienda en España?",
            "a": "Una segunda transmisión sencilla suele completarse en seis a diez semanas desde la firma del contrato de arras hasta la escritura. Lo que alarga el plazo casi nunca es la tramitación en sí, sino la espera de cita para el NIE, la tasación de la hipoteca o la resolución de algo detectado en las comprobaciones, como una ampliación no inscrita o una herencia sin completar en el título del vendedor."
      },
      {
            "q": "¿Tengo que estar en España para comprar?",
            "a": "No. Con un poder notarial puedo completar toda la compra en su nombre, incluida la firma ante notario. Puede otorgarse ante notario español, en un consulado o ante notario local con apostilla y traducción jurada. Una parte considerable de las compras se cierra sin que el comprador viaje."
      },
      {
            "q": "¿Cuánto debo prever además del precio?",
            "a": "Entre un diez y un doce por ciento en una segunda transmisión en Andalucía. El ITP está en el siete por ciento, y notaría, Registro y honorarios completan el resto. La obra nueva del promotor tributa por IVA al diez por ciento más AJD, lo que resulta algo superior."
      },
      {
            "q": "¿Qué es el contrato de arras y cuánto se entrega?",
            "a": "Es el contrato de reserva, y la señal suele situarse entre el tres y el diez por ciento del precio. En las arras penitenciales, quien desiste pierde la señal y el vendedor que desiste devuelve el doble. No todo contrato que se presenta sigue ese modelo, por eso debe leerse antes de firmar."
      },
      {
            "q": "¿Qué ocurre si me deniegan la hipoteca después de entregar la señal?",
            "a": "Sin condición expresa de financiación en el contrato de arras, la denegación es problema del comprador y la señal se pierde. Es una de las dos cláusulas que siempre negocio, y la forma más habitual en que un comprador extranjero pierde dinero en España."
      },
      {
            "q": "¿Puedo comprar si no soy ciudadano de la UE?",
            "a": "Sí. No existe restricción para que un extranjero compre en España, sea cual sea el importe. Lo que cambió en abril de 2025 es que la compra ya no otorga derecho de residencia, al derogarse la Golden Visa. Comprar y residir son ahora cuestiones independientes."
      }
    ],
    image: 'villa-pool-costa-del-sol', imageAlt: 'Villa con piscina en la Costa del Sol, típica de las compraventas en Sotogrande', eyebrow: 'Servicio', title: 'Comprar una propiedad en Espa\u00f1a',
    intro: 'Asesoramiento independiente desde la primera b\u00fasqueda hasta las llaves, actuando solo para el comprador.',
    nav: 'Comprar una propiedad',
    sections: [
      { h2: 'Nadie m\u00e1s en la operaci\u00f3n trabaja para usted',
        p: ['Es lo que la mayor\u00eda de los compradores extranjeros descubre tarde. A la agencia le paga el vendedor al firmar, de modo que su inter\u00e9s est\u00e1 en cerrar la venta. El notario es un funcionario p\u00fablico cuya funci\u00f3n es dar fe de la escritura y verificar identidades, no investigar si la finca tiene una ampliaci\u00f3n no declarada o cuotas impagadas. El abogado de la promotora trabaja para la promotora.',
            'El comprador se queda sin nadie que revise la propiedad salvo que contrate a alguien. Es la mayor diferencia estructural respecto a comprar en el Reino Unido o Irlanda, y explica por qu\u00e9 la representaci\u00f3n independiente importa aqu\u00ed m\u00e1s, no menos.'] },
      { h2: 'Antes de que se mueva ning\u00fan dinero',
        p: ['El contrato de arras es normalmente el primer momento en que se pide dinero al comprador, habitualmente entre un tres y un diez por ciento del precio. Se firma con frecuencia a los pocos d\u00edas de aceptarse la oferta y antes de que nadie independiente lo haya le\u00eddo.',
            'En las arras penitenciales, quien desiste pierde la se\u00f1al y el vendedor que desiste devuelve el doble. Casi todos dan por supuesta esa simetr\u00eda. Las arras confirmatorias y las penales funcionan de otro modo, y la denominaci\u00f3n del documento no siempre coincide con su contenido real.',
            'Dos cl\u00e1usulas importan m\u00e1s que las dem\u00e1s: qu\u00e9 ocurre si se deniega su hipoteca y qu\u00e9 ocurre si el vendedor no puede firmar en plazo por no haber cancelado una carga. Sin condici\u00f3n expresa de financiaci\u00f3n, la denegaci\u00f3n es problema suyo y la se\u00f1al se pierde.'] },
      { h2: 'Qu\u00e9 comprenden realmente las comprobaciones',
        list: ['Nota simple: titular registral, descripci\u00f3n de la finca y todas las cargas inscritas',
               'Hipotecas, embargos y procedimientos judiciales pendientes',
               'Certificado de la comunidad acreditando que las cuotas est\u00e1n al corriente',
               'Recibos de IBI y cualquier tributo municipal pendiente',
               'Situaci\u00f3n urban\u00edstica en el ayuntamiento, incluidas ampliaciones, piscinas y terrazas',
               'Licencia de primera ocupaci\u00f3n cuando la obra sea relativamente reciente',
               'Contraste entre catastro y Registro en superficie y linderos',
               'Certificado de eficiencia energ\u00e9tica, que debe aportar el vendedor'] },
      { h2: 'La secuencia y sus plazos',
        p: ['El NIE de cada comprador es lo primero, porque sin \u00e9l apenas puede hacerse nada. La disponibilidad de cita condiciona los plazos m\u00e1s que la propia documentaci\u00f3n.',
            'La due diligence y la revisi\u00f3n del contrato avanzan en paralelo a la apertura de cuenta bancaria y a la planificaci\u00f3n de la transferencia de fondos. Con hipoteca, la tasaci\u00f3n y la aprobaci\u00f3n del banco marcan el ritmo.',
            'La firma se realiza ante notario: pago, otorgamiento y entrega de llaves en el mismo acto. Inmediatamente despu\u00e9s se liquidan los impuestos y se presenta la escritura a inscripci\u00f3n, que es lo que hace oponible su titularidad frente a terceros.',
            'Una segunda transmisi\u00f3n sencilla suele completarse en seis a diez semanas desde la reserva. Cualquier irregularidad registral, una herencia en el t\u00edtulo del vendedor o una obra sin licencia alargan el plazo.'] },
      { h2: 'Qu\u00e9 cuesta adem\u00e1s del precio',
        p: ['Prevea entre un diez y un doce por ciento sobre el precio en una segunda transmisi\u00f3n en Andaluc\u00eda. El ITP est\u00e1 actualmente en el siete por ciento. La obra nueva del promotor tributa por IVA al diez por ciento m\u00e1s AJD. Notar\u00eda, Registro y honorarios completan el resto.',
            'Un dato sorprende a menudo: el valor de referencia fija una base m\u00ednima de tributaci\u00f3n. Si el precio pactado queda por debajo, se liquida sobre el valor de referencia y no sobre lo efectivamente pagado. Conviene comprobarlo antes de acordar el precio.'] },
      { h2: 'Si no est\u00e1 en Espa\u00f1a',
        p: ['Un poder notarial permite completar toda la compra en su nombre, incluida la firma ante notario. Puede otorgarse ante notario espa\u00f1ol, en un consulado de Espa\u00f1a o ante notario local con apostilla y traducci\u00f3n jurada.',
            'Una parte considerable de las compras se cierra sin que el comprador viaje. Conviene prepararlo con antelaci\u00f3n y no cuando ya resulta urgente.'] },
      { h2: 'Despu\u00e9s de la firma',
        p: ['Quedan la inscripci\u00f3n, el traspaso de suministros, la comunicaci\u00f3n a la comunidad de propietarios y el cambio de titular en el IBI. Desde el primer a\u00f1o completo de propiedad nace la obligaci\u00f3n de presentar la declaraci\u00f3n anual de no residentes, se alquile o no el inmueble.'] },
    ],
    related: [{ href: '/es/derecho-inmobiliario/', label: 'Derecho inmobiliario en Espa\u00f1a' },
              { href: '/es/fiscalidad/', label: 'Impuestos de la compra y obligaciones anuales' },
              { href: '/es/residencia-y-visados/', label: 'Si la residencia forma parte del plan' }],
  },
  'venta-de-propiedades': {
    metaTitle: "Vender una propiedad en España | Abogada Sotogrande",
    metaDesc: "Ganancia patrimonial, la retención del 3% a no residentes y cómo recuperarla, la plusvalía tras la reforma de 2021 y la repatriación del importe de la venta.",
    image: 'property-keys-handover-spain', imageAlt: 'Entrega de llaves en la firma de una compraventa en España', eyebrow: 'Servicio', title: 'Vender una propiedad en Espa\u00f1a',
    intro: 'Ganancia patrimonial, la retenci\u00f3n del 3% a no residentes y la repatriaci\u00f3n del importe.',
    nav: 'Vender una propiedad',
    sections: [
      { h2: 'La retenci\u00f3n del tres por ciento',
        p: ['Si el vendedor no es residente fiscal en Espa\u00f1a, el comprador debe retener el tres por ciento del precio e ingresarlo mediante el modelo 211 a cuenta de la ganancia patrimonial. No es opcional ni negociable: el comprador que no lo hace responde \u00e9l mismo del importe.',
            'Cuando la deuda real es inferior a la retenci\u00f3n, o la venta arroja p\u00e9rdida, el exceso se recupera presentando el modelo 210 dentro de los tres meses siguientes al ingreso. Las devoluciones no son autom\u00e1ticas ni r\u00e1pidas: de seis a doce meses es lo habitual, y Hacienda requerir\u00e1 la documentaci\u00f3n de adquisici\u00f3n.'] },
      { h2: 'Preparar el expediente con antelaci\u00f3n',
        list: ['Nota simple con la situaci\u00f3n registral limpia y coincidente con lo que se vende',
               'Certificado de la comunidad sin deudas, que exigir\u00e1 el notario',
               'Recibos de IBI y certificado de eficiencia energ\u00e9tica',
               'Licencia de primera ocupaci\u00f3n cuando proceda',
               'Justificaci\u00f3n del coste de adquisici\u00f3n y de todos los gastos deducibles',
               'Certificados de suministros al corriente',
               'Si el inmueble se hered\u00f3, acreditaci\u00f3n de que la sucesi\u00f3n se complet\u00f3 y liquid\u00f3'] },
      { h2: 'Qu\u00e9 reduce la ganancia',
        p: ['Ambos valores admiten ajuste. Del lado de la adquisici\u00f3n, el ITP satisfecho, la notar\u00eda, el Registro y los honorarios incrementan el valor de compra, igual que las mejoras documentadas, aunque no el mantenimiento ordinario ni la simple redecoraci\u00f3n.',
            'Del lado de la transmisi\u00f3n, la comisi\u00f3n de la agencia y los honorarios de la venta reducen el valor. La frontera entre mejora y mantenimiento es donde se concentra la discusi\u00f3n, y las facturas pesan m\u00e1s que los recuerdos.'] },
      { h2: 'Plusval\u00eda municipal',
        p: ['Se calcula sobre el incremento del valor catastral del suelo y corresponde por lo general al vendedor, aunque las partes pueden pactar otra cosa. Desde la sentencia del Constitucional de 2021 existen dos m\u00e9todos y puede elegirse el m\u00e1s favorable. Si no ha habido incremento real, no se devenga, pero acreditarlo exige las escrituras de compra y de venta.'] },
      { h2: 'Sacar el dinero',
        p: ['Las transferencias al exterior por encima de ciertos importes son declarables, y los bancos exigir\u00e1n justificar el origen de los fondos conforme a la normativa de prevenci\u00f3n del blanqueo. La escritura de venta y las liquidaciones correspondientes lo acreditan, pero el requerimiento suele llegar en el peor momento si nadie lo ha previsto.'] },
      { h2: 'Si no est\u00e1 en Espa\u00f1a',
        p: ['Igual que en la compra, un poder notarial permite completar la venta en su nombre, incluida la firma y las liquidaciones posteriores. Para un vendedor no residente suele ser la v\u00eda pr\u00e1ctica, porque el trabajo fiscal contin\u00faa meses despu\u00e9s de la firma.'] },
    ],
    related: [{ href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' },
              { href: '/es/derecho-inmobiliario/', label: 'Derecho inmobiliario en Espa\u00f1a' }],
  },
  'residencia-y-visados': {
    metaTitle: "Residencia y visados en España 2026 | Pujol Wilkie",
    metaDesc: "No lucrativa, nómada digital, emprendimiento y vías familiares comparadas, con sus umbrales de ingresos y la regla de los 183 días de residencia fiscal.",
    faq: [
      {
            "q": "¿Qué visado me corresponde?",
            "a": "Depende de cómo genera sus ingresos y no de lo que posee. Las rentas pasivas apuntan a la no lucrativa. El trabajo en remoto para empresas de fuera, a la de nómada digital. Un negocio real aquí, a las vías de cuenta propia o emprendimiento."
      },
      {
            "q": "¿Puedo trabajar en remoto con una no lucrativa?",
            "a": "No, y esa es precisamente la diferencia con el visado de nómada digital. La no lucrativa exige no trabajar, de modo que quien trabaja en remoto debe solicitar por la vía de nómada digital."
      },
      {
            "q": "¿Cuánto tarda la tramitación?",
            "a": "Varía bastante según consulado y vía. La parte más larga suele ser reunir la documentación, porque los certificados extranjeros requieren apostilla y traducción jurada y tienen periodos de validez de tres o seis meses. El orden importa más que la rapidez."
      },
      {
            "q": "¿Seré residente fiscal en España?",
            "a": "Si permanece más de 183 días al año, por regla general sí, por su renta mundial. Tener aquí el núcleo principal de intereses económicos puede producir el mismo resultado incluso por debajo de ese umbral. Conviene calcularlo antes de solicitar."
      }
    ],
    image: 'spanish-visa-application', imageAlt: 'Formulario de solicitud de visado español', eyebrow: 'Servicio', title: 'Residencia y visados',
    intro: 'Las v\u00edas que siguen abiertas en 2026 y cu\u00e1l encaja en su situaci\u00f3n.',
    nav: 'Residencia y visados',
    sections: [
      { h2: 'Elegir la v\u00eda',
        p: ['Desde el cierre del visado de inversores en abril de 2025, la residencia depende de c\u00f3mo se generan los ingresos y no de lo que se posee. La pregunta pr\u00e1ctica es si su renta es pasiva, remota, por cuenta propia o de empleo en Espa\u00f1a, y cu\u00e1nto tiempo piensa pasar aqu\u00ed.',
            'Casi todas las v\u00edas exigen ahora presencia real. La idea de mantener residencia espa\u00f1ola viviendo fuera ya no se sostiene, y ese solo cambio reordena la decisi\u00f3n de la mayor\u00eda.'] },
      { h2: 'Residencia no lucrativa',
        p: ['Para quien dispone de rentas pasivas suficientes y no va a trabajar en Espa\u00f1a. El umbral se fija como m\u00faltiplo del IPREM, con un importe adicional por cada familiar a cargo, y debe acreditarse con ahorros, pensiones, rentas de alquiler o inversiones, no con un salario.',
            'Se exige seguro m\u00e9dico privado de cobertura completa y sin copagos, as\u00ed como certificado de antecedentes penales legalizado y traducido. La autorizaci\u00f3n es inicialmente de un a\u00f1o y se renueva por periodos de dos. Presupone residencia superior a 183 d\u00edas anuales, lo que convierte al titular en residente fiscal.'] },
      { h2: 'Visado de n\u00f3mada digital',
        p: ['Para quien trabaja en remoto por cuenta ajena o presta servicios a empresas radicadas fuera de Espa\u00f1a. Por cuenta ajena suele exigirse antig\u00fcedad m\u00ednima en la relaci\u00f3n laboral y autorizaci\u00f3n del empleador para el trabajo a distancia. Por cuenta propia se admite facturaci\u00f3n a clientes espa\u00f1oles solo hasta un porcentaje limitado.',
            'El umbral de ingresos se vincula al salario m\u00ednimo interprofesional. El mayor atractivo es el acceso al r\u00e9gimen fiscal especial de trabajadores desplazados, que puede reducir sensiblemente el tipo efectivo durante un n\u00famero determinado de a\u00f1os, si bien los requisitos son m\u00e1s estrictos de lo que sugiere la descripci\u00f3n general y conviene confirmarlos antes de solicitar.'] },
      { h2: 'Otras v\u00edas',
        list: ['Cuenta propia y emprendimiento, con plan de negocio y, en su caso, informe favorable de ENISA',
               'Tarjeta azul UE, para empleo altamente cualificado',
               'Reagrupaci\u00f3n familiar con un residente en Espa\u00f1a',
               'Familiar de ciudadano de la UE, procedimiento distinto y por lo general m\u00e1s \u00e1gil',
               'Arraigo, en sus distintas modalidades, para quien ya lleva tiempo en Espa\u00f1a',
               'Autorizaciones de estudios, modificables en ciertos casos a autorizaci\u00f3n de trabajo'] },
      { h2: 'La fiscalidad sigue a la residencia',
        p: ['Cualquier v\u00eda que implique m\u00e1s de 183 d\u00edas al a\u00f1o en Espa\u00f1a le har\u00e1, por regla general, residente fiscal por su renta mundial. Tener aqu\u00ed el n\u00facleo principal de intereses econ\u00f3micos puede producir el mismo resultado incluso por debajo de ese umbral.',
            'Eso significa que rentas, pensiones, inversiones y ganancias de cualquier origen pasan a ser declarables en Espa\u00f1a, con aplicaci\u00f3n de los convenios de doble imposici\u00f3n. Los bienes en el extranjero por encima de los umbrales deben declararse mediante el modelo 720.',
            'Calcularlo antes de presentar la solicitud, y no despu\u00e9s de llegar, evita el error m\u00e1s caro. Estructurar la situaci\u00f3n de antemano es bastante m\u00e1s sencillo que deshacerla una vez iniciada la residencia.'] },
      { h2: 'C\u00f3mo se tramita',
        p: ['La mayor\u00eda de las v\u00edas se solicitan en el consulado espa\u00f1ol del pa\u00eds de residencia o, en algunos casos, desde Espa\u00f1a. Concedida la autorizaci\u00f3n, se entra, se obtiene el TIE y se realiza el empadronamiento.',
            'Los plazos var\u00edan mucho seg\u00fan consulado y v\u00eda, y los documentos extranjeros requieren apostilla y traducci\u00f3n jurada, lo que lleva m\u00e1s tiempo del previsto. Empezar pronto con la documentaci\u00f3n suele marcar la diferencia.'] },
    ],
    related: [{ href: '/es/golden-visa-espana/', label: 'Qu\u00e9 pas\u00f3 con la Golden Visa' },
              { href: '/es/tramites-de-extranjeria/', label: 'Tr\u00e1mites de extranjer\u00eda' }],
  },
  'gibraltar-y-espana': {
    metaTitle: "Gibraltar y España: asesoramiento transfronterizo",
    metaDesc: "Trabajadores transfronterizos, sociedades gibraltareñas con inmuebles en España y modelo 720, con una abogada que ha ejercido en Reino Unido, Gibraltar y España.",
    image: 'rock-of-gibraltar-from-spain', imageAlt: 'El Peñón de Gibraltar visto desde la costa española cerca de Sotogrande', eyebrow: 'Servicio', title: 'Gibraltar y Espa\u00f1a',
    intro: 'Asuntos transfronterizos para trabajadores, sociedades gibraltare\u00f1as y residentes entre ambas jurisdicciones.',
    nav: 'Gibraltar y Espa\u00f1a',
    sections: [
      { h2: 'Dos sistemas, un mismo trayecto',
        p: ['Sotogrande est\u00e1 a veinte minutos de la verja y mucha gente vive bajo un sistema y trabaja o tiene bienes bajo el otro. Habiendo ejercido en el Reino Unido, Gibraltar y Espa\u00f1a, asesoro sobre el punto en que ambos reg\u00edmenes se encuentran y no solo sobre uno de los dos lados.',
            'Buena parte de las dificultades en esta materia proviene de asesores que conocen a fondo una jurisdicci\u00f3n y la otra de o\u00eddas. Las cuestiones problem\u00e1ticas se sit\u00faan casi siempre en el hueco entre ambas.'] },
      { h2: 'Trabajadores transfronterizos',
        p: ['Quien reside en Espa\u00f1a y trabaja en Gibraltar es por lo general residente fiscal en Espa\u00f1a por su renta mundial, cotizando en Gibraltar por el empleo. El acuerdo fiscal de 2019 entre Espa\u00f1a y el Reino Unido en relaci\u00f3n con Gibraltar, el primero de su clase, establece reglas de desempate para determinar la residencia y prev\u00e9 el intercambio de informaci\u00f3n entre ambas administraciones.',
            'La consecuencia pr\u00e1ctica es que situaciones antes informales son ahora visibles para las dos partes. Quien haya venido tratando la cuesti\u00f3n con laxitud har\u00eda bien en revisarla antes de que se la pregunten.'] },
      { h2: 'Asuntos frecuentes',
        list: ['Trabajadores transfronterizos residentes en Espa\u00f1a y empleados en Gibraltar',
               'Residencia fiscal espa\u00f1ola y declaraci\u00f3n de rentas de origen gibraltare\u00f1o',
               'Sociedades de Gibraltar titulares de inmuebles en Espa\u00f1a',
               'Modelo 720 de bienes situados en el extranjero',
               'Traslados en cualquiera de las dos direcciones y la residencia resultante',
               'Sucesiones con bienes a ambos lados de la verja'] },
      { h2: 'Sociedades gibraltare\u00f1as con inmuebles en Espa\u00f1a',
        p: ['Estas estructuras fueron habituales y hoy resultan bastante menos atractivas. El acuerdo de 2019 contiene una regla espec\u00edfica por la que una sociedad gibraltare\u00f1a con bienes en Espa\u00f1a puede considerarse residente fiscal espa\u00f1ola, y Espa\u00f1a aplica adem\u00e1s un gravamen anual sobre inmuebles de entidades residentes en jurisdicciones calificadas como no cooperativas.',
            'Cuando la estructura ya existe, la cuesti\u00f3n \u00fatil suele ser si conviene deshacerla y qu\u00e9 consecuencias tendr\u00eda la transmisi\u00f3n. Ese c\u00e1lculo exige considerar ambas jurisdicciones a la vez y rara vez arroja el mismo resultado dos veces.'] },
      { h2: 'La situaci\u00f3n actual',
        p: ['El marco convencional que regula la relaci\u00f3n entre Gibraltar y la Uni\u00f3n Europea lleva negoci\u00e1ndose desde el Brexit y ha tardado considerablemente en asentarse. Las disposiciones sobre la verja, aduanas y circulaci\u00f3n de personas han estado sujetas a medidas transitorias.',
            'Todo lo que dependa de plazos en esta materia conviene confirmarlo en el momento de decidir y no apoyarse en una descripci\u00f3n general, incluida esta.'] },
    ],
    related: [{ href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' },
              { href: '/es/residencia-y-visados/', label: 'Residencia y visados' }],
  },
};
export default pages;
