// Page content. `legacy: true` marks URLs inherited from the WordPress site that
// must keep their path. New services sit on new paths alongside them.
const pages = {
// ---- non-service pages ----
  'about': {
    legacy: true, image: 'esther-pujol-wilkie-abogada-sotogrande',
    imageAlt: 'Esther Pujol Wilkie, abogada, in her Sotogrande office',
    portrait: true, imageCaption: 'Esther Pujol Wilkie, abogada \u00b7 Colegiada n\u00ba 1432, ICA C\u00e1diz',
    metaTitle: 'Esther Pujol Wilkie, Abogada in Sotogrande',
    metaDesc: 'Spanish lawyer specialising in property law for foreigners. Qualified in Barcelona in 1983, practised in Scotland and Gibraltar, in Sotogrande since 1990.',
    eyebrow: 'About',
    title: 'Esther Pujol Wilkie',
    intro: 'A Spanish lawyer specialising in property law, particularly for foreigners investing in, and relocating to, Spain.',
    nav: 'About',
    sections: [
      { h2: 'Barcelona, Edinburgh, Gibraltar, Sotogrande',
        p: ['I qualified in Barcelona in 1983 and moved to Edinburgh, where I practised for five years as the only Spanish lawyer in Scotland at that time. During those years I also worked in the International Division of the Bank of Scotland and obtained a Diploma from the Scottish Institute of Bankers, and I collaborated with the Law Society of Scotland, the Spanish Consulate in Edinburgh and a number of British law and media groups.',
            'In 1988 I moved to Gibraltar to join the Spanish legal team at Hassans, then in joint venture with Plazas Abogados. Shortly afterwards I transferred to their newly opened Sotogrande office, where I remained as Managing Partner until 2010, followed by a period as a partner at the international firm KONSILIA, specialising in property law and fiscal accounting.',
            'In 2012 I set out on my own, with the same work ethic and a clearer vision: to continue helping and collaborating with international clients and entrepreneurs developing business and investment in Spain and beyond.'] },
      { h2: 'Where we work',
        p: ['The office is in Guadalmarina, on Avenida de la Marina in La Marina de Sotogrande. We cover the whole Andalusian coast, particularly Marbella and Estepona, and frequently take on projects elsewhere in Spain, including Barcelona.',
            'A good deal of the work is done at a distance under power of attorney, for clients who are not in Spain for much of the year.'] },
      { h2: 'How we work',
        list: ['Honesty and integrity', 'Trust', 'Excellence', 'Creativity', 'Vision', 'Adaptability'],
        p: ['Our philosophy is a simple one: making the client feel safe at home.'] },
      { h2: 'Languages and qualifications',
        list: ['Spanish and English, both fluent, with everything explained clearly',
               'Qualified in Barcelona, 1983',
               'Colegiada n\u00ba 1432, Ilustre Colegio Provincial de Abogados de C\u00e1diz',
               'Diploma, Scottish Institute of Bankers',
               'Practised in the United Kingdom, Gibraltar and Spain',
               'Diploma en Competencias Digitales Profesionales, Uni\u00f3n Profesional and CGAE, 2026'] },
    ],
    related: [
      { href: '/full-client-service/', label: 'The full range of services' },
      { href: '/contact/', label: 'Get in touch' },
    ],
  },
  'contact': {
    legacy: true, image: 'polo-sotogrande', imageAlt: 'Polo match at Sotogrande',
    metaTitle: 'Contact | English Speaking Lawyer in Sotogrande',
    metaDesc: 'Write to Esther Pujol Wilkie about buying, selling or owning property in Spain. A personal reply, usually within one working day, in English or Spanish.',
    eyebrow: 'Contact',
    title: 'Contact',
    intro: 'Do not hesitate to reach out using the details below, or send a message using the form.',
    nav: 'Contact',
    sections: [
      { h2: 'Writing to us',
        p: ['I read and answer enquiries myself rather than passing them to an assistant, normally within one working day. A short note about what you are planning is enough to begin with.',
            'From there we can talk properly, understand what you need, and set out how we would go about it.'] },
      { h2: 'Helpful things to mention',
        list: ['Whether you are buying, selling, or already own something here',
               'Where the property is, or the area you are looking in',
               'Whether anything has been signed yet',
               'Your nationality and where you are tax resident',
               'Whether residency in Spain forms part of the plan'] },
    ],
    related: [
      { href: '/about/', label: 'About Esther Pujol Wilkie' },
      { href: '/full-client-service/', label: 'The full range of services' },
    ],
  },
  'property-law': {
    legacy: true, image: 'scales-of-justice-spanish-law', imageAlt: 'Scales of justice, representing Spanish legal practice',
    metaTitle: 'Property Law in Spain | Pujol Wilkie, Sotogrande',
    metaDesc: 'Property law in Spain for foreign owners, explained simply. Over thirty years helping clients buy, sell, let and own property along the Andalusian coast.',
    eyebrow: 'Practice area',
    title: 'Property Law in Spain',
    intro: 'If you are planning to acquire property in Spain, let us help you get it right first time.',
    nav: 'Property law',
    sections: [
      { h2: 'Getting it right first time',
        p: ['Whether you are here for the beaches, the golf, the polo, the sailing or a commercial venture, buying property in Spain is a happy experience when it is properly looked after. With more than thirty years of practice on this coast we have helped hundreds of clients through it.',
            'We can begin taking care of your requirements before you even step onto Spanish soil, from obtaining your NIE through to the purchase, the letting or the sale, and we advise on the tax that comes with owning here.'] },
      { h2: 'A system worth understanding',
        p: ['Spanish property law works differently from the English or Irish system. Ownership passes before a notary by public deed, and is then inscribed at the Land Registry, which is what makes it fully effective against everybody else.',
            'One practical point matters more than any other: charges and obligations attach to the property itself rather than to the person who created them. That is precisely why the checks we carry out beforehand are worth doing carefully.'] },
      { h2: 'What we look after',
        list: ['Purchases, sales and transfers of land and property',
               'Nota simple, charges and the full registry position',
               'The planning and licensing position at the town hall',
               'Contracts, from the reservation agreement through to the deed',
               'Lettings, both long term and holiday',
               'Inheritance, wills and succession affecting Spanish property',
               'Urban planning matters and, where it becomes necessary, litigation'] },
      { h2: 'How we work with you',
        p: ['My team and I take you by the hand through each stage, in English or Spanish, explaining what is happening and why. Where something needs resolving we tell you plainly and set out the options, so that decisions are yours and made with the full picture in front of you.'] },
    ],
    faq: [
      { q: 'What is a nota simple?',
        a: 'It is the Land Registry extract showing who owns the property, how it is described and anything registered against it. It is inexpensive and it is where every purchase properly begins.' },
      { q: 'Does the notary check the property for me?',
        a: 'The notary is a public official whose role is to witness the deed and confirm identity and capacity. Checking the physical, planning and registry position is separate work, and it is what we do for you before you commit.' },
      { q: 'What happens if the property has an extension that was never declared?',
        a: 'It is common enough and usually resolvable. Depending on the age of the work and the planning position it may be regularised, or reflected in the price and the deed. What matters is finding it early, which is part of what we do.' },
      { q: 'Should I make a Spanish will?',
        a: 'If you own property here, we would always recommend it. It makes matters far simpler for your family, and it is the natural place to elect the law of your own nationality to govern your succession, which many of our clients prefer.' },
    ],
    related: [
      { href: '/buying-property/', label: 'Buying a property in Spain' },
      { href: '/full-client-service/', label: 'The full range of services' },
    ],
  },
  'spanish-golden-visa': {
    legacy: true, image: 'spanish-visa-application', imageAlt: 'Spanish visa application form being completed',
    metaTitle: 'Spain Golden Visa: Closed April 2025 | Pujol Wilkie',
    metaDesc: 'The Spanish Golden Visa closed to new applications on 3 April 2025. What it means for existing holders, and the residency routes that remain open.',
    eyebrow: 'Residency',
    title: 'The Spanish Golden Visa',
    intro: 'The investor residency visa closed to new applications on 3 April 2025. Here is where that leaves things.',
    nav: 'Golden Visa',
    sections: [
      { h2: 'What has changed',
        p: ['The Golden Visa, formally the Residency Visa for Investors, was introduced in 2013 to encourage investment into Spain. It was repealed by Organic Law 1/2025 and stopped accepting new applications on 3 April 2025.',
            'Buying property in Spain remains entirely open to foreign nationals. It simply no longer carries an entitlement to residency, so the two are now separate questions and we are happy to advise on both.'] },
      { h2: 'If you already hold one',
        p: ['Existing holders are protected by the transitional provisions. If your authorisation was granted, or your application filed, before the cut off date, your position continues and renewal remains available while the original conditions are still met.',
            'If you are thinking of selling the property your visa was based upon, or you are approaching ten years of legal residency, do speak to us first. There are usually more options than people expect, and they are easier to arrange in advance.'] },
      { h2: 'The routes that remain',
        list: ['Non lucrative residency, for those with sufficient means who will not work in Spain',
               'Digital nomad visa, for those working remotely for companies outside Spain',
               'Self employment and entrepreneur routes, where there is a genuine business project',
               'EU Blue Card, for highly qualified employment',
               'Family reunification with a relative already resident here',
               'Free movement, for EU and EEA nationals and their families'],
        p: ['Each carries its own requirements and its own tax consequences. Which one suits you depends on how you earn and how much of the year you intend to spend in Spain, and that is a conversation worth having early.'] },
      { h2: 'A word on tax',
        p: ['Residency and tax residency are separate matters. Spending more than 183 days a year in Spain will generally make you tax resident here on your worldwide income, whichever permit you hold. It is much easier to plan for that in advance than to address it afterwards.'] },
    ],
    faq: [
      { q: 'Can I still apply for the Golden Visa?',
        a: 'No. New applications closed on 3 April 2025 and there is no replacement scheme. Buying property remains completely open to foreign nationals, but it no longer grants residency.' },
      { q: 'I already hold one. What happens now?',
        a: 'Your position is protected by the transitional provisions and renewal remains available while you continue to meet the original conditions. We are glad to review any renewal falling due.' },
      { q: 'Can I sell the property my visa was based on?',
        a: 'You can, but it will generally affect the basis for renewal, so it is worth planning the sale and your residency together. Do speak to us before committing to anything.' },
      { q: 'What replaced it?',
        a: 'Nothing replaces it exactly. The non lucrative, digital nomad, entrepreneur and family routes all remain open, though each expects you to spend a meaningful part of the year in Spain.' },
    ],
    related: [
      { href: '/residency-and-visas/', label: 'Residency and visas' },
      { href: '/immigration-and-foreigners-legal-procedures/', label: 'Immigration and legal procedures' },
    ],
  },
  'tax-and-accountancy': {
    legacy: true, image: 'coastal-property-costa-del-sol', imageAlt: 'Coastal property and marina on the Costa del Sol',
    metaTitle: 'Spanish Property Tax for Non Residents | Pujol Wilkie',
    metaDesc: 'Tax and accountancy for Spanish property owners, resident and non resident. We prepare and file your returns and keep you updated on changes in the law.',
    eyebrow: 'Practice area',
    title: 'Tax and Accountancy',
    intro: 'As a Spanish property owner or resident there are always certain tax liabilities. We take care of them for you.',
    nav: 'Tax and accountancy',
    sections: [
      { h2: 'Having someone look after it',
        p: ['It is essential to have professionals advising you and making sure the necessary annual or quarterly returns are presented on your behalf, in good time and correctly.',
            'We provide these services for individuals, both resident and non resident, whether the property is owned privately, held within a corporate structure, or part of a company with regular business activity.'] },
      { h2: 'What we take care of',
        list: ['Annual and quarterly returns, prepared and filed within the statutory time frames',
               'The non resident return, which applies whether or not the property is let',
               'Local taxes such as IBI, and the municipal charges that go with the property',
               'Tax arising on purchase, and the position on a future sale',
               'Company accounts and filings where there is a corporate structure',
               'Reporting of assets held outside Spain, where that applies to you'] },
      { h2: 'Keeping you up to date',
        p: ['Spanish tax changes more often than most people expect, and the rates and thresholds vary between regions. We keep our clients informed of anything relevant so that you are always in a position to comply, and we calculate the figures for your particular circumstances rather than working from a general rule.'] },
    ],
    faq: [
      { q: 'Do I need to file anything if my property sits empty?',
        a: 'Yes. Non resident owners file an annual return whether or not the property is let, and it is calculated from the cadastral value. We handle it as a matter of course for clients we look after.' },
      { q: 'What about rental income?',
        a: 'Rental income is declared quarterly, and the treatment differs depending on where you are tax resident. Since Brexit that distinction affects British owners in particular, so it is worth reviewing rather than assuming.' },
      { q: 'What tax arises when I sell?',
        a: 'There is a tax on the gain, and where the seller is not resident in Spain the buyer retains a percentage of the price on account of it. Where the retention exceeds the actual liability the excess can be reclaimed, and we take care of that filing.' },
      { q: 'Do I have to declare assets I hold abroad?',
        a: 'If you are tax resident in Spain and your assets abroad exceed the reporting thresholds, yes. It is straightforward once it is set up properly, and we will tell you whether it applies to you.' },
    ],
    related: [
      { href: '/selling-property/', label: 'Selling a property in Spain' },
      { href: '/property-management-services/', label: 'Property management' },
    ],
  },
  'immigration-and-foreigners-legal-procedures': {
    legacy: true, image: 'yachts-puerto-sotogrande', imageAlt: 'Yachts moored at Puerto de Sotogrande',
    metaTitle: 'Immigration Procedures in Spain | Pujol Wilkie',
    metaDesc: 'NIE, residency, TIE, citizenship and driving licence exchange handled on your behalf, with more than thirty years of experience in foreigners procedures.',
    eyebrow: 'Practice area',
    title: 'Immigration and Foreigners\u2019 Legal Procedures',
    intro: 'Managing your affairs in Spain calls for an adviser with a thorough understanding, and proper care and diligence.',
    nav: 'Immigration procedures',
    sections: [
      { h2: 'An area we know well',
        p: ['This is a field in which we have more than thirty years of experience and have built a reputation for reliable, dependable advice. We take care of the administrative and legal procedures on your behalf, usually under a power of attorney so that you need not attend in person.'] },
      { h2: 'Procedures we handle',
        list: ['NIE, the foreigner identification number',
               'Authorisations of residency, with or without activity, including for work, family reunification and study',
               'TIE, the residence card, and its renewals',
               'Residence certificates for EU nationals',
               'Citizenship applications',
               'Driving licence exchange',
               'Empadronamiento and registration with the town hall',
               'Legalisation, apostille and sworn translation of documents from abroad'] },
      { h2: 'British nationals since Brexit',
        p: ['Those who were legally resident in Spain before 31 December 2020 retain their rights under the Withdrawal Agreement, evidenced by the TIE. Those who arrived afterwards follow the same routes as any other non EU national.',
            'The distinction matters a good deal in practice, particularly for people who spent time here before 2021 without formally registering, and we are happy to tell you where you stand.'] },
      { h2: 'A tailormade service',
        p: ['Every situation is a little different. Write to us describing yours and we will advise you on what is needed and how we would go about it.'] },
    ],
    faq: [
      { q: 'What is an NIE and when do I need one?',
        a: 'It is your Spanish identification number for tax purposes, needed to buy property, open a bank account or pay tax here. We obtain it on your behalf and it is usually the first thing we arrange.' },
      { q: 'Do I have to attend appointments in person?',
        a: 'Usually not. With a power of attorney we can attend on your behalf for most procedures, which is how a good number of our clients prefer to handle it.' },
      { q: 'How long do these procedures take?',
        a: 'It varies by procedure and by office. Gathering documents is often the longest part, since papers from abroad need apostille and sworn translation and carry their own validity periods, so starting early makes a real difference.' },
    ],
    related: [
      { href: '/residency-and-visas/', label: 'Residency and visas' },
      { href: '/full-client-service/', label: 'The full range of services' },
    ],
  },
  'property-management-services': {
    legacy: true, image: 'yachts-puerto-sotogrande', imageAlt: 'Yachts moored at Puerto de Sotogrande',
    metaTitle: 'Property Management in Sotogrande | Pujol Wilkie',
    metaDesc: 'Property management and concierge for owners who are not in Spain year round: supervision, utilities, local taxes, maintenance and gardens.',
    eyebrow: 'Practice area',
    title: 'Property Management Services',
    intro: 'Peace of mind while you are away, through our property management and concierge department.',
    nav: 'Property management',
    sections: [
      { h2: 'Looking after your property while you are away',
        p: ['Many owners are unable to travel to Spain whenever they would like, and are understandably concerned about security, maintenance and repair. Our property management and concierge department exists for exactly that reason.'] },
      { h2: 'This service can include',
        list: ['Property supervision: general checking and reporting on electricity, water, post and security',
               'Utility bill management',
               'Payment of local taxes such as IBI',
               'Cleaning and laundry',
               'Gardening and landscaping',
               'Pool maintenance',
               'General painting, repair and refurbishment',
               'Vehicle maintenance, repair and inspections'] },
      { h2: 'Arranging it',
        p: ['Every property is different, and so is how much attention it needs. Write to us describing the property and how often you are here, and we will put together a proposal for you.'] },
    ],
    related: [
      { href: '/full-client-service/', label: 'Full client service' },
      { href: '/contact/', label: 'Get in touch' },
    ],
  },
  'full-client-service': {
    legacy: true, image: 'polo-sotogrande', imageAlt: 'Polo match at Sotogrande',
    metaTitle: 'Full Client Service | Sotogrande Abogada',
    metaDesc: 'A comprehensive service across property, tax, inheritance, family, corporate and planning law, from one office in Sotogrande, in English and Spanish.',
    eyebrow: 'How we work',
    title: 'Full Client Service',
    intro: 'A fully comprehensive service, assisting in any area of the law our clients may require.',
    nav: 'Full client service',
    sections: [
      { h2: 'One office, the whole relationship',
        p: ['Most clients come to us for a single matter and stay for everything that follows. A purchase leads to the tax filings, the filings lead to a residency application, and years later the same office handles the sale or the inheritance.',
            'Keeping it together in one place means nothing is left assumed, and the person advising you later already knows the history.'] },
      { h2: 'Areas we deal with regularly',
        list: ['Property law',
               'Property management',
               'Inheritance and wills',
               'Taxation and accounting',
               'Investment procedures',
               'Family law',
               'Corporate law',
               'Litigation and dispute resolution',
               'Urban planning law',
               'Legalities for foreigners: residencies, driving licence exchange, TIE, NIE'] },
      { h2: 'Working with clients who are not here',
        p: ['A power of attorney allows us to handle most matters without your presence: signing at completion, filing returns, attending appointments and dealing with utilities and banks. It is worth arranging while you are in Spain for another reason rather than at the point it becomes urgent.'] },
    ],
    related: [
      { href: '/about/', label: 'About Esther Pujol Wilkie' },
      { href: '/contact/', label: 'Get in touch' },
    ],
  },

  // ---- new services, new URLs ----
  'buying-property': {
    image: 'villa-pool-costa-del-sol', imageAlt: 'Villa with pool on the Costa del Sol, typical of resale purchases in Sotogrande',
    metaTitle: 'Buying Property in Spain: Lawyer in Sotogrande',
    metaDesc: 'We guide foreign buyers through the whole purchase, from NIE to keys: searches, contracts, taxes and completion before the notary. Sotogrande and the Costa del Sol.',
    eyebrow: 'Service',
    title: 'Buying a Property in Spain',
    intro: 'We take you by the hand through the whole process, from the first enquiry to the keys.',
    nav: 'Buying property',
    sections: [
      { h2: 'We can start before you arrive',
        p: ['A good deal of a Spanish purchase can be prepared before you set foot here. We obtain your NIE, open the way for a bank account, and begin the searches on any property you are seriously considering, so that by the time you are ready to commit you already know what you are buying.',
            'If you cannot travel for the signing, a power of attorney allows us to complete on your behalf, including at the notary. A good many of our purchases complete without the buyer needing to be in Spain at all.'] },
      { h2: 'What we look at',
        list: ['The nota simple from the Land Registry: ownership, description and any charge registered against the property',
               'Mortgages, community fees, IBI and anything else outstanding, since these follow the property rather than the seller',
               'The planning position at the town hall, including any extension, pool or terrace',
               'Licencia de primera ocupación where the property is relatively recent',
               'The registry entry against the catastro record, which do not always agree on surface area or boundaries',
               'The reservation contract, before you are asked to sign it',
               'The tax position, so that the figures are known in advance rather than on the day'] },
      { h2: 'The reservation contract',
        p: ['The contrato de arras is usually the first document a buyer is asked to sign, and the point at which a deposit is paid. There is more than one kind, and the differences matter, particularly around what happens if a mortgage is not granted or if completion is delayed.',
            'We read it and, where appropriate, discuss amendments before signature. It is a straightforward conversation to have early and a much harder one to have later.'] },
      { h2: 'Completion and afterwards',
        p: ['Completion takes place before the notary, where payment, signature and the handover of keys happen together. Immediately afterwards we settle the taxes and submit the deed for inscription at the Land Registry.',
            'From there we transfer the utilities, notify the community, and put the annual tax filings in place. Most clients stay with us for that part, which continues quietly in the background for as long as they own the property.'] },
    ],
    faq: [
      { q: 'How long does it usually take?',
        a: 'A straightforward resale generally takes six to ten weeks from the reservation contract to completion. What tends to extend it is waiting for an NIE appointment or a mortgage valuation, or resolving something that comes up in the searches.' },
      { q: 'Do I need to be in Spain to buy?',
        a: 'No. With a power of attorney we can complete the entire purchase on your behalf, including signing at the notary. It can be granted before a Spanish notary, at a Spanish consulate, or before a local notary with an apostille and sworn translation.' },
      { q: 'What is an NIE and when do I need one?',
        a: 'The NIE is your Spanish identification number for tax purposes. You need one to buy a property, open a bank account or pay tax here, and it is usually the first thing we arrange.' },
      { q: 'Can I buy if I am not an EU citizen?',
        a: 'Yes. There is no restriction on foreign nationals buying property in Spain. Since April 2025 a purchase no longer carries any residency entitlement, so buying and residency are now separate matters, and we can advise on both.' },
      { q: 'What else should I budget for beyond the price?',
        a: 'There are taxes and official fees on any Spanish purchase, and they vary with the property and how it is bought. We set out the figures for your particular purchase at the outset, so nothing arrives unexpectedly.' },
    ],
    related: [
      { href: '/property-law/', label: 'Property law in Spain' },
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
      { href: '/contact/', label: 'Get in touch' },
    ],
  },
  'selling-property': {
    image: 'property-keys-handover-spain', imageAlt: 'Keys handed over on completion of a Spanish property purchase',
    metaTitle: 'Selling Property in Spain | Sotogrande Lawyer',
    metaDesc: 'We look after the sale of your Spanish property from preparing the file to completion, including the non resident retention and the return of any excess.',
    eyebrow: 'Service',
    title: 'Selling a Property in Spain',
    intro: 'We look after the sale from beginning to end, including everything that follows it.',
    nav: 'Selling property',
    sections: [
      { h2: 'Preparing the file',
        p: ['A sale goes far more smoothly when the paperwork is ready before a buyer appears. We gather what is needed and resolve anything outstanding, so that when an offer comes you are in a position to proceed.'] },
      { h2: 'What we put in order',
        list: ['The nota simple, confirming the registry position matches what is being sold',
               'A certificate from the community confirming nothing is outstanding',
               'IBI receipts and the energy performance certificate',
               'Licencia de primera ocupación where it applies',
               'Evidence of what the property cost you and of any improvements made',
               'Utility accounts, confirmed as current'] },
      { h2: 'Tax on the sale',
        p: ['Where the seller is not resident in Spain, the buyer is obliged to retain a percentage of the price and pay it to the tax authority on account of the tax on the gain. Where that exceeds the amount actually due, the excess can be reclaimed, and we make that filing for you.',
            'There is also the municipal tax on the increase in land value, normally payable by the seller. We calculate both, together with what may properly be deducted, and set the figures out for you before completion.'] },
      { h2: 'If you are not in Spain',
        p: ['As with a purchase, a power of attorney allows us to complete the sale on your behalf and to deal with the filings that follow. For a seller living abroad it is usually the most practical arrangement, since that work continues for some months afterwards.'] },
    ],
    faq: [
      { q: 'Why is the buyer withholding part of the price?',
        a: 'Because you are not tax resident in Spain. The buyer is legally obliged to retain a percentage and pay it to the tax authority on account of the tax on your gain. It is standard on every non resident sale.' },
      { q: 'Can I get that money back?',
        a: 'Where the retention is more than the tax actually due, yes, by filing within the prescribed period with the acquisition paperwork in support. We take care of it, though refunds do take some months to arrive.' },
      { q: 'What reduces the taxable gain?',
        a: 'The costs of acquiring the property and documented improvements to it, along with the costs of selling. Keeping invoices for work done is well worth it, and we will tell you what qualifies.' },
      { q: 'Can I sell without travelling to Spain?',
        a: 'Yes, under a power of attorney. We complete on your behalf and handle the tax filings and any reclaim afterwards.' },
    ],
    related: [
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
      { href: '/property-law/', label: 'Property law in Spain' },
    ],
  },
  'residency-and-visas': {
    image: 'spanish-visa-application', imageAlt: 'Spanish visa application form being completed',
    metaTitle: 'Spanish Residency and Visas in 2026 | Pujol Wilkie',
    metaDesc: 'Non lucrative, digital nomad, entrepreneur and family routes to Spanish residency, prepared and filed on your behalf from our Sotogrande office.',
    eyebrow: 'Service',
    title: 'Residency and Visas',
    intro: 'Whether or not you already have Spanish residency, we can provide the guidance and the steps required.',
    nav: 'Residency and visas',
    sections: [
      { h2: 'Finding the right route',
        p: ['Since the investor visa closed in April 2025, residency in Spain depends on how you earn rather than what you own. The practical question is whether your income is passive, remote, self employed or from employment here, and how much of the year you intend to spend in Spain.',
            'We talk it through with you first, so that the application we prepare is the one most likely to succeed rather than simply the best known.'] },
      { h2: 'The main routes',
        list: ['Non lucrative residency, for those with sufficient means who will not work in Spain',
               'Digital nomad visa, for remote work with companies outside Spain',
               'Self employment and entrepreneur routes, where there is a genuine business project',
               'EU Blue Card, for highly qualified employment',
               'Family reunification with a relative already resident in Spain',
               'Arraigo, for those who have already spent a qualifying period here',
               'Student authorisations, which can sometimes be modified later'] },
      { h2: 'What the process involves',
        p: ['Most routes are applied for at a Spanish consulate in your country of residence, or in some cases from within Spain. Once granted, you enter, obtain the TIE card and register with the town hall.',
            'The longest part is usually gathering the documents, since papers from abroad need apostille and sworn translation and carry their own validity periods. We tell you what is needed and in what order, which is where most of the delay is avoided.'] },
      { h2: 'Residency and tax',
        p: ['These are separate questions. A route that involves spending more than 183 days a year here will generally make you tax resident in Spain on your worldwide income. It is far easier to plan for that before applying than to unpick it later, and we will raise it with you at the outset.'] },
    ],
    faq: [
      { q: 'Which visa is right for me?',
        a: 'It depends on how you earn rather than what you own. Passive income points toward the non lucrative route, remote work toward the digital nomad visa, and a business here toward self employment. Tell us your circumstances and we will advise.' },
      { q: 'Can I work remotely on a non lucrative visa?',
        a: 'No, and that is the essential difference between the two. If you work remotely, the digital nomad route is the one designed for you.' },
      { q: 'How long does an application take?',
        a: 'It varies considerably by consulate and by route. Gathering and legalising the documents is usually the longer part, so we recommend starting that early.' },
      { q: 'Will I become tax resident in Spain?',
        a: 'If you spend more than 183 days a year here, generally yes, on your worldwide income. We raise this at the outset so it can be planned for rather than discovered afterwards.' },
    ],
    related: [
      { href: '/spanish-golden-visa/', label: 'What happened to the Golden Visa' },
      { href: '/immigration-and-foreigners-legal-procedures/', label: 'Immigration procedures' },
    ],
  },
  'gibraltar-and-spain': {
    image: 'rock-of-gibraltar-from-spain', imageAlt: 'The Rock of Gibraltar seen from the Spanish coast near Sotogrande',
    metaTitle: 'Gibraltar and Spain Cross Border Legal Advice',
    metaDesc: 'Cross border advice for frontier workers, Gibraltar companies holding Spanish property and those relocating between the two, from a lawyer who has practised in both.',
    eyebrow: 'Service',
    title: 'Gibraltar and Spain',
    intro: 'Advice that takes account of both sides of the frontier, from a lawyer who has practised on each.',
    nav: 'Gibraltar and Spain',
    sections: [
      { h2: 'Two systems, one community',
        p: ['Sotogrande sits twenty minutes from the frontier, and a good number of our clients live under one system while working or holding assets under the other.',
            'Having begun my Spanish practice with the Spanish legal team at Hassans in Gibraltar, and having practised in the United Kingdom before that, I advise on the point where the two meet rather than on one side only.'] },
      { h2: 'Matters we are asked about',
        list: ['Frontier workers resident in Spain and employed in Gibraltar',
               'Spanish tax residency and the reporting of Gibraltar income',
               'Gibraltar companies holding property in Spain',
               'Declaration of assets held outside Spain',
               'Relocation in either direction, and the residency position that results',
               'Succession where assets sit on both sides of the frontier'] },
      { h2: 'Structures holding Spanish property',
        p: ['Arrangements of this kind were once common and the position has changed considerably. Where such a structure already exists, the useful question is usually whether it still serves you and what the consequences of unwinding it would be. That calculation needs both jurisdictions considered together, and we are glad to look at it with you.'] },
      { h2: 'A moving picture',
        p: ['The framework governing the relationship between Gibraltar and the European Union has been some years in the making and continues to develop. Anything that depends on timing is worth confirming with us at the point of deciding rather than relying on a general description.'] },
    ],
    faq: [
      { q: 'I live in Spain and work in Gibraltar. Where do I pay tax?',
        a: 'Generally you are tax resident in Spain on your worldwide income while contributing in Gibraltar on the employment. The treaty between the two sets out how residency is determined, and we are happy to review your particular position.' },
      { q: 'I hold Spanish property through a Gibraltar company. Is that still sensible?',
        a: 'The position has changed a good deal in recent years and it is worth reviewing. Whether to keep or unwind such a structure depends on both jurisdictions, and we would look at it as a whole with you.' },
      { q: 'Do I need to declare my Gibraltar accounts in Spain?',
        a: 'If you are tax resident in Spain and your assets abroad exceed the reporting thresholds, yes. It is straightforward once set up correctly and we can take care of it.' },
    ],
    related: [
      { href: '/tax-and-accountancy/', label: 'Tax and accountancy' },
      { href: '/residency-and-visas/', label: 'Residency and visas' },
    ],
  },
};
export default pages;
