// Las páginas heredadas conservan su ruta original en inglés bajo /es/ con slug propio.
const pages = {
  'derecho-inmobiliario': {
    en: 'property-law', image: 'buying', eyebrow: 'Área de práctica',
    title: 'Derecho inmobiliario en España',
    intro: 'El marco legal que hay detrás de cada compraventa en España y lo que significa para un propietario extranjero.',
    nav: 'Derecho inmobiliario',
    sections: [
      { h2: 'Un sistema distinto al que usted conoce',
        p: ['La propiedad se transmite ante notario mediante escritura pública y solo despliega plenos efectos frente a terceros una vez inscrita en el Registro de la Propiedad. Hasta esa inscripción, la posición del comprador es más débil de lo que suele suponerse.',
            'La consecuencia práctica es que casi todo depende de las comprobaciones previas a la firma. Las deudas, las cargas y las irregularidades urbanísticas siguen a la finca, no a quien las generó, de modo que un comprador puede heredar problemas ajenos.'] },
      { h2: 'Lo que sigue a la finca, no al vendedor',
        list: ['Hipotecas y cualquier otra carga inscrita en el Registro',
               'Cuotas de comunidad impagadas, por lo general del año en curso y los tres anteriores',
               'IBI pendiente, el impuesto municipal anual',
               'Embargos y procedimientos judiciales en curso',
               'Infracciones urbanísticas por obras sin licencia o no declaradas'] },
      { h2: 'Los documentos que importan',
        p: ['La nota simple es el extracto registral que acredita la titularidad, la descripción de la finca y las cargas que pesan sobre ella. Es el punto de partida de toda compra y su coste es mínimo.',
            'El catastro es independiente y tiene finalidad fiscal. Ambos discrepan con frecuencia en superficie o linderos, y conviene conciliarlos antes de la firma para evitar problemas en una futura venta.'] },
    ],
    related: [{ href: '/es/compraventa/', label: 'Comprar una propiedad: el proceso completo' },
              { href: '/es/venta-de-propiedades/', label: 'Vender una propiedad en España' }],
  },
  'golden-visa-espana': {
    en: 'spanish-golden-visa', image: 'residency', eyebrow: 'Residencia',
    title: 'La Golden Visa española',
    intro: 'La vía de residencia por inversión se cerró el 3 de abril de 2025. Qué ocurre si ya la tiene y qué alternativas existen.',
    nav: 'Golden Visa',
    sections: [
      { h2: 'El programa ha terminado',
        p: ['El visado de residencia para inversores quedó derogado por la Ley Orgánica 1/2025, publicada en el BOE el 3 de enero de 2025 y con efectos desde el 3 de abril de 2025. Se suprimieron los artículos 63 a 67 de la Ley 14/2013, base legal del régimen desde 2013.',
            'No hay sustituto ni periodo transitorio para nuevas solicitudes. Comprar un inmueble en España ya no otorga ningún derecho de residencia, sea cual sea su valor.'] },
      { h2: 'Si ya es titular',
        p: ['Las disposiciones transitorias protegen a quienes obtuvieron la autorización, o presentaron la solicitud, antes de la fecha de corte. La renovación sigue siendo posible siempre que se mantengan las condiciones originales, incluida la inversión que dio derecho al permiso.',
            'Las renovaciones que venzan en 2026 y 2027 conviene revisarlas caso por caso y no darlas por hechas.'] },
      { h2: 'Qué queda disponible',
        list: ['Visado de residencia no lucrativa, con ingresos pasivos suficientes y sin trabajar en España',
               'Visado de nómada digital, para quienes trabajan en remoto para empresas fuera de España',
               'Vías de emprendimiento y trabajo por cuenta propia, con un proyecto empresarial real',
               'Tarjeta azul UE, para empleo altamente cualificado',
               'Reagrupación familiar con un residente en España'] },
      { h2: 'El punto fiscal que se suele pasar por alto',
        p: ['Residencia y residencia fiscal son cuestiones distintas. Permanecer más de 183 días en España en un año natural le convierte, por regla general, en residente fiscal aquí por su renta mundial, con independencia del permiso que tenga.'] },
    ],
    related: [{ href: '/es/residencia-y-visados/', label: 'Residencia y visados' },
              { href: '/es/tramites-de-extranjeria/', label: 'Trámites de extranjería' }],
  },
  'fiscalidad': {
    en: 'tax-and-accountancy', image: 'tax', eyebrow: 'Área de práctica',
    title: 'Fiscalidad y contabilidad',
    intro: 'Los impuestos de la compra, los que se repiten cada año y las declaraciones que hay que presentar viva o no en España.',
    nav: 'Fiscalidad',
    sections: [
      { h2: 'En la compra',
        p: ['Una segunda transmisión en Andalucía tributa por ITP, actualmente al 7%. La obra nueva del promotor tributa por IVA al 10% más AJD. Notaría, registro y honorarios se suman, y una previsión razonable es del 10 al 12% sobre el precio.',
            'El valor de referencia fija una base mínima de tributación. Cuando el precio pactado queda por debajo, se liquida sobre el valor de referencia.'] },
      { h2: 'Cada año, como propietario no residente',
        list: ['Modelo 210, se alquile o no el inmueble', 'IBI, impuesto municipal anual',
               'Cuotas de comunidad', 'Impuesto sobre el patrimonio, si se superan los umbrales'] },
      { h2: 'En la venta',
        p: ['La ganancia patrimonial tributa sobre la diferencia entre valor de adquisición y de transmisión. Si el vendedor no es residente, el comprador retiene un 3% del precio y lo ingresa en Hacienda a cuenta. Recuperar el exceso exige una presentación específica.'] },
    ],
    related: [{ href: '/es/venta-de-propiedades/', label: 'Vender una propiedad' }],
  },
  'tramites-de-extranjeria': {
    en: 'immigration-and-foreigners-legal-procedures', image: 'management', eyebrow: 'Área de práctica',
    title: 'Extranjería y trámites administrativos',
    intro: 'La maquinaria administrativa que acompaña a vivir o tener algo en España siendo extranjero.',
    nav: 'Extranjería',
    sections: [
      { h2: 'El papeleo del día a día',
        p: ['Lo difícil no suele ser la ley sino la administración: citas con semanas de espera, documentos que deben legalizarse o apostillarse y oficinas que rechazan un expediente por un solo campo mal cumplimentado.',
            'Tramito estos procedimientos en nombre del cliente, normalmente mediante poder notarial, de modo que no sea necesario acudir en persona.'] },
      { h2: 'Trámites que gestiono',
        list: ['NIE', 'Empadronamiento', 'TIE y sus renovaciones', 'Certificados de residencia para ciudadanos de la UE',
               'Canje de permiso de conducir y matriculación', 'Legalización, apostilla y traducción jurada'] },
      { h2: 'Para ciudadanos británicos tras el Brexit',
        p: ['Quienes residían en España antes del 31 de diciembre de 2020 conservan sus derechos bajo el Acuerdo de Retirada, acreditados con el TIE. Quienes llegaron después son nacionales de tercer país y necesitan una vía de visado. La distinción tiene consecuencias importantes.'] },
    ],
    related: [{ href: '/es/residencia-y-visados/', label: 'Residencia y visados' }],
  },
  'gestion-de-propiedades': {
    en: 'property-management-services', image: 'selling', eyebrow: 'Área de práctica',
    title: 'Gestión de propiedades',
    intro: 'Mantener una propiedad en España en orden cuando no se reside aquí la mayor parte del año.',
    nav: 'Gestión de propiedades',
    sections: [
      { h2: 'Qué necesita cubrir un propietario ausente',
        list: ['Contratos de suministro, traspasos, lecturas y domiciliaciones',
               'Cuotas de comunidad, correspondencia y representación en juntas',
               'Seguros de continente y contenido', 'IBI y tasa de basuras al día',
               'Custodia de llaves, acceso a gremios e inspecciones periódicas'] },
      { h2: 'Por qué importa',
        p: ['Las cuotas de comunidad y los tributos municipales impagados no prescriben sin más: se acumulan contra la finca y afloran en el momento de la venta, normalmente en el peor momento posible.'] },
    ],
    related: [{ href: '/es/servicio-integral/', label: 'Servicio integral al cliente' }],
  },
  'servicio-integral': {
    en: 'full-client-service', image: 'polo', eyebrow: 'Cómo trabajo',
    title: 'Servicio integral al cliente',
    intro: 'Asuntos legales, fiscales y administrativos atendidos desde un mismo despacho, mientras tenga algo aquí.',
    nav: 'Servicio integral',
    sections: [
      { h2: 'Un despacho, toda la relación',
        p: ['La mayoría de los clientes llega con una sola operación en mente y se queda para todo lo que viene después: la compra lleva a las declaraciones, las declaraciones a la residencia y, años más tarde, el mismo despacho gestiona la venta o la herencia.',
            'Tenerlo todo en un mismo sitio evita el supuesto de que algo ya lo habrá hecho otro, que es donde empiezan casi todos los problemas transfronterizos.'] },
      { h2: 'Qué incluye',
        list: ['Compraventa', 'Cumplimiento fiscal anual', 'Residencia y extranjería',
               'Testamentos, herencias y sucesiones', 'Gestión y administración de inmuebles',
               'Representación mediante poder notarial'] },
    ],
    related: [{ href: '/es/compraventa/', label: 'Comprar una propiedad' }],
  },
  'compraventa': {
    image: 'buying', eyebrow: 'Servicio', title: 'Comprar una propiedad en España',
    intro: 'Asesoramiento independiente desde la primera búsqueda hasta las llaves, actuando solo para el comprador.',
    nav: 'Comprar una propiedad',
    sections: [
      { h2: 'Antes de que se mueva ningún dinero',
        p: ['El contrato de arras es donde se pide el primer compromiso económico y se firma con frecuencia antes de que nadie independiente lo haya leído. En las arras penitenciales quien se retira pierde la señal y el vendedor que desiste devuelve el doble, pero la redacción varía y no todo contrato que se presenta es estándar.'] },
      { h2: 'La secuencia',
        list: ['NIE para cada comprador', 'Nota simple y due diligence completa',
               'Revisión y negociación del contrato de arras', 'Cuenta bancaria y planificación de fondos',
               'Firma ante notario, presencial o por poder', 'Impuestos, inscripción registral y traspaso de suministros'] },
      { h2: 'Si no está en España',
        p: ['Un poder notarial permite completar toda la operación en su nombre. Una parte considerable de las compras se cierra sin que el comprador viaje.'] },
    ],
    related: [{ href: '/es/derecho-inmobiliario/', label: 'Derecho inmobiliario en España' },
              { href: '/es/fiscalidad/', label: 'Impuestos de la compra' }],
  },
  'venta-de-propiedades': {
    image: 'selling', eyebrow: 'Servicio', title: 'Vender una propiedad en España',
    intro: 'Ganancia patrimonial, la retención del 3% a no residentes y la repatriación del importe.',
    nav: 'Vender una propiedad',
    sections: [
      { h2: 'La retención del 3%',
        p: ['Si el vendedor no es residente fiscal en España, el comprador retiene el 3% del precio y lo ingresa en Hacienda a cuenta de la ganancia. Cuando la deuda real es menor, el exceso se recupera, pero solo presentando en plazo y con la documentación en regla.'] },
      { h2: 'Preparar el expediente con antelación',
        list: ['Nota simple con la situación registral limpia', 'Certificado de la comunidad sin deudas',
               'Recibos de IBI y certificado energético', 'Licencia de primera ocupación cuando proceda',
               'Justificación del coste de adquisición y gastos deducibles'] },
      { h2: 'Plusvalía municipal',
        p: ['Se calcula sobre el incremento del valor catastral del suelo y corresponde al vendedor. Desde la reforma de 2021 existen dos métodos de cálculo y puede elegirse el más favorable.'] },
    ],
    related: [{ href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' }],
  },
  'residencia-y-visados': {
    image: 'residency', eyebrow: 'Servicio', title: 'Residencia y visados',
    intro: 'Las vías que siguen abiertas en 2026 y cuál encaja en su situación.',
    nav: 'Residencia y visados',
    sections: [
      { h2: 'Elegir la vía',
        p: ['Desde el cierre del visado de inversores en abril de 2025, la residencia depende de cómo se generan los ingresos, no de lo que se posee. La pregunta práctica es si su renta es pasiva, remota, por cuenta propia o de empleo en España, y cuánto tiempo piensa pasar aquí.'] },
      { h2: 'Las vías principales',
        list: ['No lucrativa: ingresos pasivos suficientes, sin trabajar en España',
               'Nómada digital: trabajo en remoto para empresas fuera de España, con umbral mínimo de ingresos',
               'Cuenta propia y emprendimiento: proyecto empresarial real',
               'Tarjeta azul UE: empleo altamente cualificado', 'Reagrupación familiar'] },
      { h2: 'La fiscalidad sigue a la residencia',
        p: ['Cualquier vía que implique más de 183 días al año en España le hará, por regla general, residente fiscal por su renta mundial. Conviene calcularlo antes de solicitar, no después de llegar.'] },
    ],
    related: [{ href: '/es/golden-visa-espana/', label: 'Qué pasó con la Golden Visa' }],
  },
  'gibraltar-y-espana': {
    image: 'gibraltar', eyebrow: 'Servicio', title: 'Gibraltar y España',
    intro: 'Asuntos transfronterizos para trabajadores, sociedades gibraltareñas y residentes entre ambas jurisdicciones.',
    nav: 'Gibraltar y España',
    sections: [
      { h2: 'Dos sistemas, un mismo trayecto',
        p: ['Sotogrande está a veinte minutos de la verja y mucha gente vive bajo un sistema y trabaja o tiene bienes bajo el otro. Habiendo ejercido en el Reino Unido, Gibraltar y España, asesoro sobre el punto en que ambos regímenes se encuentran.'] },
      { h2: 'Asuntos frecuentes',
        list: ['Trabajadores transfronterizos residentes en España y empleados en Gibraltar',
               'Residencia fiscal española y declaración de rentas de Gibraltar',
               'Sociedades gibraltareñas titulares de inmuebles en España',
               'Modelo 720 de bienes en el extranjero', 'Traslados en cualquiera de las dos direcciones'] },
      { h2: 'Sobre la situación actual',
        p: ['El marco del tratado que regula la relación entre Gibraltar y la UE lleva años en negociación y sigue sujeto a cambios. Todo lo que dependa de plazos conviene confirmarlo en el momento de decidir.'] },
    ],
    related: [{ href: '/es/fiscalidad/', label: 'Fiscalidad y contabilidad' }],
  },
};
export default pages;
